### ISSUE TITLE
TypeError: sequence item 2: expected str instance, dict found returned when template with conditional in locals is used 

### ISSUE THREAD

**Issue by nwsparks** [bridgecrewio/checkov#1071]
**Describe the bug**

This seems to have been introduced in checkov v2, it does not occur in v1

`TypeError: sequence item 2: expected str instance, dict found` returned when template with a conditional in locals is used 

```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.7/dist-packages/checkov/main.py", line 97, in run
    files=file, guidelines=guidelines, bc_integration=bc_integration)
  File "/usr/local/lib/python3.7/dist-packages/checkov/common/runners/runner_registry.py", line 35, in run
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/runner.py", line 83, in run
    parsing_errors=parsing_errors)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_manager.py", line 17, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 42, in build_graph
    renderer.render_variables_from_local_graph()
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/renderer.py", line 49, in render_variables_from_local_graph
    num_of_workers=self.max_workers)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/checks/utils/utils.py", line 221, in run_function_multithreaded
    raise e
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/checks/utils/utils.py", line 219, in run_function_multithreaded
    future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/renderer.py", line 77, in _edge_evaluation_task
    self.evaluate_vertex_attribute_from_edge(edges)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/renderer.py", line 121, in evaluate_vertex_attribute_from_edge
    val_to_eval = self.replace_value(edge, val_to_eval, replaced_key, evaluated_attribute_value, True)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/renderer.py", line 224, in replace_value
    replaced_value=replaced_value, keep_origin=keep_origin)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/evaluate_terraform.py", line 62, in replace_string_value
    original_str[i] = evaluate_terraform(original_str[i])
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/evaluate_terraform.py", line 36, in evaluate_terraform
    evaluated_value = evaluate_directives(evaluated_value)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/variable_rendering/evaluate_terraform.py", line 189, in evaluate_directives
    return ''.join(evaluated_string_parts)
TypeError: sequence item 2: expected str instance, dict found
```

**To Reproduce**

1. add this file in an empty directory
```
variable "use_splunk_logging" {
  default = false
}

locals {
  log_config = <<EOF
%{if var.use_splunk_logging}
{
  "logDriver": "splunk",
  "options": {
    "splunk-format": "json",
    "splunk-verify-connection": "false",
    "tag": "{{.Name}}"
  }
}
%{else}
{
  "logDriver": "awslogs",
  "options": {
    "awslogs-group": "hi",
    "awslogs-region": "us-east-1",
    "awslogs-stream-prefix": "app"
  }
}
%{endif~}
EOF
}
```

2. run `checkov -d . --framework terraform`

**Expected behavior**

It should just work without error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: using the docker image you guys provide
 - Checkov Version 2.0.34

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by nwsparks** [comment]
still a problem with the latest version

**Comment by nimrodkor** [comment]
Does not crash on checkov version 2.0.692
