### ISSUE TITLE
TypeError: can only concatenate list (not "str") to list when using or conditions in custom rules

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1110]
**Describe the bug**
When using an or condition in a custom rule, checkov errors if resource_types is given as a string:

```
metadata:
  name: "Ensure location is eu-west"
  id: "<id>"
  category: "CONVENTION"
definition:
  or:
    - cond_type: "attribute"
      resource_types: "google_bigquery_dataset"
      attribute: "location"
      operator: "contains"
      value: "europe-west"
    - cond_type: "attribute"
      resource_types: "google_bigquery_dataset"
      attribute: "region"
      operator: "contains"
      value: "europe-west"
```

```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 114, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=args.file,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 71, in run
    self.load_external_checks(external_checks_dir)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 119, in load_external_checks
    graph_registry.load_external_checks(directory)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/registry.py", line 41, in load_external_checks
    self._load_checks_from_dir(dir)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/registry.py", line 36, in _load_checks_from_dir
    check = self.parser.parse_raw_check(check_json, resources_types=self._get_resource_types(check_json))
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/checks_parser.py", line 51, in parse_raw_check
    check = self._parse_raw_check(policy_definition, kwargs.get("resources_types"))
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/checks_parser.py", line 70, in _parse_raw_check
    check.resource_types = list(set(sum(resources_types_of_sub_solvers, [])))
TypeError: can only concatenate list (not "str") to list

```

Passing resource_types as a list works correctly.

**To Reproduce**
1. Create a yaml file with the above custom rule, and run `checkov -f <your-file>.tf --external-checks-dir <your-path>`

**Expected behavior**
If the resource type is a string but inside a condition block, concat the strings to make a list (or allow value to be something like "option1|option2|option3" to avoid having to use or blocks)

**Desktop (please complete the following information):**
 - OS: os X
 - Checkov Version : 2.0.64

**Comment by nimrodkor** [comment]
Hey @dwilliams782 !
`resource_types` is plural, hinting to the fact it expects an array.
Please try setting the resource_types to an array of length 1 and testing this again.
