### ISSUE TITLE
TypeError: object of type 'NoneType' has no len() when using "all" custom check

### ISSUE THREAD

**Issue by dwilliams782** [bridgecrewio/checkov#1114]
**Describe the bug**
I'm trying to implement a custom check that makes sure all resources contains a label:

```
metadata:
  name: "Ensure environment label exists"
  id: "<id>"
  category: "CONVENTION"
definition:
  cond_type: "attribute"
  resource_types: "all"
  attribute: "labels.env"
  operator: "exists"

```

Using "all" rather than any explicit resource (e.g. it works with `google_storage_bucket`):
```
>checkov -f test_tf2/test_bucket2.tf --external-checks-dir checkov-custom      
         
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    exit(run())
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 114, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=args.file,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 110, in run
    graph_report = self.get_graph_checks_report(root_folder, runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 126, in get_graph_checks_report
    registry_results = r.run_checks(self.graph_manager.get_reader_traversal(), runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/graph/checks_infra/registry.py", line 19, in run_checks
    passed, failed = check.run(graph_connector)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/graph/checks_infra/base_check.py", line 18, in run
    return self.solver.run(graph_connector=graph_connector)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/solvers/attribute_solvers/base_attribute_solver.py", line 19, in run
    all_vertices_resource_types = [data for _, data in graph_connector.nodes(data=True) if
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks_infra/solvers/attribute_solvers/base_attribute_solver.py", line 20, in <listcomp>
    self.resource_type_pred(data, self.resource_types)]
  File "/usr/local/lib/python3.9/site-packages/checkov/common/graph/checks_infra/solvers/base_solver.py", line 24, in resource_type_pred
    return len(resource_types) == 0 or v.get('resource_type') in resource_types
TypeError: object of type 'NoneType' has no len()
```

**To Reproduce**
1. Create a custom check with "all" as a resource type

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: os X
 - Checkov Version 2.0.67

**Comment by nimrodkor** [comment]
Hey @dwilliams782 !

It seems your policy is missing the `scope` block. When you mention specific resource types, it is fine to leave this block out. However, when specifying 'all', it is also required to add a provider. Example for your policy:
```yaml
metadata:
  name: "Ensure environment label exists"
  id: "<id>"
  category: "CONVENTION"
scope:
  provider: gcp
definition:
  cond_type: "attribute"
  resource_types: "all"
  attribute: "labels.env"
  operator: "exists"
```

Please reference the relevant resource types as listed in [resource_types.py](https://github.com/bridgecrewio/checkov/blob/0f325a42f88d389a80fe5cf3f10f0e1684ff79e3/checkov/terraform/checks_infra/resources_types.py)

Hope this helps!

**Comment by dwilliams782** [comment]
Thank you, I took my example from the first example here which does not have a provider:

https://www.checkov.io/3.Custom%20Policies/Examples.html

**Comment by dwilliams782** [comment]
@nimrodkor do you know if this is supported in Python checks? Can't see `scope` or `provider` in the base class, but it's very possible I'm not looking in the right place?

**Comment by nimrodkor** [comment]
Hey @dwilliams782 , I just fixed the documentation. When using the `all` resource types, the query should contain a `scope.provider` attribute
