### ISSUE TITLE
Azure terraform error

### ISSUE THREAD

**Issue by serxansherif** [bridgecrewio/checkov#1223]
Hello,

I get the following error when scanning the tf files.

_ERROR:checkov.terraform.checks.resource.azure.NSGRuleUDPAccessRestricted:Failed to run check: Ensure that UDP Services are restricted from the Internet  for configuration: {'count': [1], 'location': ['WestEurope'], 'name': ['dev-nsg'], 'resource_group_name': ['dev-vm'], 'security_rule': ['lookup(rule,"destination_port_range",*):\\\'lookup(rule,"destination_port_ranges",[])\\\',\\\'direction\\\':\\\'lookup(rule,"direction",Inbound)\\\',\\\'protocol\\\':\\\'lookup(rule,"protocol",Tcp)\\\',\\\'source_port_range\\\':\\\'lookup(rule,"source_port_range",*)\\\',\\\'description\\\':\\\'\\\',\\\'destination_address_prefix\\\':\\\'*\\\',\\\'destination_address_prefixes\\\':[],\\\'destination_application_security_group_ids\\\':[],\\\'source_application_security_group_ids\\\':[],\\\'source_port_ranges\\\':[]}]}\']'], 'tags': [{'source': 'terraform'}]} at file: /modules/aabb/nsg.tf
2021-05-18 11:41:13,329 [MainThread  ] [ERROR]  Failed to run check: Ensure that UDP Services are restricted from the Internet  for configuration: {'count': [1], 'location': ['WestEurope'], 'name': ['dev-nsg'], 'resource_group_name': ['dev-vm'], 'security_rule': ['lookup(rule,"destination_port_range",*):\\\'lookup(rule,"destination_port_ranges",[])\\\',\\\'direction\\\':\\\'lookup(rule,"direction",Inbound)\\\',\\\'protocol\\\':\\\'lookup(rule,"protocol",Tcp)\\\',\\\'source_port_range\\\':\\\'lookup(rule,"source_port_range",*)\\\',\\\'description\\\':\\\'\\\',\\\'destination_address_prefix\\\':\\\'*\\\',\\\'destination_address_prefixes\\\':[],\\\'destination_application_security_group_ids\\\':[],\\\'source_application_security_group_ids\\\':[],\\\'source_port_ranges\\\':[]}]}\']'], 'tags': [{'source': 'terraform'}]} at file: /modules/aabb/nsg.tf
Traceback (most recent call last):
  File "/home/username/.local/bin/checkov", line 8, in <module>
    exit(run())
  File "/home/username/.local/lib/python3.8/site-packages/checkov/main.py", line 110, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/home/username/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 106, in run
    self.check_tf_definition(report, root_folder, runner_filter, collect_skip_comments)
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 185, in check_tf_definition
    self.run_all_blocks(definition, self.definitions_context, full_file_path, root_folder, report,
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 195, in run_all_blocks
    self.run_block(definition[block_type], definitions_context,
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 264, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
  File "/home/username/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 113, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/username/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 127, in run_check
    result = check.run(
  File "/home/username/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 65, in run
    raise e
  File "/home/username/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 52, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 23, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/home/username/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/azure/NSGRuleUDPAccessRestricted.py", line 19, in scan_resource_conf
    if 'protocol' in rule_conf and rule_conf['protocol'][0].lower() == 'udp' \
TypeError: string indices must be integers_

Scan works when I skip CKV_AZURE_77 control.

**Comment by nimrodkor** [comment]
Hey @serxansherif !

I believe the issue is we don't handle the `lookup` function correctly in this case. There are 2 options:
1. Ensure rule_conf['protocol'] is a list - should be an easy fix. 
2. Resolve the `lookup` function. This seems like an overkill for me in this case.

We're open to a fix PR if you're up to it :)

**Comment by serxansherif** [comment]
hey @nimrodkor 

thanks for the quick responding.
it's up to you :)

**Comment by nimrodkor** [comment]
The lookup function has been [implemented](https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/graph_builder/variable_rendering/safe_eval_functions.py#L165)!
