### ISSUE TITLE
GKE Shielded Node Checks (CKV_GCP_68 and CKV_GCP_72) can crash with dynamic content block

### ISSUE THREAD

**Issue by rbmarkh** [bridgecrewio/checkov#1337]
**Describe the bug**
GKE Shielded Node Checks (CKV_GCP_68, 72) fail if shielded_instance_config present but empty

**To Reproduce**
1. Have an affected resource with an empty shielded_instance_config block:

In our TF, shielded_instance_config is a dynamic block for backward compatibility reasons:
```
dynamic "shielded_instance_config" {
      for_each = var.modern_nodepool ? [true] : []

      content {
        enable_secure_boot = true
      }
    }
```

2. Run checkov against the generated plan
3. You'll get a Python traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 8, in <module>
    exit(run())
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 123, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=args.file,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 39, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 62, in run
    self.check_tf_definition(report, runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 78, in check_tf_definition
    self.run_block(definition[block_type], full_file_path, report, scanned_file,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 94, in run_block
    results = registry.scan(scanned_file, entity, [], runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 113, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 127, in run_check
    result = check.run(
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 65, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 52, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 23, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/gcp/GKESecureBootforShieldedNodes.py", line 19, in scan_resource_conf
    if monitor.get("enable_secure_boot", None) == [True]:
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/context_parsers/tf_plan/node.py", line 202, in __getattr__
    raise TemplateAttributeError('%s.%s is invalid' % (self.__class__.__name__, name))
checkov.terraform.context_parsers.tf_plan.node.TemplateAttributeError: list_node.get is invalid 
```

**Expected behavior**
* Check should pass/fail rather than crash Checkov

**Screenshots**
* N/A

**Desktop (please complete the following information):**
- OSX x64

**Additional context**
I think the cause here is the check in GKESecureBootforShieldedNodes.py (and same for GKEEnsureIntegrityMonitoring.py, at least)
```:
if isinstance(node, dict) and 'shielded_instance_config' in node:
    monitor = node["shielded_instance_config"][0]
    if monitor.get("enable_secure_boot", None) == [True]:
```
node.shielded_instance_config can be [ [] ], causing 'monitor' to be an empty list before the monitor.get call

I think (but not certain) that this might be a change in Terraform itself somewhere - haven't bisected this, but we're on TF 1.0.1 now, and this check used to work fine for us previously. I'm a little surprised it's [] rather than {}!

**Comment by daniel-shuy** [comment]
Created a PR at #1804 to support dynamic blocks for `shielded_instance_config`
