### ISSUE TITLE
Checkov crashes with UnicodeEncodeError under gitbash

### ISSUE THREAD

**Issue by crbunney** [bridgecrewio/checkov#1360]
**Describe the bug**
When I try to run checkov I get an error:
```bash
$ checkov

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.259

Would you like to ▒level up▒ your Checkov powers for free?  The upgrade includes:

Traceback (most recent call last):
  File "C:/venvs/bginvoketasks/Scripts/checkov", line 8, in <module>
    exit(run())
  File "C:\venvs\bginvoketasks\lib\site-packages\checkov\main.py", line 204, in run
    bc_integration.onboarding()
  File "C:\venvs\bginvoketasks\lib\site-packages\checkov\common\bridgecrew\platform_integration.py", line 304, in onboarding
    print(Style.BRIGHT + colored("\nWould you like to ▒level up▒ your Checkov powers for free?  The upgrade includes: \n\n", 'green',
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\venvs\bginvoketasks\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\program files\python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u25e6' in position 240: character maps to <undefined>

```

**To Reproduce**
1. `pip install checkov==2.0.259`
2. `checkov`

**Expected behavior**
Checkov should run without crashing

**Desktop (please complete the following information):**
 - OS: 
   - Edition	Windows 10 Enterprise
Version	20H2
OS build	19042.1052
Experience	Windows Feature Experience Pack 120.2212.2020.0

 - Checkov Version 2.0.259

**Additional context**
I'm running checkov within a gitbash environment, which is using `mintty 3.4.6 (x86_64-pc-msys) [Windows 19042]`

**Comment by JamesWoolfenden** [comment]
@metahertz look like our old friend is back in new ways. i bet those quotes aren't standard.

**Comment by nimrodkor** [comment]
@JamesWoolfenden Did we get this sorted?
