### ISSUE TITLE
TypeError on "Ensure no hard coded AWS access key and secret key exists in provider for configuration"

### ISSUE THREAD

**Issue by fraserc182** [bridgecrewio/checkov#1378]
**Describe the bug**
We run in terraform cloud and use workspace variables to set sensitive variables, this means having placeholders in the variables.tf file like so:

```
variable "access_key" {
  default = {}
}

variable "secret_key" {
  default = {}
}
```
However, this is causing checkov to crash with:
```
TypeError: expected string or bytes-like object
```

Traceback:
```
fraser@laptop:.../c/terraform/isnw$ checkov --directory .
2021-07-13 19:17:26,901 [MainThread  ] [ERROR]  Failed to run check: Ensure no hard coded AWS access key and secret key exists in provider for configuration: {'access_key': [{}], 'region': ['eu-west-1'], 'secret_key': [{}]} at file: /network/main.tf
Traceback (most recent call last):
  File "/home/fraser/.local/bin/checkov", line 8, in <module>
    exit(run())
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/main.py", line 148, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 39, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,

# Variables within this file are specific to the Development environment
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 108, in run
    self.check_tf_definition(report, root_folder, runner_filter, collect_skip_comments)
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 200, in check_tf_definition
    self.run_all_blocks(definition, self.definitions_context, full_file_path, root_folder, report,
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 210, in run_all_blocks
    self.run_block(definition[block_type], definitions_context,
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 279, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 113, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 127, in run_check
    result = check.run(
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 65, in run
    raise e
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 52, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/checks/provider/base_check.py", line 18, in scan_entity_conf
    return self.scan_provider_conf(conf)
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/checks/provider/aws/credentials.py", line 21, in scan_provider_conf
    if self.secret_found(conf, "access_key", access_key_pattern):
  File "/home/fraser/.local/lib/python3.8/site-packages/checkov/terraform/checks/provider/aws/credentials.py", line 31, in secret_found
    if re.match(pattern, value) is not None:
  File "/usr/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

Setting the following placeholders;

```
variable "access_key" {
  default = {"132456"}
}

variable "secret_key" {
  default = {"123456"}
}
```
Let me run checkov without any issues.

**To Reproduce**
1. Set empty access key & secret key in variables.tf
2. Run checkov --directory . in the directory
3. It will error

**Expected behavior**
Be able to account for empty strings, either pass them or give a warning "This variable is empty" or similar

**Desktop (please complete the following information):**
 - OS: windows 10
 - Checkov Version [2.0.267]

**Additional context**
Curiously running
```
checkov --file variables.tf
```
Works without an issue, unsure why this would be the case.

**Comment by gruebel** [comment]
Maybe I'm missing something, but why not use an empty string as default -> `default = ""`

**Comment by JamesWoolfenden** [comment]
You don't ever have to set those vars for a provider as you can just define them as env vars as shown here https://learn.hashicorp.com/tutorials/terraform/cloud-workspace-configure as terraform now uses the aws keychain properly, pretty sure this way you end up putting them in your statefile and your git repo.

**Comment by fraserc182** [comment]
These are both better ideas.
Maybe the reason we're using this is legacy and I've just went with it. I'll test out moving to environment variables and report back.

**Comment by schosterbarak** [comment]
@fraserc182 i'm closing for now. please let us know if this reproduces
