### ISSUE TITLE
Unexpected token Token('RPAR', ')') - Error parsing file

### ISSUE THREAD

**Issue by pete-leese** [bridgecrewio/checkov#1393]
**Describe the bug**
I am validating some terraform and using the following functions to generate a tag value, this works, and terraform validate / apply completes with no issue, however checkov is unable to parse the file. 

```
  tags = merge(
    tomap({ "Name" = "${lower("${var.name}-${each.value["name"]}-${substr("${each.value["availability_zone"]}", -2, -1)}")}" }),
    local.common_tags,
    var.extra_tags
  )

```

**Expected behavior**
It is expected that the chekov is able to parse the code.

By bridgecrew.io | version: 2.0.276 

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file test.tf

**Additional context**

Debug output: 
```
2021-07-16 14:27:17,230 [MainThread  ] [DEBUG]  failed while parsing file test.tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: 'RPAR'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 603, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 9, in load
    return loads(file.read())
  File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 18, in loads
    return hcl2.parse(text + "\n")
  File "/usr/local/lib/python3.9/site-packages/lark/lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", line 115, in parse
    return self._parse(token_stream, start)
  File "/usr/local/lib/python3.9/site-packages/lark/parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    action, arg = get_action(token)
  File "/usr/local/lib/python3.9/site-packages/lark/parsers/lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('RPAR', ')') at line 39, column 122.
Expected one of: 
        * __ANON_7
        * PLUS
        * __ANON_4
        * PERCENT
        * SLASH
        * __ANON_6
        * LESSTHAN
        * __ANON_8
        * __ANON_1
        * __ANON_9
        * STAR
        * COMMA
        * MORETHAN
        * __ANON_5
        * __ANON_2
        * QMARK
        * RBRACE
        * __ANON_0
        * MINUS
```

**Comment by pete-leese** [comment]
Hey @schosterbarak - This has been outstanding for some months, and still facing the exact same issue - are you able to take a look at this please?
