### ISSUE TITLE
Parsing errors if resource name is null

### ISSUE THREAD

**Issue by AlexDexsoon** [bridgecrewio/checkov#1414]
**Describe the bug**
I have errors when I try to use a resource with "null" name

**To Reproduce**
1. Example terraform code: 
```
data "aws_iam_policy_document" "null" {}

output "aws_iam_policy_document" {
  value       = data.aws_iam_policy_document.null
  description = "aws_iam_policy_document with null name"
}
```
2. Run cli command:
```
docker run -it -e LOG_LEVEL=DEBUG --rm -v $(pwd)/main.tf:/data/main.tf:ro bridgecrew/checkov:latest -d /data/
```
3. See an error:
```
2021-07-23 13:59:08,440 [MainThread  ] [DEBUG]  failed while parsing file /data/main.tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: 'NULL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/parser.py", line 628, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/usr/local/lib/python3.7/site-packages/hcl2/api.py", line 9, in load
    return loads(file.read())
  File "/usr/local/lib/python3.7/site-packages/hcl2/api.py", line 18, in loads
    return hcl2.parse(text + "\n")
  File "/usr/local/lib/python3.7/site-packages/lark/lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "/usr/local/lib/python3.7/site-packages/lark/parser_frontends.py", line 115, in parse
    return self._parse(token_stream, start)
  File "/usr/local/lib/python3.7/site-packages/lark/parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "/usr/local/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "/usr/local/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 88, in parse
    action, arg = get_action(token)
  File "/usr/local/lib/python3.7/site-packages/lark/parsers/lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('NULL', 'null') at line 4, column 46.
Expected one of: 
        * DECIMAL
        * __ANON_3

By bridgecrew.io | version: 2.0.295 
terraform scan results:
Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1
Error parsing file /data/main.tf
```
**Expected behavior**
As for me, shouldn't be a problem if the name of resources is null.

**Desktop (please complete the following information):**
 - OS: Docker
 - Checkov Version: 2.0.295

**Comment by nimrodkor** [comment]
Hi @AlexDexsoon !

It's not valid terraform to leave a resource without a name, so I'm not sure why you would expect it to work. It makes perfect sense to me that parsing invalid terraform will lead to a parsing error
