### ISSUE TITLE
checkov fails with junit-xml==1.8

### ISSUE THREAD

**Issue by n2qz** [bridgecrewio/checkov#1495]
**Describe the bug**
checkov fails with junit-xml==1.8

**To Reproduce**
1. pip3 install junit-xml==1.8
2. checkov -d .
3. See error: 

```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/checkov/main.py", line 12, in <module>
    from checkov.arm.runner import Runner as arm_runner
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/checkov/arm/runner.py", line 7, in <module>
    from checkov.common.output.report import Report
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/checkov/common/output/report.py", line 5, in <module>
    from junit_xml import TestCase, TestSuite, to_xml_report_string
ImportError: cannot import name 'to_xml_report_string' from 'junit_xml' (/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/junit_xml/__init__.py)
```

**Expected behavior**
checkov runs fine with junit-xml==1.9 so a reasonable fix would be to pin that version (or greater) in setup.py install_requires.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: RHEL 7
 - Checkov Version [e.g. 22]: 2.0.350

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by n2qz** [comment]
Submitted PR #1497
