### ISSUE TITLE
Python error IndexError: list index out of range

### ISSUE THREAD

**Issue by dogmatic69** [bridgecrewio/checkov#15]
**Describe the bug**
I get this error for any of my terraform modules. Could it be due to tfvars files? Is there some way to specify a var file to use?

```
$ checkov -d /path/to/module
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 24, in <module>
    report = Runner().run(root_folder)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 22, in run
    scanned_file = definition[0].split(root_folder)[1]
IndexError: list index out of range
```

My terraform module is formatted as folows:
```
├── apis.tf
├── dataflow.tf
├── env
│   ├── backend
│   │   ├── development.tfvars
│   │   ├── production.tfvars
│   │   └── staging.tfvars
│   ├── development.tfvars
│   ├── production.tfvars
│   └── staging.tfvars
├── main.tf
├── variables.tf
└── versions.tf
```

**To Reproduce**
1. run `checkov -d /path/to/module`
2. See error

**Expected behavior**
Output 

**Desktop (please complete the following information):**
 - OS: python:alpine docker image
 - Checkov Version [e.g. 22]: 1.0.78

**Comment by schosterbarak** [comment]
Hey @dogmatic69 thank you for reporting this. 
On the example terraform module format you've described, what was the value of "/path/to/module"?
-it should be to the directory of `main.tf`

**Comment by tronxd** [comment]
Hey @dogmatic69, in order to reproduce the error I would like the snapshot of your Terraform code (root directory), possibly with anonymised values if you wish.
Also, please provide your Terraform version you are using.

**Comment by dogmatic69** [comment]
Hi, that is correct. The path I entered is to the location of main.tf. It’s version 0.12

I’ll send an example shortly. Will try narrow it down too 👍🏻

**Comment by schosterbarak** [comment]
Hey @dogmatic69 can you please share an example?

**Comment by schosterbarak** [comment]
@dogmatic69 ?

**Comment by schosterbarak** [comment]
closing due to inactivity.
