### ISSUE TITLE
Terraform Plan Parsing Error when running checkov -f tfplan.json on multi-provider Terraform Configuration

### ISSUE THREAD

**Issue by CCOLLOT** [bridgecrewio/checkov#1522]
Hi, I am currently facing an issue while passing a terraform plan (json format) to the checkov -f command (parsing ERROR) as follows:

terraform plan  -var-file=values.prod.tfvars --out=tfplan.binary
terraform show -json tfplan.binary > tfplan.json 
checkov -f tfplan.json
```
Traceback (most recent call last):
  File "/home/ccollot/.local/bin/checkov", line 8, in <module>
    exit(run())
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/main.py", line 186, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 49, in run
    scan_report = runner.run(
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 62, in run
    tf_definitions, template_lines = parse_tf_plan(file)
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 137, in parse_tf_plan
    resource_block, prepared = _prepare_resource_block(resource, conf)
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 92, in _prepare_resource_block
    resource_block[resource["type"]][resource.get("name", "default")] = _hclify(resource["values"], expressions)
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 54, in _hclify
    child_list.append(_hclify(internal_val, internal_conf_val))
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 63, in _hclify
    for conf_key in conf.keys() - obj.keys():
  File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/context_parsers/tf_plan/node.py", line 39, in __getattr__
    raise TemplateAttributeError('%s.%s is invalid' % (self.__class__.__name__, name))
checkov.terraform.context_parsers.tf_plan.node.TemplateAttributeError: str_node.keys is invalid
```

It cannot provide the material to reproduce the bug, since it would require me to give you my current plan / var file. It looks like a parsing error of the json file by the parser.py file but I cannot figure out the issue.
+ The terraform configuration deploys about 30 resources (nothing too fancy, basically an EKS cluster with a bunch of network-related resources, in TWO different AWS Accounts, therefore leveraging TWO different providers, using the alias feature of terraform provider blocks)
+ The terraform configuration is valid and can be applied without any issue (terraform init / validate /plan /apply are all working)

I have tried with both checkov  2.0.363 (latest) and 2.0.344  running on Ubuntu 20.04

+ checkov -d . works perfectly (when the tfplan.json file is not in the directory)
+ checkov -f tfplan.json works perfectly with my other terraform configurations, it really seems to be something wrong with the tfplan.json file from this specific terraform configuration.

Any suggestions? Thank you very much

**Comment by schosterbarak** [comment]
hey @CCOLLOT would you be able to share plan file sample?

**Comment by acheraime** [comment]
> Hi, I am currently facing an issue while passing a terraform plan (json format) to the checkov -f command (parsing ERROR) as follows:
> 
> terraform plan -var-file=values.prod.tfvars --out=tfplan.binary
> terraform show -json tfplan.binary > tfplan.json
> checkov -f tfplan.json
> 
> ```
> Traceback (most recent call last):
>   File "/home/ccollot/.local/bin/checkov", line 8, in <module>
>     exit(run())
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/main.py", line 186, in run
>     scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 49, in run
>     scan_report = runner.run(
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 62, in run
>     tf_definitions, template_lines = parse_tf_plan(file)
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 137, in parse_tf_plan
>     resource_block, prepared = _prepare_resource_block(resource, conf)
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 92, in _prepare_resource_block
>     resource_block[resource["type"]][resource.get("name", "default")] = _hclify(resource["values"], expressions)
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 54, in _hclify
>     child_list.append(_hclify(internal_val, internal_conf_val))
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/plan_parser.py", line 63, in _hclify
>     for conf_key in conf.keys() - obj.keys():
>   File "/home/ccollot/.local/lib/python3.8/site-packages/checkov/terraform/context_parsers/tf_plan/node.py", line 39, in __getattr__
>     raise TemplateAttributeError('%s.%s is invalid' % (self.__class__.__name__, name))
> checkov.terraform.context_parsers.tf_plan.node.TemplateAttributeError: str_node.keys is invalid
> ```
> 
> It cannot provide the material to reproduce the bug, since it would require me to give you my current plan / var file. It looks like a parsing error of the json file by the parser.py file but I cannot figure out the issue.
> 
> * The terraform configuration deploys about 30 resources (nothing too fancy, basically an EKS cluster with a bunch of network-related resources, in TWO different AWS Accounts, therefore leveraging TWO different providers, using the alias feature of terraform provider blocks)
> * The terraform configuration is valid and can be applied without any issue (terraform init / validate /plan /apply are all working)
> 
> I have tried with both checkov 2.0.363 (latest) and 2.0.344 running on Ubuntu 20.04
> 
> * checkov -d . works perfectly (when the tfplan.json file is not in the directory)
> * checkov -f tfplan.json works perfectly with my other terraform configurations, it really seems to be something wrong with the tfplan.json file from this specific terraform configuration.
> 
> Any suggestions? Thank you very much

Same issue here!  checkov -f tfplan.json returns the below error.

```bash
  2021-09-01 20:47:53,915 [MainThread  ] [ERROR]  Failed to run check: Ensure that instances are not configured to use the default service account with full access to all Cloud APIs for configuration: {'advanced_machine_features': [[]], 'allow_stopping_for_update': [None], 'attached_disk': [[]], 'boot_disk': [{'auto_delete': [True], 'disk_encryption_key_raw': [None], 'initialize_params': [{'image': ['ubuntu-os-cloud/ubuntu-1804-lts'], 'start_line': [0], 'end_line': [0]}], 'mode': ['READ_WRITE'], 'start_line': [0], 'end_line': [0]}], 'can_ip_forward': [False], 'deletion_protection': [False], 'description': [None], 'desired_status': [None], 'enable_display': [None], 'hostname': [None], 'labels': [None], 'machine_type': ['f1-micro'], 'metadata': [{'enable-oslogin': ['true'], 'start_line': [0], 'end_line': [0]}], 'metadata_startup_script': [''], 'name': ['test-host'], 'network_interface': [{'access_config': [{'public_ptr_domain_name': [None], 'start_line': [0], 'end_line': [0]}], 'alias_ip_range': [[]], 'nic_type': [None], 'subnetwork': ['bastion-subnet'], 'start_line': [0], 'end_line': [0]}], 'project': ['powerchord-dx'], 'resource_policies': [None], 'scratch_disk': [[]], 'service_account': [{'scopes': [None], 'start_line': [0], 'end_line': [0]}], 'shielded_instance_config': [[]], 'tags': [['bastion-host']], 'timeouts': [None], 'zone': ['us-central1-a'], 'start_line': [0], 'end_line': [0]} at file: /../main.json
Traceback (most recent call last):
  File "/home/vsts/.local/bin/checkov", line 8, in <module>
    exit(run())
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/main.py", line 194, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 49, in run
    scan_report = runner.run(
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 67, in run
    self.check_tf_definition(report, runner_filter)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 92, in check_tf_definition
    self.run_block(definition[block_type], full_file_path, report, scanned_file,
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 106, in run_block
    results = registry.scan(scanned_file, entity, [], runner_filter)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 121, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 135, in run_check
    result = check.run(
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 67, in run
    raise e
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 54, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 23, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccountFullAccess.py", line 34, in scan_resource_conf
    elif FULL_ACCESS_API in conf['service_account'][0]['scopes'][0]:
TypeError: argument of type 'NoneType' is not iterable
##[error]Bash exited with code '1'.


```

**Comment by bpoole** [comment]
Can you try the code in my PR? I believe it will fix these issues.

https://github.com/bridgecrewio/checkov/pull/1642
