### ISSUE TITLE
Failure scanning plan of aws_autoscaling_group resource with tags argument

### ISSUE THREAD

**Issue by aucheun-tu** [bridgecrewio/checkov#1584]
**Describe the bug**
When scanning the terraform plan output of an aws_autoscaling_group resource that utilizes the tags argument. I receive a "checkov.terraform.context_parsers.tf_plan.node.TemplateAttributeError: str_node.keys" is invalid error. 

**To Reproduce**
Create a main.tf file using the following template.
```
resource "aws_autoscaling_group" "example" {
  max_size             = 1
  min_size             = 1
  health_check_type    = "ELB"
  vpc_zone_identifier  = ["test"]
  launch_configuration = "test"

  tags = [{
    key                 = "test"
    value               = "test"
    propagate_at_launch = true
    },
    {
      key                 = "test2"
      value               = "test2"
      propagate_at_launch = true
  }]
}
```
Run the following commands.
```
terraform init
terraform plan -out test.binary
terraform show -json test.binary > test.json
checkov -f test.json
```
Below is the error that occurs.
```
Traceback (most recent call last):
  File "/venv/bin/checkov", line 8, in <module>
    exit(run())
  File "/venv/lib/python3.9/site-packages/checkov/main.py", line 146, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "/venv/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 39, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/venv/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 57, in run
    tf_definitions, template_lines = parse_tf_plan(file)
  File "/venv/lib/python3.9/site-packages/checkov/terraform/plan_parser.py", line 137, in parse_tf_plan
    resource_block, prepared = _prepare_resource_block(resource, conf)
  File "/venv/lib/python3.9/site-packages/checkov/terraform/plan_parser.py", line 92, in _prepare_resource_block
    resource_block[resource["type"]][resource.get("name", "default")] = _hclify(resource["values"], expressions)
  File "/venv/lib/python3.9/site-packages/checkov/terraform/plan_parser.py", line 54, in _hclify
    child_list.append(_hclify(internal_val, internal_conf_val))
  File "/venv/lib/python3.9/site-packages/checkov/terraform/plan_parser.py", line 63, in _hclify
    for conf_key in conf.keys() - obj.keys():
  File "/venv/lib/python3.9/site-packages/checkov/terraform/context_parsers/tf_plan/node.py", line 39, in __getattr__
    raise TemplateAttributeError('%s.%s is invalid' % (self.__class__.__name__, name))
checkov.terraform.context_parsers.tf_plan.node.TemplateAttributeError: str_node.keys is invalid
```

**Expected behavior**
Checkov produces scan results without errors.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Checkov Version: 2.0.189

**Additional context**
When trying using the tag argument instead of the tags argument there are no errors. Example template with successful scan below.
```
resource "aws_autoscaling_group" "example" {
  max_size             = 1
  min_size             = 1
  health_check_type    = "ELB"
  vpc_zone_identifier  = ["test"]
  launch_configuration = "test"

  tag {
    key                 = "test"
    value               = "test"
    propagate_at_launch = true
  }

  tag {
    key                 = "test2"
    value               = "test2"
    propagate_at_launch = true
  }
}
```

**Comment by kmcquade** [comment]
@schosterbarak we are hitting this issue too :(

**Comment by bpoole** [comment]
Can you try the code in my PR? I believe it will fix these issues.

https://github.com/bridgecrewio/checkov/pull/1642
