### ISSUE TITLE
NoneType Object is not Iterable with Custom Policy and Terraform

### ISSUE THREAD

**Issue by solaris187** [bridgecrewio/checkov#1621]
**Describe the bug**
Created a custom rule in YAML to check for existence of tags on resources. When running checkov against a plan in json format I get the following error:
`
Traceback (most recent call last):
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\Scripts\checkov", line 8, in <module>
    exit(run())
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\main.py", line 195, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\runners\runner_registry.py", line 55, in run
    scan_report = runner.run(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\terraform\runner.py", line 64, in run
    self.load_external_checks(external_checks_dir)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\terraform\runner.py", line 114, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\registry.py", line 55, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\registry.py", line 45, in _load_checks_from_dir
    check = self.parser.parse_raw_check(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\checks_parser.py", line 56, in parse_raw_check
    solver = self.get_check_solver(check)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\checks_parser.py", line 113, in get_check_solver
    SolverType.COMPLEX_CONNECTION: operator_to_complex_connection_solver_classes.get(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\solvers\connections_solvers\and_connection_solver.py", line 15, in __init__
    super().__init__(solvers, operator)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\solvers\connections_solvers\complex_connection_solver.py", line 29, in __init__
    resource_types.update(sub_solver.resource_types)
TypeError: 'NoneType' object is not iterable
`

**To Reproduce**
1. Create custom check that looks like this:
`
metadata:
  name: "Ensure that Invesco required tags are present on all resources"
  #id: "CKV2_AWS_IVZ-01-Tags"
  id: "IVZ_01_Tags"
  category: "CONVENTION"
definition:
  and:
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
      value: "ApplicationCI"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
      value: "CostCenter"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
      value: "Owner"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
      value: "Requestor"
    - cond_type: "attribute"
      resource_types: "all"
      attribute: "tags"
      operator: "exists"
      value: "AppEnv"
`
2. terraform plan --out tfplan.binary
3. terraform show -json tfplan.binary > tfplan.json
4. checkov -f tfplan.json --external-checks-dir ../../../checkov/ivz-custom-rules/

**Expected behavior**
Checkov parses my plan and runs the custom rule to check for existance of tag keys

**Desktop (please complete the following information):**

 - Checkov Version 2.0.418

**Comment by nimrodkor** [comment]
Hey @solaris187 !

When using the `all` resource type, you need to specify the relevant provider in the scope. Try this:
```yaml
metadata:
name: "Ensure that Invesco required tags are present on all resources"
#id: "CKV2_AWS_IVZ-01-Tags"
id: "IVZ_01_Tags"
category: "CONVENTION"
scope:
  provider:
    - AWS
```

**Comment by solaris187** [comment]
> Hey @solaris187 !
> 
> When using the `all` resource type, you need to specify the relevant provider in the scope. Try this:
> 
> ```yaml
> metadata:
> name: "Ensure that Invesco required tags are present on all resources"
> #id: "CKV2_AWS_IVZ-01-Tags"
> id: "IVZ_01_Tags"
> category: "CONVENTION"
> scope:
>   provider:
>     - AWS
> ```

Thanks for the reply. Here is what I have now tried:

`---
metadata:
  name: "Ensure that Invesco required tags are present on all resources"
  id: "AWS_IVZ_01_Tags"
  category: "CONVENTION"
  scope:
    provider:
      - aws
definition:
  and:
    - cond_type: attribute
      resource_types: all
      attribute: tag.ApplicationCI
      operator: exists

    - cond_type: attribute
      resource_types: all
      attribute: tags.CostCenter
      operator: exists

    - cond_type: attribute
      resource_types: all
      attribute: tags.Owner
      operator: exists

    - cond_type: attribute
      resource_types: all
      attribute: tags.Requestor
      operator: exists

    - cond_type: attribute
      resource_types: all
      attribute: tags.AppEnv
      operator: exists
`

Error being returned:

`
Traceback (most recent call last):
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\Scripts\checkov", line 8, in <module>
    exit(run())
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\main.py", line 195, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\runners\runner_registry.py", line 55, in run
    scan_report = runner.run(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\terraform\runner.py", line 64, in run
    self.load_external_checks(external_checks_dir)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\terraform\runner.py", line 114, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\registry.py", line 55, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\registry.py", line 45, in _load_checks_from_dir
    check = self.parser.parse_raw_check(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\checks_parser.py", line 56, in parse_raw_check
    solver = self.get_check_solver(check)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\checks_parser.py", line 113, in get_check_solver
    SolverType.COMPLEX_CONNECTION: operator_to_complex_connection_solver_classes.get(
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\solvers\connections_solvers\and_connection_solver.py", line 15, in __init__
    super().__init__(solvers, operator)
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks_infra\solvers\connections_solvers\complex_connection_solver.py", line 29, in __init__
    resource_types.update(sub_solver.resource_types)
TypeError: 'NoneType' object is not iterable
`

**Comment by nimrodkor** [comment]
We should have a better log message for this case though, to make the error clearer

**Comment by zamoose** [comment]
Huh, interesting. The docs didn't indicate that `scope:` was a valid top-level block, or I misread them entirely.

When I use the approach you outlined, I got:

```shell
Traceback (most recent call last):
  File "/Users/zamoose/.pyenv/versions/3.8.5/bin/checkov", line 8, in <module>
    exit(run())
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/main.py", line 199, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 55, in run
    scan_report = runner.run(
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/terraform/runner.py", line 66, in run
    self.load_external_checks(external_checks_dir)
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/terraform/runner.py", line 123, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/common/checks_infra/registry.py", line 55, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/common/checks_infra/registry.py", line 46, in _load_checks_from_dir
    check_json, resources_types=self._get_resource_types(check_json)
  File "/Users/zamoose/.pyenv/versions/3.8.5/lib/python3.8/site-packages/checkov/common/checks_infra/registry.py", line 59, in _get_resource_types
    provider = check_json.get("scope", {}).get("provider", "").lower()
AttributeError: 'list' object has no attribute 'lower'```

**Comment by nimrodkor** [comment]
I think the issue here is that the "all" resource types works for terraform, for example, but not for cloudformation

**Comment by AjkayAlan** [comment]
We are running into a similar issue for CloudFormation. Here is our example JSON:

```json
{
  "Resources": {
    "ExampleHostedZone": {
      "Type": "AWS::Route53::HostedZone",
      "Properties": {
        "Name": "example.com."
      }
    },
    "MyRecordSet707B295C": {
      "Type": "AWS::Route53::RecordSet",
      "Properties": {
        "Name": "example.com.",
        "Type": "A",
        "HostedZoneId": {
          "Ref": "ExampleHostedZone"
        },
        "ResourceRecords": ["10.0.0.0"],
        "TTL": "1800"
      }
    }
  }
}
```

And here is our graph rule:
```yaml
metadata:
  name: "Route53 Publicly HostedZones should not contain private records"
  id: "CUSTOM_AWS_ROUTE53_DENY_PRIVATE_IP_IN_PUBLIC_HZ"
  category: "GENERAL_SECURITY"
definition:
  and:
    - cond_type: filter
      attribute: resource_type
      value:
        - AWS::Route53::HostedZone
      operator: within
    - cond_type: connection
      resource_types:
        - AWS::Route53::HostedZone
      connected_resource_types:
        - AWS::Route53::RecordSet
      operator: exists
    # Public HZ's can't have VPCs per https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html#cfn-route53-hostedzone-vpcs
    - cond_type: attribute
      resource_type:
        - AWS::Route53::HostedZone
      attribute: VPCs
      operator: not_exists
    # This is commented out because even the above condition blows this up.
    # - cond_type: attribute
    #   resource_type:
    #     - AWS::Route53::RecordSet
    #   attribute: ResourceRecords
    #   operator: not_starting_with
    #   value:
    #     - 10.
```

And our error:
```
Process ForkProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/parallelizer/parallel_runner.py", line 27, in func_wrapper
    result = original_func(item)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 63, in <lambda>
    lambda runner: runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 67, in run
    self.load_external_checks(external_checks_dir)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 116, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/registry.py", line 55, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/registry.py", line 45, in _load_checks_from_dir
    check = self.parser.parse_raw_check(
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/checks_parser.py", line 88, in parse_raw_check
    solver = self.get_check_solver(check)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/checks_parser.py", line 145, in get_check_solver
    SolverType.COMPLEX_CONNECTION: operator_to_complex_connection_solver_classes.get(
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/solvers/connections_solvers/and_connection_solver.py", line 15, in __init__
    super().__init__(solvers, operator)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks_infra/solvers/connections_solvers/complex_connection_solver.py", line 29, in __init__
    resource_types.update(sub_solver.resource_types)
TypeError: 'NoneType' object is not iterable
```

Any idea what's going on here?
