### ISSUE TITLE
Can't run checkov locally - An error occurred setting up the Bridgecrew platform integration.

### ISSUE THREAD

**Issue by kibnelbachyr** [bridgecrewio/checkov#1671]
**Describe the bug**
I got the error below when I run checkov command locally: 
```
2021-09-28 23:26:01,035 [MainThread  ] [ERROR]  Response of https://www.bridgecrew.cloud/api/v1/integrations/types/checkov is not a valid JSON
Expecting value: line 1 column 1 (char 0)
2021-09-28 23:26:01,036 [MainThread  ] [ERROR]  An error occurred setting up the Bridgecrew platform integration. Please check your API token and try again.
Traceback (most recent call last):
  File "/usr/local/Cellar/checkov/2.0.435/libexec/lib/python3.9/site-packages/checkov/main.py", line 130, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=config.repo_id,
  File "/usr/local/Cellar/checkov/2.0.435/libexec/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 160, in setup_bridgecrew_credentials
    raise e
  File "/usr/local/Cellar/checkov/2.0.435/libexec/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 139, in setup_bridgecrew_credentials
    repo_full_path, response = self.get_s3_role(repo_id)
  File "/usr/local/Cellar/checkov/2.0.435/libexec/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 170, in get_s3_role
    response = json.loads(request.data.decode("utf8"))
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**To Reproduce**
1. brew install checkov
2. checkov --directory .
3. See error

**Expected behavior**
Checkov's normal output/report. 

**Screenshots**
<img width="1218" alt="Screenshot 2021-09-28 at 23 38 05" src="https://user-images.githubusercontent.com/31845236/135169378-5ac3357b-d31e-4fab-a659-9e2371c49732.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Checkov Version: 2.0.435

**Comment by nimrodkor** [comment]
Hey @kibnelbachyr , do you have a config file by any chance?

**Comment by nimrodkor** [comment]
Do you mind running checkov with lower log level to help us gather data? i.e.:
```sh
LOG_LEVEL=DEBUG checkov --directory .
```

**Comment by kibnelbachyr** [comment]
@nimrodkor, sure! Here is the output: 

`> LOG_LEVEL=DEBUG checkov --directory .
2021-09-30 15:32:14,843 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2021-09-30 15:32:14,843 [MainThread  ] [DEBUG]  terraform_runner declares no system dependency checks required.
2021-09-30 15:32:14,843 [MainThread  ] [DEBUG]  cloudformation_runner declares no system dependency checks required.
2021-09-30 15:32:14,844 [MainThread  ] [DEBUG]  kubernetes_runner declares no system dependency checks required.
2021-09-30 15:32:14,844 [MainThread  ] [DEBUG]  serverless_runner declares no system dependency checks required.
2021-09-30 15:32:14,844 [MainThread  ] [DEBUG]  arm_runner declares no system dependency checks required.
2021-09-30 15:32:14,844 [MainThread  ] [DEBUG]  terraform_plan_runner declares no system dependency checks required.
2021-09-30 15:32:14,845 [MainThread  ] [INFO ]  Checking necessary system dependancies for helm checks.
2021-09-30 15:32:15,023 [MainThread  ] [INFO ]  Found working version of helm dependancies: v3.5.0
2021-09-30 15:32:15,024 [MainThread  ] [DEBUG]  dockerfile_runner declares no system dependency checks required.
2021-09-30 15:32:15,024 [MainThread  ] [DEBUG]  secrets_runner declares no system dependency checks required.
2021-09-30 15:32:15,024 [MainThread  ] [DEBUG]  Using API key ending with b7400aa7
2021-09-30 15:32:15,024 [MainThread  ] [DEBUG]  BC_SOURCE = cli, version = 2.0.456
2021-09-30 15:32:15,891 [MainThread  ] [ERROR]  Response of https://www.bridgecrew.cloud/api/v1/integrations/types/checkov is not a valid JSON
Expecting value: line 1 column 1 (char 0)
2021-09-30 15:32:15,891 [MainThread  ] [ERROR]  An error occurred setting up the Bridgecrew platform integration. Please check your API token and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 130, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=config.repo_id,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 160, in setup_bridgecrew_credentials
    raise e
  File "/usr/local/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 139, in setup_bridgecrew_credentials
    repo_full_path, response = self.get_s3_role(repo_id)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/bridgecrew/platform_integration.py", line 170, in get_s3_role
    response = json.loads(request.data.decode("utf8"))
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by pandrel** [comment]
@nimrodkor  Same error today .. checkov worked fine till yesterday .. suddenly stopped working today. Any solution for this issue ?

**Comment by pandrel** [comment]
found fix for this error. It appears i have subscribed for levelup checkov and registered with an email id which creates an api key and the key is not valid any more. 

remove ~/.bridgecrew/credentials if you are using free checkov version.

**Comment by KevinHock** [comment]
Can confirm. `rm ~/.bridgecrew/credentials` fixed this for me 👍🏼
