### ISSUE TITLE
Crash:  Ensure Google compute firewall ingress does not allow unrestricted ssh access

### ISSUE THREAD

**Issue by hazcod** [bridgecrewio/checkov#1713]
**Describe the bug**

checkov v13 seems to crash when parsing my ingress YAML.

**Expected behavior**

Working.

**Log**

```log
running checkov on directory: .
10
ERROR:checkov.terraform.checks.resource.gcp.GoogleComputeFirewallUnrestrictedIngress22:Failed to run check: Ensure Google compute firewall ingress does not allow unrestricted ssh access for configuration: {'name': ['main-ingress-firewall'], 'network': ['${google_compute_network.gke_cluster_vpc.name}'], 'description': ['Main firewall that blocks all ingress traffic.'], 'priority': [10], 'direction': ['INGRESS'], 'deny': [{'protocol': ['all']}], 'log_config': [{'metadata': ['INCLUDE_ALL_METADATA']}]} at file: /google/gke/firewall.tf
11
Error: -05 04:37:23,260 [MainThread  ] [ERROR]  Failed to run check: Ensure Google compute firewall ingress does not allow unrestricted ssh access for configuration: {'name': ['main-ingress-firewall'], 'network': ['${google_compute_network.gke_cluster_vpc.name}'], 'description': ['Main firewall that blocks all ingress traffic.'], 'priority': [10], 'direction': ['INGRESS'], 'deny': [{'protocol': ['all']}], 'log_config': [{'metadata': ['INCLUDE_ALL_METADATA']}]} at file: /google/gke/firewall.tf
12
Traceback (most recent call last):
13
  File "/usr/local/bin/checkov", line 5, in <module>
14
    run()
15
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 75, in run
16
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=args.external_checks_dir,
17
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 25, in run
18
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
19
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 50, in run
20
    self.check_tf_definition(report, root_folder, runner_filter)
21
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 90, in check_tf_definition
22
    self.run_block(definition[block_type], definitions_context, full_file_path, report, scanned_file,
23
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/runner.py", line 113, in run_block
24
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
25
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 64, in scan
26
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
27
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 70, in run_check
28
    result = check.run(scanned_file=scanned_file, entity_configuration=entity_configuration,
29
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 44, in run
30
    raise e
31
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 33, in run
32
    check_result['result'] = self.scan_entity_conf(entity_configuration)
33
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 20, in scan_entity_conf
34
    return self.scan_resource_conf(conf)
35
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress22.py", line 22, in scan_resource_conf
36
    allow_blocks = conf['allow']
37
KeyError: 'allow'
```

**Desktop (please complete the following information):**
checkov-action v13

**Additional context**

```hcl
resource "google_compute_firewall" "gke_ingress_firewall" {
  name        = "main-ingress-firewall"
  network     = google_compute_network.gke_cluster_vpc.name
  description = "Main firewall that blocks all ingress traffic."

  priority  = 10
  direction = "INGRESS"

  deny {
    protocol = "all"
  }

  log_config {
    metadata = "INCLUDE_ALL_METADATA"
  }
}

resource "google_compute_firewall" "gke_egress_firewall" {
  name        = "main-egress-firewall"
  network     = google_compute_network.gke_cluster_vpc.name
  description = "Main firewall that allows specific egress traffic."

  priority  = 10
  direction = "EGRESS"

  allow {
    protocol = "all"
  }

  # deny {}

  log_config {
    metadata = "INCLUDE_ALL_METADATA"
  }
}
```

**Comment by schosterbarak** [comment]
@hazcod thanks for reporting.  what version of checkov is being used? (run checkov -v)

**Comment by hazcod** [comment]
Hi @schosterbarak , as I mentioned it's `checkov-action@v13`. So `Downloading checkov-1.0.338-py3-none-any.whl (202 kB)`.

**Comment by schosterbarak** [comment]
this is an old version. 
not sure what checkov-action@v13 is. please use latest release mentioned at: https://github.com/bridgecrewio/checkov-action/releases or master

**Comment by hazcod** [comment]
@schosterbarak v13 is a tag: https://github.com/bridgecrewio/checkov-action/releases/tag/v13

**Comment by schosterbarak** [comment]
good shout @hazcod . removing the tag now
