### ISSUE TITLE
All releases above 2.0.459 stop working on checking terraform plan outputs.

### ISSUE THREAD

**Issue by luedigernet** [bridgecrewio/checkov#1752]
**Describe the bug**
Since 2.0.459 checkov crashes on checking a terraform plan output.

**To Reproduce**
run checkov in docker container with a tag of 2.0.460 or greater (2.0.485 is also affected)

Use the following gist as myPkan.json for the input of the check

https://gist.github.com/luedigernet/7ee1434211c4a7086563de4cddbb3b1b

```bash
docker run -t -v $PWD:/tf bridgecrew/checkov:2.0.460 -f /tf/myPlan.json 
2021-10-13 05:32:40,983 [MainThread  ] [ERROR]  Failed to run check: Ensure that respective logs of Amazon Relational Database Service (Amazon RDS) are enabled for configuration: {'allocated_storage': [1000], 'allow_major_version_upgrade': [False], 'apply_immediately': [False], 'auto_minor_version_upgrade': [True], 'backup_retention_period': [7], 'backup_window': ['22:00-23:59'], 'character_set_name': ['WE8ISO8859P1'], 'copy_tags_to_snapshot': [False], 'customer_owned_ip_enabled': [None], 'delete_automated_backups': [True], 'deletion_protection': [False], 'domain': [None], 'domain_iam_role_name': [None], 'enabled_cloudwatch_logs_exports': [['alert', 'audit']], 'engine': ['oracle-se2'], 'engine_version': ['19'], 'final_snapshot_identifier': [None], 'iam_database_authentication_enabled': [False], 'identifier': ['tf-demo-db-stage-01'], 'instance_class': ['db.t3.xlarge'], 'iops': [0], 'license_model': ['license-included'], 'maintenance_window': ['sun:00:00-sun:06:00'], 'max_allocated_storage': [1500], 'monitoring_interval': [0], 'multi_az': [False], 'name': ['DEMO1'], 'password': ['demo'], 'performance_insights_enabled': [True], 'performance_insights_retention_period': [7], 'port': [1521], 'publicly_accessible': [True], 'replica_mode': [None], 'replicate_source_db': [None], 'restore_to_point_in_time': [[]], 's3_import': [[]], 'security_group_names': [None], 'skip_final_snapshot': [True], 'storage_encrypted': [True], 'tags': [{'Environment': 'dev', 'Name': 'tf-demo-db-stage-01', 'Terraform': 'true', 'start_line': 319, 'end_line': 321}], 'tags_all': [{'Environment': ['dev'], 'Name': ['tf-demo-db-stage-01'], 'Terraform': ['true'], 'start_line': [324], 'end_line': [326]}], 'timeouts': [{'create': ['40m'], 'delete': ['40m'], 'update': ['80m'], 'start_line': [329], 'end_line': [331]}], 'username': ['demo'], 'start_line': [276], 'end_line': [333]} at file: /tf/myPlan.json
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 8, in <module>
    exit(run())
  File "/usr/local/lib/python3.7/site-packages/checkov/main.py", line 201, in run
    repo_root_for_plan_enrichment=config.repo_root_for_plan_enrichment)
  File "/usr/local/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 60, in run
    collect_skip_comments=collect_skip_comments,
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/plan_runner.py", line 67, in run
    self.check_tf_definition(report, runner_filter)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/plan_runner.py", line 93, in check_tf_definition
    block_type, runner_filter)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/plan_runner.py", line 106, in run_block
    results = registry.scan(scanned_file, entity, [], runner_filter)
  File "/usr/local/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 121, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/usr/local/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 140, in run_check
    skip_info=skip_info,
  File "/usr/local/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 69, in run
    raise e
  File "/usr/local/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 56, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 23, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_value_check.py", line 61, in scan_resource_conf
    if dpath.search(conf, inspected_key) != {}:
  File "/usr/local/lib/python3.7/site-packages/dpath/util.py", line 170, in search
    return _search_view(obj, glob, separator, afilter, dirs)
  File "/usr/local/lib/python3.7/site-packages/dpath/util.py", line 151, in _search_view
    val = dpath.path.get(obj, path, afilter=afilter, view=True)
  File "/usr/local/lib/python3.7/site-packages/dpath/path.py", line 322, in get
    tail.append(pair[1]())
TypeError: __init__() missing 3 required positional arguments: 'x', 'start_mark', and 'end_mark'

```

**Expected behavior**
running checkov without crashing and deliver its results

**Screenshots**

**Desktop (please complete the following information):**
 - docker container to eliminate local dependencies
 - Checkov Version 2.0.460 and above (even 2.0.485 is affected)

**Additional context**

**Comment by BenjaDiaz** [comment]
Any updates on this? I'm hitting this exact same issue.

**Comment by gruebel** [comment]
please update to the newest version and it should work 🙂 
```shell
checkov -f tfplan.json

       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.0.585 

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file tfplan.json
terraform_plan scan results:

Passed checks: 34, Failed checks: 13, Skipped checks: 0
```

**Comment by gruebel** [comment]
If there are still problems with scanning Terraform plan files, feel free to open a new issue with the error message and additional info.
