### ISSUE TITLE
Checkov may fail at checks due to use of "if" conditions instead of "get" method

### ISSUE THREAD

**Issue by Arun-kc** [bridgecrewio/checkov#1765]
**Describe the bug**

Checking if the `key` is in a `dictionary` using a `get` method gives more sense than using an `if` condition.

`if` condition just checks if the value is in the target or not.  The target can be a dictionary or list or string or any other data structure. But since in our case, it's a dictionary it's more sensible to use a `get` method for the key check. 

**To Reproduce**

Using `if` condition may cause issues like #1486 depending on the dictionary we are passing on to the said function. 

**Expected behavior**

The key check shouldn't break because of an invalid scenario like in the issue mentioned above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Checkov Version 2.0.344

**Additional context**

Using `get` method like in this commit https://github.com/bridgecrewio/checkov/pull/1763/commits/1ffd9c4049429584f7dba541244f7b621c06d6c5 can solve this issue

We may have to refactor all the python files inside `checkov/checkov/arm/checks/resource/`

**Comment by Arun-kc** [comment]
I can do a PR if you find this a valid issue. Thanks @schosterbarak

**Comment by aholler2** [comment]
This is additionally an issue with checkov/arm/checks/resource/AKSDashboardDisabled.py

```
if "kubeDashboard" in conf["properties"]["addonProfiles"]:
    if "enabled" in conf["properties"]["addonProfiles"]["kubeDashboard"]:
```

```
"addonProfiles": "[union(variables('omsagentAddon'),variables('azurepolicyAddon'),variables('appgwIngressControllerAddonFinal'),variables('kubeDashboardAddon'))]"
```

```
2021-11-30T22:35:19.1203654Z 2021-11-30 22:35:19,116 [ThreadPoolEx] [ERROR]  Failed to run check: Ensure Kubernetes Dashboard is disabled for configuration: {'dependsOn': ["[concat('Microsoft.Network/publicIPAddresses/', variables('publicIPAddressName'))]"], 'apiVersion': '2020-07-01', 'type': 'Microsoft.ContainerService/managedClusters', 'location': '[resourceGroup().location]', 'tags': {'__startline__': 179, '__endline__': 179}, 'name': "[parameters('clusterName')]", 'identity': {'type': 'SystemAssigned', '__startline__': 260, '__endline__': 262}, 'properties': {'kubernetesVersion': '', 'nodeResourceGroup': "[concat(resourceGroup().name, '-infra')]", 'dnsPrefix': "[parameters('clusterName')]", 'enableRBAC': True, 'networkProfile': {'networkPlugin': 'azure', 'networkPolicy': 'azure', 'outboundType': 'loadBalancer', 'loadBalancerSku': 'standard', 'loadBalancerProfile': {'outboundIPs': {'publicIPs': [{'id': "[resourceId('Microsoft.Network/publicIPAddresses',variables('publicIPAddressName'))]", '__startline__': 276, '__endline__': 278}], '__startline__': 274, '__endline__': 280}, '__startline__': 273, '__endline__': 281}, '__startline__': 268, '__endline__': 282}, 'agentPoolProfiles': [{'name': 'pool1', 'tags': "[parameters('agentPoolTags')]", 'type': 'VirtualMachineScaleSets', 'mode': 'System', 'osDiskSizeGB': 0, 'vnetSubnetID': "[if(empty(parameters('vnetSubnetID')), json('null'), parameters('vnetSubnetID'))]", 'count': 2, 'vmSize': 'Standard_B2s', 'osType': 'Linux', 'maxPods': 30, 'enableNodePublicIP': False, 'storageProfile': 'ManagedDisks', '__startline__': 284, '__endline__': 297}], 'aadProfile': {'managed': True, 'enableAzureRBAC': True, '__startline__': 299, '__endline__': 302}, 'apiServerAccessProfile': {'authorizedIPRanges': "[concat(variables('catIPs'),parameters('apiServerauthorizedIPRanges'))]", '__startline__': 303, '__endline__': 305}, 'addonProfiles': "[union(variables('omsagentAddon'),variables('azurepolicyAddon'),variables('appgwIngressControllerAddonFinal'),variables('kubeDashboardAddon'))]", '__startline__': 263, '__endline__': 307}, 'resources': [{'condition': "[not(empty(parameters('diagnosticSettings')))]", 'type': 'providers/diagnosticSettings', 'name': "[concat('/Microsoft.Insights/',variables('diagnosticLogssettingName'),'workspace')]", 'apiVersion': '2017-05-01-preview', 'properties': {'storageAccountId': "[if(contains(parameters('diagnosticSettings'),'storageAccountId'), parameters('diagnosticSettings').storageAccountId, json('null'))]", 'workspaceId': "[if(contains(parameters('diagnosticSettings'),'workspaceId'), parameters('diagnosticSettings').workspaceId, json('null'))]", 'eventHubAuthorizationRuleId': "[if(contains(parameters('diagnosticSettings'),'eventHubAuthorizationRuleId'), parameters('diagnosticSettings').eventHubAuthorizationRuleId, json('null'))]", 'eventHubName': "[if(contains(parameters('diagnosticSettings'),'eventHubName'), parameters('diagnosticSettings').eventHubName, json('null'))]", 'logs': [{'category': 'kube-apiserver', 'enabled': True, 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': True, '__startline__': 323, '__endline__': 326}, '__startline__': 320, '__endline__': 327}, {'category': 'kube-audit', 'enabled': False, 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': True, '__startline__': 331, '__endline__': 334}, '__startline__': 328, '__endline__': 335}, {'category': 'kube-controller-manager', 'enabled': True, 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': True, '__startline__': 339, '__endline__': 342}, '__startline__': 336, '__endline__': 343}, {'category': 'kube-scheduler', 'enabled': True, 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': True, '__startline__': 347, '__endline__': 350}, '__startline__': 344, '__endline__': 351}, {'category': 'cluster-autoscaler', 'enabled': True, 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': False, '__startline__': 355, '__endline__': 358}, '__startline__': 352, '__endline__': 359}], 'metrics': [{'enabled': True, 'category': 'AllMetrics', 'retentionPolicy': {'days': "[if(contains(parameters('diagnosticSettings'),'logRetentionDays'), parameters('diagnosticSettings').logRetentionDays, 90)]", 'enabled': False, '__startline__': 365, '__endline__': 368}, '__startline__': 362, '__endline__': 369}], '__startline__': 314, '__endline__': 371}, 'dependsOn': ["[concat('Microsoft.ContainerService/managedClusters/', parameters('clusterName'))]"], '__startline__': 309, '__endline__': 375, 'parent_name': "[parameters('clusterName')]", 'parent_type': 'Microsoft.ContainerService/managedClusters'}], '__startline__': 253, '__endline__': 377} at file: /aks-basic.json
2021-11-30T22:35:20.0231449Z Traceback (most recent call last):
2021-11-30T22:35:20.0232598Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\checkov.cmd", line 53, in <module>
2021-11-30T22:35:20.0236679Z     run()
2021-11-30T22:35:20.0239916Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\main.py", line 209, in run
2021-11-30T22:35:20.0241064Z     files=file, guidelines=guidelines)
2021-11-30T22:35:20.0241642Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\runners\runner_registry.py", line 69, in run
2021-11-30T22:35:20.0245065Z     for scan_report in reports:
2021-11-30T22:35:20.0246130Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\concurrent\futures\_base.py", line 598, in result_iterator
2021-11-30T22:35:20.0441998Z     yield fs.pop().result()
2021-11-30T22:35:20.0443349Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\concurrent\futures\_base.py", line 428, in result
2021-11-30T22:35:20.0445428Z     return self.__get_result()
2021-11-30T22:35:20.0446407Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\concurrent\futures\_base.py", line 384, in __get_result
2021-11-30T22:35:20.0447461Z     raise self._exception
2021-11-30T22:35:20.0448699Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\concurrent\futures\thread.py", line 57, in run
2021-11-30T22:35:20.0449858Z     result = self.fn(*self.args, **self.kwargs)
2021-11-30T22:35:20.0451124Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\runners\runner_registry.py", line 66, in <lambda>
2021-11-30T22:35:20.0455041Z     runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments),
2021-11-30T22:35:20.0455958Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\arm\runner.py", line 105, in run
2021-11-30T22:35:20.0459305Z     runner_filter)
2021-11-30T22:35:20.0460328Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\checks\base_check_registry.py", line 121, in scan
2021-11-30T22:35:20.0463412Z     result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
2021-11-30T22:35:20.0464867Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\checks\base_check_registry.py", line 140, in run_check
2021-11-30T22:35:20.0465980Z     skip_info=skip_info,
2021-11-30T22:35:20.0467269Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\checks\base_check.py", line 74, in run
2021-11-30T22:35:20.0468514Z     raise e
2021-11-30T22:35:20.0469863Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\common\checks\base_check.py", line 61, in run
2021-11-30T22:35:20.0473085Z     check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
2021-11-30T22:35:20.0474573Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\arm\base_resource_check.py", line 16, in scan_entity_conf
2021-11-30T22:35:20.0476260Z     return self.scan_resource_conf(conf, entity_type)
2021-11-30T22:35:20.0477189Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\arm\base_resource_check.py", line 28, in wrapper
2021-11-30T22:35:20.0480881Z     return wrapped(self, conf)
2021-11-30T22:35:20.0482497Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\checkov\arm\checks\resource\AKSDashboardDisabled.py", line 22, in scan_resource_conf
2021-11-30T22:35:20.0485619Z     if "enabled" in conf["properties"]["addonProfiles"]["kubeDashboard"]:
2021-11-30T22:35:20.0486730Z TypeError: string indices must be integers
2021-11-30T22:35:20.4818316Z 
2021-11-30T22:35:20.4819246Z 
2021-11-30T22:35:20.6551022Z ##[error]PowerShell exited with code '1'.
2021-11-30T22:35:20.7443302Z ##[section]Finishing: Checkov - Azure Kubernetes Service
```
