### ISSUE TITLE
Suppressing/Ignoring a check does not work in kubernetes manifests

### ISSUE THREAD

**Issue by lpzdvd-packlink** [bridgecrewio/checkov#1780]
**Describe the bug**
Suppressing/Ignoring a check does not work in kubernetes manifests

**To Reproduce**
1. I try to set `checkov.io/skip1: CKV_SECRET_6` annotation in a CronJob
2. run `checkov -f cronjob.yaml`
3. Output still state `Check: CKV_SECRET_6: "Base64 High Entropy String"`

It's not very clear in the documentation where we should place annotations according to different workloads

Base case:

```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: foo
  annotations:
    checkov.io/skip1: CKV_SECRET_6
````
Output:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/checkov", line 8, in <module>
    exit(run())
  File "/opt/homebrew/Cellar/checkov/2.0.465/libexec/lib/python3.9/site-packages/checkov/main.py", line 199, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
  File "/opt/homebrew/Cellar/checkov/2.0.465/libexec/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 55, in run
    scan_report = runner.run(
  File "/opt/homebrew/Cellar/checkov/2.0.465/libexec/lib/python3.9/site-packages/checkov/kubernetes/runner.py", line 172, in run
    skipped_checks = get_skipped_checks(entity_conf)
  File "/opt/homebrew/Cellar/checkov/2.0.465/libexec/lib/python3.9/site-packages/checkov/kubernetes/runner.py", line 240, in get_skipped_checks
    logging.debug("Parse of Annotation Failed for {}: {}".format(metadata["annotations"][key], entity_conf, indent=2))
TypeError: list indices must be integers or slices, not str
```

If I place the annotation in any other metadata section (like .spec.jobTemplate.metadata or spec.jobTemplate.spec.template.metadata) warning is still present at the output:

```
Passed checks: 0, Failed checks: 1, Skipped checks: 0

Check: CKV_SECRET_6: "Base64 High Entropy String"
```

**Expected behavior**
Check ignored / Skipped

**Desktop:**
 - OS: macOS Big Sur 11.6 (Apple M1)
 - Checkov Version 2.0.465

**Comment by bmm-alc** [comment]
Sorry to hi-jack this issue but Iḿ getting the same issue even if I set the skip comment.
And I did not find the related documentation about how to skip.

the file (you see I've put skip before and inlined)
``` 
1  | apiVersion: rbac.authorization.k8s.io/v1
2  | kind: ClusterRole
3  | metadata:
4  |   name: infra-admin
5  |   annotations:
6  | rules:
7  | - apiGroups:
8  |   # checkov:skip=CKV_K8S_49
9  |   - '*' # checkov:skip=CKV_K8S_49
10 |   resources:
11 |   # checkov:skip=CKV_K8S_49
12 |   - '*' # checkov:skip=CKV_K8S_49
13 |   verbs:
14 |   - get
15 |   - list
16 |   - watch
17 | - apiGroups:
18 |   - ''
19 |   resources:
20 |   - [&quot;groups&quot;, &quot;serviceaccounts&quot;]
21 |   verbs: [&quot;impersonate&quot;]

```

However I get the message
```
testcase name="[NONE][CKV_K8S_49] Minimize wildcard use in Roles and ClusterRoles" classname="....
			<failure type="failure" message="Minimize wildcard use in Roles and ClusterRoles">
```

is there something I missed ?
If the documentation is missing I'm okay to do a patch if someone can provide me some indications where it should goes.

best

**Comment by gruebel** [comment]
@bmm-alc as you can see in one of the comments, you have to add it as an annotation https://github.com/bridgecrewio/checkov/blob/main/docs/2.Basics/Suppressing%20and%20Skipping%20Policies.md#kubernetes-example
