### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by khorwood** [bridgecrewio/checkov#1896]
**Describe the bug**
With the latest available checkov (2.0.537) and prior versions (2.0.446) I'm seeing an `IndexError: list index out of range` popping up when processing a large serverless definition.

```
$ checkov -d . --framework serverless
Traceback (most recent call last):
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\Scripts\checkov.cmd", line 53, in <module>
    run()
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\site-packages\checkov\main.py", line 182, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\site-packages\checkov\common\runners\runner_registry.py", line 62, in run
    for scan_report in reports:
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\site-packages\checkov\common\runners\runner_registry.py", line 58, in <lambda>
    lambda runner: runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\site-packages\checkov\serverless\runner.py", line 110, in run
    entity_lines_range, entity_code_lines = cf_context_parser.extract_cf_resource_code_lines(
  File "C:\Users\khorwood\AppData\Local\Programs\Python\Python39\lib\site-packages\checkov\cloudformation\context_parser.py", line 76, in extract_cf_resource_code_lines
    entity_lines_range = [entity_code_lines[0][0], entity_code_lines[-1][0]]
IndexError: list index out of range
```

**To Reproduce**
1. Run `checkov -d . --framework serverless` from the repository folder

**Expected behavior**
No errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Checkov Version: 2.0.446, 2.0.537

**Additional context**
N/A

**Comment by khorwood** [comment]
Apologies for the delay, this issue appears to have been fixed in `2.0.564`
