### ISSUE TITLE
Checkov output to json leads to TypeError

### ISSUE THREAD

**Issue by manuel-sommer** [bridgecrewio/checkov#1948]
**Describe the bug**
I run the latest checkov version 2.0.579 and I use the json output:
`checkov --framework terraform -d folder/ --output json`
The python versions, I tried: 
- 3.10.0
- 3.9
- 3.8.10

Whenver I use `--output json`, the output fails to the following error:
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 224, in run
    exit_codes.append(runner_registry.print_reports(scan_reports, config, url=url,
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 148, in print_reports
    print(json.dumps(report_jsons[0], indent=4))
  File "/usr/local/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python3.10/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable

**To Reproduce**
1. Run the latest checkov version with `--output json` 
2. See error

**Expected behavior**
There should be an output likewise to the other output formats (e.g. sarif github_failed_only or sarif)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Checkov Version 2.0.579

**Comment by tonnyhideyori** [comment]
I am facing the same problem with the new version

**Comment by madrum** [comment]
Not sure this is directly related, but I have an issue getting properly formatted JSON output. 
When running a command like this, where I'm checking helm charts and terraform: 
`checkov -d ./charts -d ./terraform -o json --quiet --framework terraform --framework kubernetes`
The JSON is not well formed and looks like two JSON object strings were concatenated. 

`{
    "check_type": "kubernetes",
    "results": {
        "failed_checks": []
    },
    "summary": {
        "passed": 1792,
        "failed": 0,
        "skipped": 341,
        "parsing_errors": 0,
        "resource_count": 218,
        "checkov_version": "2.0.559"
    }
}
{
    "check_type": "kubernetes",
    "results": {
        "failed_checks": []
    },
    "summary": {
        "passed": 1792,
        "failed": 0,
        "skipped": 341,
        "parsing_errors": 0,
        "resource_count": 218,
        "checkov_version": "2.0.559"
    }
}`

**Comment by manuel-sommer** [comment]
Here I pushed an example to replay the failure:
https://github.com/manuel-sommer/terragoat/commit/545260c1f9e96ea5c6c74508b147c57685eb7c0d 

https://github.com/manuel-sommer/terragoat/tree/checkov_fails_here

**Comment by nimrodkor** [comment]
I believe the issue is we need to encode the `set` python object using a custom json decoder. The change needs to be [here](https://github.com/bridgecrewio/checkov/blob/112326a84c21f8c22598a94309c6579edcf43a78/checkov/common/runners/runner_registry.py#L148) and [here](https://github.com/bridgecrewio/checkov/blob/112326a84c21f8c22598a94309c6579edcf43a78/checkov/common/runners/runner_registry.py#L150)

We've created a custom JSON encoder already [here](https://github.com/bridgecrewio/checkov/blob/599051e3893f3374691d92cb5d660fd9b1431c0d/checkov/terraform/parser.py#L32) and used it in the parser - it seems we need something similar in this case.

We'd appreciate a contribution here!
