### ISSUE TITLE
Policy Document Check Bugs

### ISSUE THREAD

**Issue by jdhornsby** [bridgecrewio/checkov#212]
**Describe the bug**
StarActionPolicyDocument  has issues with SCPs that use not_action.

Stack trace:
```
 Traceback (most recent call last):
   File "/usr/local/bin/checkov", line 5, in <module>
     run()
   File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 47, in run
     scan_reports = runner_registry.run(root_folder, external_checks_dir=args.external_checks_dir, files=file)
   File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 20, in run
     scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files)
   File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 38, in run
     self.check_tf_definition(report, root_folder, tf_definitions)
   File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 66, in check_tf_definition
     self.run_block(definition[1][block_type], definitions_context, full_file_path, report, scanned_file,
   File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 88, in run_block
     results = registry.scan(scanned_file, entity,
   File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 48, in scan
     result = check.run(scanned_file=scanned_file, entity_configuration=entity_configuration,
   File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 44, in run
     raise e
   File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 33, in run
     check_result['result'] = self.scan_entity_conf(entity_configuration)
   File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/data/base_check.py", line 19, in scan_entity_conf
     return self.scan_data_conf(conf)
   File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/data/aws/StarActionPolicyDocument.py", line 23, in scan_data_conf
     if '*' in statement['actions'][0] and statement['effect'][0] == "Allow":
 KeyError: 'actions'
```

**To Reproduce**
Attempt to scan a SCP policy document with a statement like:
```
  statement {
    sid    = "NoIAMUsers"
    effect = "Deny"
    not_actions = [
      "iam:Get*",
      "iam:List*",
      "iam:Describe*",
    ]
    resources = [
      "arn:aws:iam::*:user/*",
    ]
  }
```

**Expected behavior**
The checks should probably ignore statements that use not_actions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Docker (GitLab CI)
 - Checkov Version: 1.0.230 

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by nimrodkor** [comment]
Investigating

**Comment by jdhornsby** [comment]
Thank you. No rush. I've added a skip comment to work around for now.

**Comment by nimrodkor** [comment]
Thanks for reporting @jdhornsby !
