### ISSUE TITLE
Terraform DynamoDB Recovery check fails - Error checking bool

### ISSUE THREAD

**Issue by sandstheman** [bridgecrewio/checkov#222]
**Describe the bug**
The dynamodb point in time recovery check fails when the paramater 'enabled' is set to true or false in terraform

**To Reproduce**
1. configure point in time recovery to be enabled in your terraform for a dynamodb table resource
```
...
point_in_time_recovery = {
    enabled = true
  }
...
```
2. run checkov against the code
3. Error generated:
```
ERROR:checkov.terraform.checks.resource.aws.DynamodbRecovery:Failed to run check Ensure Dynamodb point in time recovery (backup) is enabled for configuration {'name': ['${var.common_tags["project"]}-${var.environment_tags["environment"]}-jobs'], 'billing_mode': ['${var.jobs_billing_mode}'], 'read_capacity': ['${var.jobs_read_capacity}'], 'write_capacity': ['${var.jobs_write_capacity}'], 'hash_key': ['job_id'], 'attribute': [{'name': ['job_id'], 'type': ['S']}], 'point_in_time_recovery': [{Token(IDENTIFIER, 'enabled'): True}], 'tags': ['${merge(var.common_tags,,var.environment_tags,,{\'Name\': \'${var.common_tags["project"]}-${var.environment_tags["environment"]}-jobs\', \'description\': \'Jobs DynamoDB Table\'},)}']} 
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.6/dist-packages/checkov/main.py", line 43, in run
    report = Runner().run(root_folder, external_checks_dir=args.external_checks_dir, files=file)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/runner.py", line 32, in run
    self.check_tf_definition(report, root_folder, tf_definitions)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/runner.py", line 60, in check_tf_definition
    block_type)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/runner.py", line 76, in run_block
    results = registry.scan(entity, scanned_file, skipped_checks)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/checks/utilities/base_registry.py", line 39, in scan
    entity_name=entity_name, entity_type=entity, skip_info=skip_info)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/checks/utilities/base_check.py", line 44, in run
    raise e
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/checks/utilities/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/checks/resource/base_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/lib/python3.6/dist-packages/checkov/terraform/checks/resource/aws/DynamodbRecovery.py", line 21, in scan_resource_conf
    if conf["point_in_time_recovery"][0]['enabled'][0]:
TypeError: 'bool' object is not subscriptable
```

**Expected behavior**
Checkov detects that 'enabled' is set to true or false and passes if the value is true, and fails if the value is false

**Desktop (please complete the following information):**
 - Ubunut
 - Checkov Version : latest

**Comment by sandstheman** [comment]
My bad - the = before the { is what was breaking it even though having/not having it seems to be valid terraform

CLOSING
