### ISSUE TITLE
Checkov crash when processing AWS::Serverless:Function with Condition used in Globals

### ISSUE THREAD

**Issue by twierzchowski** [bridgecrewio/checkov#2228]
**Describe the issue**
Checkov crash when processing AWS::Serverless:Function with Condition used in Globals.
However, when Environment section is moved to Lambda it works as expected.

**Examples**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  EnvironmentType:
    Type: String
    AllowedValues:
      - dev
      - stage

Conditions:
  IsStageEnvironment: !Equals [ !Ref EnvironmentType, stage ]

Resources:   
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  ActionLogBucket:
    Type: AWS::S3::Bucket

  ApplicationProcessingLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print('hello from lambda')

Globals:
  Function:
    Environment:
      Variables:
        LogBucketName: !If [ IsStageEnvironment, !Ref ActionLogBucket, unkown ]
```

**Exception Trace**
```sh
λ LOGLEVEL=DEBUG checkov -f application.yaml
Traceback (most recent call last):
  File "C:/Users/TomaszWierzchowski/AppData/Local/Programs/Python/Python37-32/Scripts/checkov", line 9, in <module>
    sys.exit(run())
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\main.py", line 243, in run
    repo_root_for_plan_enrichment=config.repo_root_for_plan_enrichment)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\common\runners\runner_registry.py", line 67, in run
    for scan_report in reports:
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\concurrent\futures\_base.py", line 586, in result_iterator

    yield fs.pop().result()
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\common\runners\runner_registry.py", line 64, in <lambda>
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments),
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\runner.py", line 69, in run
    local_graph = self.graph_manager.build_graph_from_definitions(self.definitions)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_manager.py", line 49, in build_graph_from_definitions
    local_graph.build_graph(render_variables=render_variables)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_builder\local_graph.py", line 47, in build_graph
    renderer.render_variables_from_local_graph()
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\common\graph\graph_builder\variable_rendering\renderer.py", line 26, in render_variables_from_local_graph
    self._render_variables_from_edges()
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\common\graph\graph_builder\variable_rendering\renderer.py", line 64, in _render_variables_from_edges
    self._edge_evaluation_task([edge_group])
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\common\graph\graph_builder\variable_rendering\renderer.py", line 96, in _edge_evaluation_task
    self.evaluate_vertex_attribute_from_edge(inner_edges)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_builder\variable_rendering\renderer.py", line 55, in evaluate_vertex_attribute_from_edge
    self._handle_edge_list_evaluation_functions(edge_list, origin_vertex, val_to_eval)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_builder\variable_rendering\renderer.py", line 416, in _handle_edge_list_evaluation_functions
    edge, origin_vertex, cfn_evaluation_function, val_to_eval, dest_vertex_attributes)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_builder\variable_rendering\renderer.py", line 449, in _evaluate_cfn_function
    val_to_eval[ConditionFunctions.IF], dest_vertex_attributes)
  File "C:\users\tomaszwierzchowski\appdata\local\programs\python\python37-32\lib\site-packages\checkov\cloudformation\graph_builder\variable_rendering\renderer.py", line 330, in _evaluate_if_connection
    condition_name = value[0]
KeyError: 0
```

**Desktop (please complete the following information):**
 - OS: Checked on both Windows and Linux
 - Checkov Version 2.0.727

**Comment by schosterbarak** [comment]
@twierzchowski it seems that we don't mark a file as a "serverless framework related" if it does not have a "provider" block in the yaml. Is "provider" block not mandatory to provision on AWS?

**Comment by twierzchowski** [comment]
Not sure if I correct understand, but it's not [Serverless Framework](https://www.serverless.com/).  
I'm able to deploy that stack using `aws cloudformation deploy` command.

**Comment by nimrodkor** [comment]
This is actually a SAM template issue. @gruebel mind taking a look?

**Comment by gruebel** [comment]
sorry, I'm not sure, why I added the `serverless` label, changed it to `cloudformation`, will have a look 🧐

**Comment by twierzchowski** [comment]
ok, thanks for quick response. If you need any additional information let me know.

**Comment by twierzchowski** [comment]
I confirm that it's fixed. Thanks @gruebel
