### ISSUE TITLE
Fatal error in variable_context_parser in v >1.0.235

### ISSUE THREAD

**Issue by ohthehugemanatee** [bridgecrewio/checkov#223]
**Describe the bug**
Starting in release-1.0.236, some of my (formerly passing) terraform directories produce a fatal error. The error is produced when a variable uses the "default" key.
```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 47, in run
    scan_reports = runner_registry.run(root_folder, external_checks_dir=args.external_checks_dir, files=file)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 20, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 39, in run
    self.check_tf_definition(report, root_folder, tf_definitions)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 57, in check_tf_definition
    definitions_context = parser_registry.enrich_definitions_context(definition)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/registry.py", line 24, in enrich_definitions_context
    self.definitions_context[tf_file][definition_type] = context_parser.run(tf_file, definition_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/base_parser.py", line 108, in run
    self.context = self.enrich_definition_block(definition_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/parsers/variable_context_parser.py", line 27, in enrich_definition_block
    self._collect_default_variables_values(variable_block)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/context_parsers/parsers/variable_context_parser.py", line 19, in _collect_default_variables_values
    dpath.new(self.context, ['assignments', variable_name], value)
  File "/usr/local/lib/python3.8/site-packages/dpath/util.py", line 59, in new
    return dpath.path.set(obj, pathobj, value, creator=creator)
  File "/usr/local/lib/python3.8/site-packages/dpath/path.py", line 279, in set
    local_creator(obj, elem, next_elem)
  File "/usr/local/lib/python3.8/site-packages/dpath/path.py", line 221, in _create_missing_dict
    obj[elem[0]] = elem[1]()
TypeError: __new__() missing 2 required positional arguments: 'type_' and 'value'
Testing directory: /home/ohthehugemanatee/Projects/microsoft/vw-adp-simulation/src/tf/adp-simulation-environment/test/fixture
```

**To Reproduce**
1) Create a terraform module in `test-dir` with `variables.tf`:
```
variable break_my_test {
  type        = string
  description = "Descriptive text here."
  default     = "somevalue"
}
```
2) run `docker run -t -v test-dir:/tf bridgecrew/checkov:release-1.0.236 -d /tf`
3) see error.

**Expected behavior**
Test should not fatal.

**Desktop (please complete the following information):**
 - OS: tested on Linux Manjaro and Ubuntu 18.04 (running in docker)
 - Checkov Version 1.0.236 or higher

**Comment by tronxd** [comment]
Hey @ohthehugemanatee, thank you for the report!
Can you please run checkov with Python version 3.7 installed? I recreated the bug only when I used python3.8 on my environment.

**Comment by tronxd** [comment]
Hey @ohthehugemanatee, can you please upgrade to the latest checkov version and see if your issue is solved?

**Comment by schosterbarak** [comment]
fixed.
