### ISSUE TITLE
checkov crashed when checking for missing `kms_key_id`

### ISSUE THREAD

**Issue by frek818** [bridgecrewio/checkov#2238]
**Describe the issue**
I produced a terraform plan file and ran checkov against it. I expected the checkov command to complete without a traceback. However, this traceback was produced:

**Examples**
```hcl
resource "aws_secretsmanager_secret" "site" {
  name = "the-site-secret"
}
```

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
2022-01-20 04:15:51,404 [MainThread  ] [ERROR]  Failed to run check: Ensure that Secrets Manager secret is encrypted using KMS CMK for configuration: {'description': [None], 'force_overwrite_replica_secret': [False], 'kms_key_id': [None], 'name': ['ebean-example-kitchen-hagerty-com-secret'], 'recovery_window_in_days': [30], 'tags': [{'Name': 'ebean-example-kitchen-hagerty-com-secret', 'start_line': 753, 'end_line': 753}], 'tags_all': [{'Name': ['ebean-example-kitchen-hagerty-com-secret'], 'start_line': [756], 'end_line': [757]}], 'start_line': [747], 'end_line': [757], '__address__': 'module.elastic_beanstalk.aws_secretsmanager_secret.site'} at file: /../../../_temp/tfplan_KITCHEN.json
Process ForkProcess-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/parallelizer/parallel_runner.py", line 29, in func_wrapper
    result = original_func(item)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 63, in <lambda>
    lambda runner: runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 67, in run
    self.check_tf_definition(report, runner_filter)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 93, in check_tf_definition
    self.run_block(definition[block_type], full_file_path, report, scanned_file,
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/plan_runner.py", line 109, in run_block
    results = registry.scan(scanned_file, entity, [], runner_filter)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 121, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 135, in run_check
    result = check.run(
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 81, in run
    raise e
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 68, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 38, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/home/vsts/.local/lib/python3.8/site-packages/checkov/terraform/checks/resource/aws/SecretManagerSecretEncrypted.py", line 23, in scan_resource_conf
    return CheckResult.FAILED if aws_kms_alias in kms_key_id[0] else CheckResult.PASSED
TypeError: argument of type 'NoneType' is not iterable
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Checkov Version checkov-2.0.734-py3-none-any.whl
 - terraform version: 1.1.3

**Additional context**
I found that the cause of the error was due to the `kms_key_id` attribute not being specified in the `aws_secretsmanager_secret`

**Comment by rotemavni** [comment]
Hey @frek818 , thanks for reporting this issue.
The issue was resolved in this PR - https://github.com/bridgecrewio/checkov/pull/2239
