### ISSUE TITLE
cannot import name 'SINGLE_BORDER' from 'prettytable' in checkov-2.0.752

### ISSUE THREAD

**Issue by PascalBourdier** [bridgecrewio/checkov#2268]
**Describe the issue**
```
...
    Uninstalling checkov-2.0.751:
      Successfully uninstalled checkov-2.0.751
Successfully installed checkov-2.0.752

$ checkov
Traceback (most recent call last):
  File "xxx/.local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "xxx/.local/lib/python3.10/site-packages/checkov/main.py", line 49, in <module>
    from checkov.sca_package.runner import Runner as sca_package_runner
  File "xxx/.local/lib/python3.10/site-packages/checkov/sca_package/runner.py", line 12, in <module>
    from checkov.sca_package.output import create_report_record
  File "xxx/.local/lib/python3.10/site-packages/checkov/sca_package/output.py", line 8, in <module>
    from prettytable import PrettyTable, SINGLE_BORDER
ImportError: cannot import name 'SINGLE_BORDER' from 'prettytable' (/usr/lib/python3.10/site-packages/prettytable.py
```

**Additional context**
OS: Fedora release 35

```
$ rpm -qf /usr/lib/python3.10/site-packages/prettytable.py
python3-prettytable-0.7.2-27.fc35.noarch
```

**Workaround**
```
$ pip install --user prettytable --upgrade
```

**Comment by PascalBourdier** [comment]
cf: https://github.com/bridgecrewio/checkov/pull/2226

**Comment by gruebel** [comment]
@PascalBourdier thanks for raising the issue, it looks like you had an old `prettytable` version in your virtualenv, because version `0.7.2` is from 2013 and probably belonged to one of the other packages in your Python env.

**Comment by PascalBourdier** [comment]
this file is provided by Fedora (RPM) not a virtualenv !

**Comment by PascalBourdier** [comment]
a minimum version of this component should be in a requirement file or equivalent
