### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by aschuhl** [bridgecrewio/checkov#2325]
**Describe the issue**
Using pre-commit, and every time I try to commit, checkov fails with `ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)`

**Exception Trace**
```
Checkov..................................................................Failed
- hook id: checkov
- exit code: 1

Traceback (most recent call last):
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/main.py", line 16, in <module>
    from checkov.common.util.docs_generator import print_checks
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/common/util/docs_generator.py", line 11, in <module>
    from checkov.serverless.registry import sls_registry
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/__init__.py", line 1, in <module>
    from checkov.serverless.checks.function import *
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/checks/__init__.py", line 3, in <module>
    from checkov.serverless.checks.function import *
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/checks/function/__init__.py", line 1, in <module>
    from checkov.serverless.checks.function.aws import *
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/checks/function/aws/StarActionPolicyDocument.py", line 1, in <module>
    from checkov.serverless.checks.function.base_function_check import BaseFunctionCheck
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/checks/function/base_function_check.py", line 5, in <module>
    from checkov.serverless.checks.function.registry import function_registry
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/checks/function/registry.py", line 1, in <module>
    from checkov.serverless.base_registry import ServerlessRegistry
  File "/Users/redacted/.cache/pre-commit/repomv0wvy6b/py_env-python3/lib/python3.10/site-packages/checkov/serverless/base_registry.py", line 1, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/collections/__init__.py)
```

**Desktop (please complete the following information):**
 - OS: Macos 11.6.2
 - Checkov Version 1.0.692 and tried a newer version (1.0.832) but same issue.

**Comment by gruebel** [comment]
hi @aschuhl thanks for creating the issue.

We don't support the old version `1.0.x` anymore. Depending on the size of your repo, which you want to scan this can take quite long, but usually it is done in a few seconds. You can try to install `checkov` in a virtual env or use `pipx` and scan your repo with `LOG_LEVEL=INFO checkov -d path/to/repo` then you can see what exactly is happening, and what could be wrong.

**Comment by aschuhl** [comment]
@gruebel Thank you. Btw I did try the latest and that is working, but it takes a significant amount of time compared to before (it's in minutes). Is that expected or can I troubleshoot in some way?

**Comment by gruebel** [comment]
I would recommend you to install the `checkov` CLI and then run the command like I suggested
```shell
LOG_LEVEL=INFO checkov -d path/to/repo
```
this will give you a lot of extra info and also timestamps for the different steps. When are ok, then you can share it with us and I can take a look, where a possible issue could be.

**Comment by gruebel** [comment]
hey @aschuhl if you still have problems, feel free to answer here.
