### ISSUE TITLE
LESSTHAN ("<") symbol in Terraform script causes parse error 

### ISSUE THREAD

**Issue by PlasticGhoul** [bridgecrewio/checkov#2339]
**Description**
We are using Terraform to create virtual machines in Azure. However in order to fulfill Azure Defenders security recommendations, you need to install VM extensions.
Some extensions are using the LESSTHAN ("<") symbol, e. g.:
```
resource "azurerm_virtual_machine_extension" "vm_extension_remoting" {
  name                 = "ansible_ps_remoting"
  virtual_machine_id   = azurerm_windows_virtual_machine.vm.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.10"
  settings             = <<_SETTINGS
    {
      "fileUris": ["https://raw.githubusercontent.com/ansible/ansible/v2.12.1/examples/scripts/ConfigureRemotingForAnsible.ps1"],
      "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"
    }
  _SETTINGS
}
```
In this example we want to execute a script provided by Ansible to configure the VM to be configured by Ansible.

**Error**
Command: `checkov -d C:\DEVELOP\git\autotests-azure\terraform\ --framework terraform`
I get the following stacktrace with LOG_LEVEL=DEBUG (Just the relevant part, because this is a project with sensitive information):
```
2022-02-04 16:19:38,959 [MainThread  ] [DEBUG]  failed while parsing file C:\DEVELOP\git\autotests-azure\terraform\main.tf
Traceback (most recent call last):
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parsers\lalr_parser.py", line 59, in get_action
    return states[state][token.type]
KeyError: 'LESSTHAN'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\DEVELOP\Programme\python310\lib\site-packages\checkov\terraform\parser.py", line 712, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\hcl2\api.py", line 10, in load
    return loads(file.read())
  File "C:\DEVELOP\Programme\python310\lib\site-packages\hcl2\api.py", line 68, in loads
    return hcl2.parse(text + "\n")
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\lark.py", line 464, in parse
    return self.parser.parse(text, start=start)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parser_frontends.py", line 115, in parse
    return self._parse(token_stream, start)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parser_frontends.py", line 63, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parsers\lalr_parser.py", line 35, in parse
    return self.parser.parse(*args)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parsers\lalr_parser.py", line 88, in parse
    action, arg = get_action(token)
  File "C:\DEVELOP\Programme\python310\lib\site-packages\lark\parsers\lalr_parser.py", line 66, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token('LESSTHAN', '<') at line 96, column 26.
Expected one of:
        * __ANON_10
        * __ANON_11
        * STRING_LIT
        * LPAR
        * FALSE
        * LSQB
        * TRUE
        * LBRACE
        * MINUS
        * DECIMAL
        * NULL
        * BANG
        * __ANON_3
```

**Desktop**
 - OS: Windows 10 21H2 x86_64
 - Checkov: 2.0.789
 - Python: 3.10.2
 - PIP: 22.0.3
Checkov installed via `pip install checkov`

**Comment by gruebel** [comment]
hi @PlasticGhoul thanks for creating this issue.

The parser has a problem with the name of heredoc identifier, if you remove the underscore `_`, then it should work.

```hcl
resource "azurerm_virtual_machine_extension" "vm_extension_remoting" {
  name                 = "ansible_ps_remoting"
  virtual_machine_id   = azurerm_windows_virtual_machine.vm.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.10"
  settings             = <<SETTINGS
    {
      "fileUris": ["https://raw.githubusercontent.com/ansible/ansible/v2.12.1/examples/scripts/ConfigureRemotingForAnsible.ps1"],
      "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"
    }
  SETTINGS
}
```

**Comment by PlasticGhoul** [comment]
That works! Thanks for the quick response.
I didn't expect the underscore to be the problem as the parser said it doesn't want the LESSTHAN symbol...
