### ISSUE TITLE
Latest docker image missing boto3 dependency

### ISSUE THREAD

**Issue by jdhornsby** [bridgecrewio/checkov#244]
**Describe the bug**
Docker image release-1.0.257 appears to be missing the boto3 dependency.

**To Reproduce**
Run the docker version of Checkov.

``` $ for DIR in $(find modules -type d -print); do echo "Running Checkov in $DIR"; checkov -d $DIR; done
 Running Checkov in modules
 Traceback (most recent call last):
   File "/usr/local/bin/checkov", line 2, in <module>
     from checkov.main import run
   File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 13, in <module>
     from checkov.common.bridgecrew.platform_integration import BcPlatformIntegration
   File "/usr/local/lib/python3.8/site-packages/checkov/common/bridgecrew/platform_integration.py", line 2, in <module>
     import boto3
 ModuleNotFoundError: No module named 'boto3'
```

**Expected behavior**
Checkov is able to scan.

**Desktop (please complete the following information):**
 - OS: Linux (Docker)
 - Checkov Version 1.0.257

**Comment by tronxd** [comment]
Hey @jdhornsby, please pull the latest checkov docker image and try to re-run at your configuration =

**Comment by jdhornsby** [comment]
Looks good now. Thank you!
