### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by stefaneacsu** [bridgecrewio/checkov#2455]
**Describe the issue**
Updated to the latest version and I am getting the following error after merging a PR to main (GitHub Actions)

**Examples**
```sh
input_soft_fail:
running checkov on directory: .
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 8, in <module>
    exit(run())
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line [11](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5213430541?check_suite_focus=true#step:5:11)2, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/runner.py", line 80, in run
    self.graph_manager.build_graph_from_source_directory(root_folder,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_manager.py", line 18, in build_graph_from_source_directory
    parser.parse_hcl_module(source_dir, self.source, download_external_modules, parsing_errors, excluded_paths=excluded_paths)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line 426, in parse_hcl_module
    self.parse_directory(directory=source_dir, out_definitions=tf_definitions, out_evaluations_context={},
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line 84, in parse_directory
    self._parse_directory(dir_filter=lambda d: self._check_process_dir(d))
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line [12](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5213430541?check_suite_focus=true#step:5:12)5, in _parse_directory
    self._internal_dir_load(sub_dir, module_loader_registry, dir_filter,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line [21](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5213430541?check_suite_focus=true#step:5:21)1, in _internal_dir_load
    self.external_variables_data.append((var_name, default_value[0], file.path))
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - Checkov Version: latest

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by gruebel** [comment]
hi @stefaneacsu thanks for raising this issue, we already released a new version `2.0.854`, which should fix it

**Comment by stefaneacsu** [comment]
@gruebel Updated to version 2.0.854 same issue so I do not think this is fixed.

```sh
input_soft_fail:
running checkov on directory: .
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 8, in <module>
    exit(run())
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line [11](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5214165685?check_suite_focus=true#step:5:11)2, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/runner.py", line 80, in run
    self.graph_manager.build_graph_from_source_directory(root_folder,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_manager.py", line [18](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5214165685?check_suite_focus=true#step:5:18), in build_graph_from_source_directory
    parser.parse_hcl_module(source_dir, self.source, download_external_modules, parsing_errors, excluded_paths=excluded_paths)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line 426, in parse_hcl_module
    self.parse_directory(directory=source_dir, out_definitions=tf_definitions, out_evaluations_context={},
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line 84, in parse_directory
    self._parse_directory(dir_filter=lambda d: self._check_process_dir(d))
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line 125, in _parse_directory
    self._internal_dir_load(sub_dir, module_loader_registry, dir_filter,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/parser.py", line [21](https://github.com/devoteamgcloud/tf-gcp-modules/runs/5214165685?check_suite_focus=true#step:5:21)1, in _internal_dir_load
    self.external_variables_data.append((var_name, default_value[0], file.path))
IndexError: list index out of range
```

**Comment by gruebel** [comment]
is it the `checkov` GitHub action or your own, where you install `checkov` manually?

**Comment by stefaneacsu** [comment]
First I got in the manual version on my CLI but now after I pushed with some new changes in the repo the GitHub Action checkov it's returning the error I put above. @gruebel

**Comment by stefaneacsu** [comment]
Seems that the issue does not appear anymore so I suppose it got fixed?

**Comment by gruebel** [comment]
yes that was our goal 😄
