### ISSUE TITLE
Cant run checkov -d .

### ISSUE THREAD

**Issue by acidflash** [bridgecrewio/checkov#254]
**Describe the bug**
I did just run installation of checkov on my MAC with brew installation inscrutions.
When i run: checkov -d .
The output is:

`ERROR:checkov.terraform.checks.resource.aws.PasswordPolicyReuse:Failed to run check: Ensure IAM password policy prevents password reuse for configuration: {'count': ['True ? 1 : 0}'], 'max_password_age': [0], 'minimum_password_length': [8], 'allow_users_to_change_password': [True], 'hard_expiry': [False], 'password_reuse_prevention': ['${var.password_reuse_prevention}'], 'require_lowercase_characters': [True], 'require_uppercase_characters': [True], 'require_numbers': [True], 'require_symbols': [True]} at file: /.terraform/modules/iam_assumable_roles/modules/iam-account/main.tf
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/main.py", line 63, in run
    files=file)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 21, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/terraform/runner.py", line 46, in run
    self.check_tf_definition(report, root_folder)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/terraform/runner.py", line 86, in check_tf_definition
    block_type)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/terraform/runner.py", line 108, in run_block
    skipped_checks)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 49, in scan
    entity_name=entity_name, entity_type=entity_type, skip_info=skip_info)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 44, in run
    raise e
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/Cellar/checkov/1.0.271/libexec/lib/python3.7/site-packages/checkov/terraform/checks/resource/aws/PasswordPolicyReuse.py", line 22, in scan_resource_conf
    if conf[key][0] >= 24:
TypeError: '>=' not supported between instances of 'str' and 'int'`

**To Reproduce**
1. Go to 'project map'
2. Run cli command  'checkov -d .'
3. See error

**Expected behavior**
That the application doesn't crash

**Screenshots**
<img width="1262" alt="Crash" src="https://user-images.githubusercontent.com/1126336/81146609-ecce1e00-8f78-11ea-8b58-616db036f73b.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.4
 - Checkov Version 1.0.271

**Comment by nimrodkor** [comment]
Hey @acidflash , thanks for reporting!

Please check out the newest version, available also through `brew upgrade checkov`!
Fixed version is 1.0.273. If it isn't solved - let us know here!
