### ISSUE TITLE
Cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by afterdesign** [bridgecrewio/checkov#271]
**Describe the bug**
From version 1.0.299 I'm unable to run checkov againts single file (does not matter if it's empty or have some resource definition).

```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 89, in run
    scan_reports = runner_registry.run(external_checks_dir=args.external_checks_dir, files=args.file)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 23, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/kubernetes/runner.py", line 31, in run
    (definitions[file], definitions_raw[file]) = parse(file)
TypeError: cannot unpack non-iterable NoneType object
```

**To Reproduce**
touch test.tf
checkov -f test.tf

**Expected behavior**
Prior to version 1.0.299:
```
➜ checkov -f test.tf

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

version: 1.0.298
```

**Desktop (please complete the following information):**
MacOS, python3.8, installed with pip3, checkov >= 1.0.299

**Comment by schosterbarak** [comment]
Thank you @afterdesign for reporting this. Fixed at https://github.com/bridgecrewio/checkov/pull/272 and tests added to prevent that from happening again. much appreciated!
