### ISSUE TITLE
checkov hanging after crash of lexer scanning terraform

### ISSUE THREAD

**Issue by jfharden** [bridgecrewio/checkov#2717]
**Describe the issue**
When running checkov against terraform formatted in a particular way a crash occurs in a child process and the checkov process hangs forever.

**Examples**
I have distilled a real-world crash down to the bare minimum to create a minimal demonstration of the crash, so although this is a toy example looking at this problem was sparked by real examples which are much more complex than this.
```terraform
locals {
  foo = (
    true
    || false
  )
}

output "foo" {
  value = local.foo
}
```

If the `foo =` assignment is changed so the `||` is on the end of the true line the crash does not occur:

```terraform
locals {
  foo = (
    true ||
    false
  )
}

output "foo" {
  value = local.foo
}
```

Terraform is happy with the syntax:
```
$ terraform fmt
$ terraform validate
Success! The configuration is valid.
$ terraform apply

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

foo = true
```

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
$ LOG_LEVEL=DEBUG checkov -f test.tf
2022-03-30 14:02:44,752 [MainThread  ] [DEBUG]  Leveraging the bundled IAM Definition.
2022-03-30 14:02:44,752 [MainThread  ] [DEBUG]  Leveraging the IAM definition at /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/policy_sentry/shared/data/iam-definition.json
2022-03-30 14:02:44,890 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/bicep/checks/graph_checks
2022-03-30 14:02:44,966 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,068 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,100 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,100 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,149 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,158 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,205 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/Users/jonathanharden/test/checkov, universal_newlines=False, shell=None, istream=None)
2022-03-30 14:02:45,216 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/Users/jonathanharden/test/checkov, universal_newlines=False, shell=None, istream=None)
2022-03-30 14:02:45,261 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,396 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,407 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,407 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,410 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,414 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,414 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,414 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,416 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,538 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,538 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,539 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,539 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,539 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,543 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,544 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,549 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,618 [MainThread  ] [DEBUG]  Checkov version: 2.0.1010
2022-03-30 14:02:45,618 [MainThread  ] [DEBUG]  Python executable: /Users/jonathanharden/test/checkov/.venv/bin/python
2022-03-30 14:02:45,618 [MainThread  ] [DEBUG]  Python version: 3.10.4 (main, Mar 30 2022, 13:51:16) [Clang 13.0.0 (clang-1300.0.29.30)]
2022-03-30 14:02:45,618 [MainThread  ] [DEBUG]  Checkov executable (argv[0]): /Users/jonathanharden/test/checkov/.venv/bin/checkov
2022-03-30 14:02:45,618 [MainThread  ] [DEBUG]  Command Line Args:   -f test.tf
Defaults:
  --framework:       ['all']
  --branch:          master
  --download-external-modules:False
  --external-modules-download-path:.external_modules
  --evaluate-variables:True

2022-03-30 14:02:45,619 [MainThread  ] [INFO ]  Resultant set of frameworks (removing skipped frameworks): all
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  terraform_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  cloudformation_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  kubernetes_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  serverless_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  arm_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [DEBUG]  terraform_plan_runner declares no system dependency checks required.
2022-03-30 14:02:45,619 [MainThread  ] [INFO ]  Checking necessary system dependancies for helm checks.
2022-03-30 14:02:45,625 [MainThread  ] [INFO ]  Error running necessary tools to process helm checks.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  dockerfile_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  secrets_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  json_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  yaml_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  github_configuration_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  gitlab_configuration_runner declares no system dependency checks required.
2022-03-30 14:02:45,626 [MainThread  ] [DEBUG]  bitbucket_configuration_runner declares no system dependency checks required.
2022-03-30 14:02:45,627 [MainThread  ] [INFO ]  Checking necessary system dependancies for kustomize checks.
2022-03-30 14:02:45,864 [MainThread  ] [INFO ]  Found working version of kustomize dependancy kubectl: 1.22
2022-03-30 14:02:45,864 [MainThread  ] [DEBUG]  sca_package_runner declares no system dependency checks required.
2022-03-30 14:02:45,865 [MainThread  ] [DEBUG]  github_actions_runner declares no system dependency checks required.
2022-03-30 14:02:45,865 [MainThread  ] [DEBUG]  bicep_runner declares no system dependency checks required.
2022-03-30 14:02:45,865 [MainThread  ] [INFO ]  The following frameworks will automatically be disabled due to missing system dependencies: helm
2022-03-30 14:02:45,865 [MainThread  ] [DEBUG]  No API key found. Scanning locally only.
2022-03-30 14:02:46,009 [MainThread  ] [DEBUG]  Got checkov mappings and guidelines from Bridgecrew BE
2022-03-30 14:02:46,010 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/terraform/checks/graph_checks
2022-03-30 14:02:46,010 [MainThread  ] [INFO ]  Searching through ['azure', '__pycache__', 'gcp', 'aws'] and ['__init__.py']
2022-03-30 14:02:46,010 [MainThread  ] [INFO ]  Searching through [] and ['AzureActiveDirectoryAdminIsConfigured.yaml', 'AzureAntimalwareIsConfiguredWithAutoUpdatesForVMs.yaml', 'MSQLenablesCustomerManagedKey.yaml', 'AzureSynapseWorkspacesHaveNoIPFirewallRulesAttached.yaml', 'StorageCriticalDataEncryptedCMK.yaml', 'AzureStorageAccountsUseCustomerManagedKeyForEncryption.yaml', 'VMHasBackUpMachine.yaml', 'VirtualMachinesUtilizingManagedDisks.yaml', 'DataExplorerEncryptionUsesCustomKey.yaml', 'SQLServerAuditingEnabled.yaml', 'SQLServerAuditingRetention90Days.yaml', 'StorageContainerActivityLogsNotPublic.yaml', 'AzureUnattachedDisksAreEncrypted.yaml', 'AzureDataFactoriesEncryptedWithCustomerManagedKey.yaml', 'VAsetPeriodicScansOnSQL.yaml', 'VAconfiguredToSendReports.yaml', 'StorageLoggingIsEnabledForTableService.yaml', 'PGSQLenablesCustomerManagedKey.yaml', 'AzureMSSQLServerHasSecurityAlertPolicy.yaml', 'StorageLoggingIsEnabledForBlobService.yaml', 'AzureNetworkInterfacePublicIPAddressId.yaml', 'AccessToPostgreSQLFromAzureServicesIsDisabled.yaml', 'CognitiveServicesCustomerManagedKey.yaml', 'VAconfiguredToSendReportsToAdmins.yaml', 'VAisEnabledInStorageAccount.yaml']
2022-03-30 14:02:46,100 [MainThread  ] [INFO ]  Searching through [] and ['__init__.cpython-310.pyc']
2022-03-30 14:02:46,101 [MainThread  ] [INFO ]  Searching through [] and ['GCPKMSCryptoKeysAreNotPubliclyAccessible.yaml', 'GCPLogBucketsConfiguredUsingLock.yaml', 'GCPAuditLogsConfiguredForAllServicesAndUsers.yaml', 'GCPKMSKeyRingsAreNotPubliclyAccessible.yaml', 'GCPProjectHasNoLegacyNetworks.yaml', 'ServiceAccountHasGCPmanagedKey.yaml', 'DisableAccessToSqlDBInstanceForRootUsersWithoutPassword.yaml', 'GCPContainerRegistryReposAreNotPubliclyAccessible.yaml', 'GKEClustersAreNotUsingDefaultServiceAccount.yaml']
2022-03-30 14:02:46,143 [MainThread  ] [INFO ]  Searching through [] and ['GuardDutyIsEnabled.yaml', 'AppSyncProtectedByWAF.yaml', 'SGAttachedToResource.yaml', 'WAF2HasLogs.yaml', 'SubnetHasACL.yaml', 'S3PublicACLRead.yaml', 'EIPAllocatedToVPCAttachedEC2.yaml', 'EncryptedEBSVolumeOnlyConnectedToEC2s.yaml', 'CloudtrailHasCloudwatch.yaml', 'AWSNATGatewaysshouldbeutilized.yaml', 'APIGWLoggingLevelsDefinedProperly.yaml', 'AutoScalingEnableOnDynamoDBTables.yaml', 'CloudFrontHasSecurityHeadersPolicy.yaml', 'VPCHasRestrictedSG.yaml', 'AutoScallingEnabledELB.yaml', 'S3BucketLogging.yaml', 'ALBRedirectsHTTPToHTTPS.yaml', 'VPCHasFlowLog.yaml', 'AMRClustersNotOpenToInternet.yaml', 'AWSSSMParameterShouldBeEncrypted.yaml', 'PostgresDBHasQueryLoggingEnabled.yaml', 'S3BucketEncryption.yaml', 'PostgresRDSHasQueryLoggingEnabled.yaml', 'Route53ARecordAttachedResource.yaml', 'APIProtectedByWAF.yaml', 'IAMUserHasNoConsoleAccess.yaml', 'IAMUsersAreMembersAtLeastOneGroup.yaml', 'ALBProtectedByWAF.yaml', 'HTTPNotSendingPasswords.yaml', 'S3BucketHasPublicAccessBlock.yaml', 'IAMGroupHasAtLeastOneUser.yaml', 'RDSClusterHasBackupPlan.yaml', 'S3BucketVersioning.yaml', 'EFSAddedBackup.yaml', 'S3PublicACLWrite.yaml', 'EBSAddedBackup.yaml']
2022-03-30 14:02:46,330 [MainThread  ] [INFO ]  Scanning root folder and producing fresh tf_definitions and context
2022-03-30 14:02:46,332 [MainThread  ] [INFO ]  creating cloudformation graph
2022-03-30 14:02:46,334 [MainThread  ] [INFO ]  [CloudformationLocalGraph] created 0 vertices
2022-03-30 14:02:46,335 [MainThread  ] [INFO ]  [CloudformationLocalGraph] created 0 edges
2022-03-30 14:02:46,335 [MainThread  ] [INFO ]  Rendering variables, graph has 0 vertices and 0 edges
2022-03-30 14:02:46,337 [MainThread  ] [INFO ]  done evaluating edges
2022-03-30 14:02:46,338 [MainThread  ] [INFO ]  done evaluate_non_rendered_values
2022-03-30 14:02:46,337 [MainThread  ] [DEBUG]  Parsing /Users/jonathanharden/test/checkov/test.tf
2022-03-30 14:02:46,339 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/cloudformation/checks/graph_checks
2022-03-30 14:02:46,340 [MainThread  ] [INFO ]  Searching through ['__pycache__'] and ['__init__.py']
2022-03-30 14:02:46,340 [MainThread  ] [INFO ]  creating kubernetes graph
2022-03-30 14:02:46,340 [MainThread  ] [DEBUG]  Failed to load /Users/jonathanharden/test/checkov/test.tf as is not a .json file, skipping
2022-03-30 14:02:46,342 [MainThread  ] [INFO ]  Searching through [] and ['__init__.cpython-310.pyc']
2022-03-30 14:02:46,343 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/kubernetes/checks/graph_checks
2022-03-30 14:02:46,344 [MainThread  ] [INFO ]  Searching through ['__pycache__'] and ['__init__.py']
2022-03-30 14:02:46,346 [MainThread  ] [INFO ]  Searching through [] and ['__init__.cpython-310.pyc']
2022-03-30 14:02:46,351 [MainThread  ] [DEBUG]  The runner requires that external checks are defined.
2022-03-30 14:02:46,351 [MainThread  ] [INFO ]  Secrets scanning will scan 1 files
2022-03-30 14:02:46,353 [MainThread  ] [DEBUG]  The runner requires that external checks are defined.
2022-03-30 14:02:46,364 [MainThread  ] [INFO ]  Running with --file argument; file must be a kustomization.yaml file
2022-03-30 14:02:46,368 [MainThread  ] [INFO ]  creating kubernetes graph
2022-03-30 14:02:46,362 [MainThread  ] [DEBUG]  validation error
Traceback (most recent call last):
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/common/vcs/vcs_schema.py", line 13, in validate
    validate(instance=data, schema=self.schema)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'object'

Failed validating 'type' in schema:
    {'properties': {'data': {'properties': {'organization': {'properties': {'description': {'type': 'string'},
                                                                            'ipAllowListEnabledSetting': {'type': 'string'},
                                                                            'ipAllowListForInstalledAppsEnabledSetting': {'type': 'string'},
                                                                            'login': {'type': 'string'},
                                                                            'name': {'type': 'string'},
                                                                            'requiresTwoFactorAuthentication': {'type': 'boolean'},
                                                                            'samlIdentityProvider': {'properties': {'ssoUrl': {'type': 'string'}},
                                                                                                     'type': 'object'}},
                                                             'required': ['name',
                                                                          'login',
                                                                          'description',
                                                                          'ipAllowListEnabledSetting',
                                                                          'ipAllowListForInstalledAppsEnabledSetting',
                                                                          'requiresTwoFactorAuthentication'],
                                                             'type': 'object'}},
                             'required': ['organization'],
                             'type': 'object'}},
     'required': ['data'],
     'type': 'object'}

On instance:
    None
2022-03-30 14:02:46,370 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/kubernetes/checks/graph_checks
2022-03-30 14:02:46,372 [MainThread  ] [INFO ]  Searching through ['__pycache__'] and ['__init__.py']
2022-03-30 14:02:46,373 [MainThread  ] [INFO ]  Searching through [] and ['__init__.cpython-310.pyc']
2022-03-30 14:02:46,375 [MainThread  ] [DEBUG]  Sucessfully ran k8s scan on Kustomization templated files in tmp scan dir : /var/folders/rh/6ll5hc1s2xb7kwz4j3kp1bhw0000gp/T/tmpufvbg49g
2022-03-30 14:02:46,366 [MainThread  ] [DEBUG]  failed while parsing file /Users/jonathanharden/test/checkov/test.tf
Traceback (most recent call last):
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/lexer.py", line 528, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <unprintable UnexpectedCharacters object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/terraform/parser.py", line 712, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/hcl2/api.py", line 10, in load
    return loads(file.read())
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/hcl2/api.py", line 68, in loads
    return hcl2.parse(text + "\n")
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/hcl2/parser.py", line 43, in parse
    tree = Hcl2.lark_parser.parse(text)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/lexer.py", line 537, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <unprintable UnexpectedToken object>
Process ForkProcess-1:1:
Traceback (most recent call last):
  File "/Users/jonathanharden/.asdf/installs/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/jonathanharden/.asdf/installs/python/3.10.4/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 29, in func_wrapper
    result = original_func(item)
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/terraform/runner.py", line 362, in parse_file
    file_parsing_errors[path] = Exception(str(e))
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/exceptions.py", line 256, in __str__
    % (self.token, self.line, self.column, self._format_expected(self.accepts or self.expected)))
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/exceptions.py", line 142, in _format_expected
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/exceptions.py", line 142, in <listcomp>
    expected = [d[t_name].user_repr() if t_name in d else t_name for t_name in expected]
  File "/Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/lark/lexer.py", line 123, in user_repr
    return self.pattern.raw or self.name
AttributeError: 'PatternRE' object has no attribute 'raw'
2022-03-30 14:02:46,756 [MainThread  ] [INFO ]  [bicep] start to parse 0 files
2022-03-30 14:02:46,757 [MainThread  ] [INFO ]  [bicep] successfully parsed 0 files
2022-03-30 14:02:46,764 [MainThread  ] [INFO ]  Creating Bicep graph
2022-03-30 14:02:46,765 [MainThread  ] [INFO ]  [BicepLocalGraph] created 0 vertices
2022-03-30 14:02:46,765 [MainThread  ] [INFO ]  [BicepLocalGraph] created 0 edges
2022-03-30 14:02:46,766 [MainThread  ] [INFO ]  Successfully created Bicep graph
2022-03-30 14:02:46,767 [MainThread  ] [INFO ]  Loading external checks from /Users/jonathanharden/test/checkov/.venv/lib/python3.10/site-packages/checkov/bicep/checks/graph_checks
```

Note that the process hangs at this point never to complete

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6.5
 - Checkov Version: 2.0.1010 (previously tried on 2.0.1008)

**Additional context**
Same results with python 3.9.7 and python 3.10.4

**Comment by gruebel** [comment]
Hi @jfharden thanks for creating the issue and adding so much detailed info to it. I created a fix for it and probably it will be reviewed/merged on Sunday.

**Comment by jfharden** [comment]
Thanks so much for the quick response and fix 👍 Much appreciated
