### ISSUE TITLE
Validation Errors with tfplan.json

### ISSUE THREAD

**Issue by travisnburton** [bridgecrewio/checkov#2732]
**Describe the issue**
checkov provides no output when evaluating json plan files

**Examples**
generate tfplan.json -  `terragrunt show -json tfplan.binary > tfplan.json`
**NOTE** - same result when using jq - `terragrunt show -json tfplan.binary | jq '.' > tfplan.json`
execute checkov - `checkov -f tfplan.json`

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
2022-03-31 09:50:59,553 [MainThread  ] [DEBUG]  validation error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/checkov/common/vcs/vcs_schema.py", line 13, in validate
    validate(instance=data, schema=self.schema)
  File "/opt/homebrew/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type 'object'

Failed validating 'type' in schema:
    {'properties': {'data': {'properties': {'organization': {'properties': {'description': {'type': 'string'},
                                                                            'ipAllowListEnabledSetting': {'type': 'string'},
                                                                            'ipAllowListForInstalledAppsEnabledSetting': {'type': 'string'},
                                                                            'login': {'type': 'string'},
                                                                            'name': {'type': 'string'},
                                                                            'requiresTwoFactorAuthentication': {'type': 'boolean'},
                                                                            'samlIdentityProvider': {'properties': {'ssoUrl': {'type': 'string'}},
                                                                                                     'type': 'object'}},
                                                             'required': ['name',
                                                                          'login',
                                                                          'description',
                                                                          'ipAllowListEnabledSetting',
                                                                          'ipAllowListForInstalledAppsEnabledSetting',
                                                                          'requiresTwoFactorAuthentication'],
                                                             'type': 'object'}},
                             'required': ['organization'],
                             'type': 'object'}},
     'required': ['data'],
     'type': 'object'}

On instance:
    None
```

```
2022-03-31 09:50:59,565 [MainThread  ] [DEBUG]  validation error
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/checkov/common/vcs/vcs_schema.py", line 13, in validate
    validate(instance=data, schema=self.schema)
  File "/opt/homebrew/lib/python3.9/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'approvals_before_merge' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'properties': {'approvals_before_merge': {'type': 'integer'},
                    'disable_overriding_approvers_per_merge_request': {'type': 'boolean'},
                    'merge_requests_author_approval': {'type': 'boolean'},
                    'merge_requests_disable_committers_approval': {'type': 'boolean'},
                    'require_password_to_approve': {'type': 'boolean'},
                    'reset_approvals_on_push': {'type': 'boolean'}},
     'required': ['approvals_before_merge',
                  'reset_approvals_on_push',
                  'disable_overriding_approvers_per_merge_request',
                  'merge_requests_author_approval',
                  'merge_requests_disable_committers_approval',
                  'require_password_to_approve'],
     'type': 'object'}

On instance:
    {'configuration': {'provider_config': {'aws': {'expressions': {'assume_role': [{'role_arn': {'constant_value': 'arn:aws:iam::SNIP:role/FullAdmin'}}],
                                                                   'region': {'constant_value': 'us-west-2'}},
                                                   'name': 'aws',
                                                   'version_constraint': '3.74.1'}},
                       'root_module': {'outputs': {'key_name': {'expression': {'references': ['aws_key_pair.this.key_name',
                                                                                              'aws_key_pair.this']}},
                                                   'keypair_id': {'expression': {'references': ['aws_key_pair.this.id',
                                                                                                'aws_key_pair.this']}}},
                                       'resources': [{'address': 'aws_key_pair.this',
                                                      'expressions': {'key_name': {'references': ['var.key_name']},
                                                                      'public_key': {'references': ['var.public_key']}},
                                                      'mode': 'managed',
                                                      'name': 'this',
                                                      'provider_config_key': 'aws',
                                                      'schema_version': 1,
                                                      'type': 'aws_key_pair'}],
                                       'variables': {'key_name': {},
                                                     'public_key': {},
                                                     'tags': {}}}},
     'format_version': '1.0',
     'output_changes': {'key_name': {'actions': ['no-op'],
                                     'after': 'sandbox-py',
                                     'after_sensitive': False,
                                     'after_unknown': False,
                                     'before': 'sandbox-py',
                                     'before_sensitive': False},
                        'keypair_id': {'actions': ['update'],
                                       'after_sensitive': False,
                                       'after_unknown': True,
                                       'before': 'sandbox-py',
                                       'before_sensitive': False}},
     'planned_values': {'outputs': {'key_name': {'sensitive': False,
                                                 'value': 'sandbox-py'},
                                    'keypair_id': {'sensitive': False}},
                        'root_module': {'resources': [{'address': 'aws_key_pair.this',
                                                       'mode': 'managed',
                                                       'name': 'this',
                                                       'provider_name': 'registry.terraform.io/hashicorp/aws',
                                                       'schema_version': 1,
                                                       'sensitive_values': {'tags_all': {}},
                                                       'type': 'aws_key_pair',
                                                       'values': {'key_name': 'sandbox-py',
                                                                  'public_key': 'ssh-rsa '
                                                                                'SNIP',
                                                                  'tags': None}}]}},
     'prior_state': {'format_version': '1.0',
                     'terraform_version': '1.1.7',
                     'values': {'outputs': {'key_name': {'sensitive': False,
                                                         'value': 'sandbox-py'},
                                            'keypair_id': {'sensitive': False,
                                                           'value': 'sandbox-py'}},
                                'root_module': {}}},
     'resource_changes': [{'address': 'aws_key_pair.this',
                           'change': {'actions': ['create'],
                                      'after': {'key_name': 'sandbox-py',
                                                'public_key': 'ssh-rsa '
                                                              'SNIP',
                                                'tags': None},
                                      'after_sensitive': {'tags_all': {}},
                                      'after_unknown': {'arn': True,
                                                        'fingerprint': True,
                                                        'id': True,
                                                        'key_name_prefix': True,
                                                        'key_pair_id': True,
                                                        'tags_all': True},
                                      'before': None,
                                      'before_sensitive': False},
                           'mode': 'managed',
                           'name': 'this',
                           'provider_name': 'registry.terraform.io/hashicorp/aws',
                           'type': 'aws_key_pair'}],
     'resource_drift': [{'address': 'aws_key_pair.this',
                         'change': {'actions': ['delete'],
                                    'after': None,
                                    'after_sensitive': False,
                                    'after_unknown': {},
                                    'before': {'arn': 'arn:aws:ec2:us-west-2:SNIP:key-pair/sandbox-py',
                                               'fingerprint': 'da:6f:c9:c6:a8:f4:af:8f:5a:08:14:5f:ea:66:81:ef',
                                               'id': 'sandbox-py',
                                               'key_name': 'sandbox-py',
                                               'key_name_prefix': '',
                                               'key_pair_id': 'key-0c73125c6d8fe134d',
                                               'public_key': 'ssh-rsa '
                                                             'SNIP',
                                               'tags': None,
                                               'tags_all': {}},
                                    'before_sensitive': {'tags_all': {}}},
                         'mode': 'managed',
                         'name': 'this',
                         'provider_name': 'registry.terraform.io/hashicorp/aws',
                         'type': 'aws_key_pair'}],
     'terraform_version': '1.1.7',
     'variables': {'key_name': {'value': 'sandbox-py'},
                   'public_key': {'value': 'ssh-rsa '
                                           'SNIP'},
                   'tags': {'value': {'billing-cost-center': 1234,
                                      'billing-group': 'basic',
                                      'billing-hfm': 4321,
                                      'env': 'sandbox-py',
                                      'terraform': True,
                                      'terraform-path': 'terragrunt/aws-SNIP/sandbox-py/us-west-2/common/ec2-keypair'}}}}
```
 - OS: [MacOS 12.2.1]
 - Checkov Version 2.0.1020

**Comment by gruebel** [comment]
Hi @travisnburton thanks for reaching out. Great find with the error, but this has nothing to do with your TF plan output, these are different frameworks which thinks that they found something interesting for them. I can't tell why you don't see any check results for your TF plan. Is it possible to share a small TF plan with us? you should of course remove any sensible information.

**Comment by gruebel** [comment]
on an extra note, you can also run `checkov` like this, then it will only run for TF plan checks
```shell
checkov -f tfplan.json --framework terraform_plan
```

**Comment by travisnburton** [comment]
tfplan.json below, thanks!

```json
{
  "format_version": "1.0",
  "terraform_version": "1.1.7",
  "variables": {
    "env": {
      "value": "sandbox-py"
    },
    "name": {
      "value": "foo"
    },
    "tags": {
      "value": {
        "billing-cost-center": 1234,
        "billing-group": "basic",
        "billing-hfm": 4321,
        "env": "sandbox-py",
        "terraform": true,
        "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
      }
    },
    "vpc_id": {
      "value": "mocked"
    }
  },
  "planned_values": {
    "root_module": {}
  },
  "output_changes": {
    "sg_id": {
      "actions": [
        "delete"
      ],
      "before": null,
      "after": null,
      "after_unknown": false,
      "before_sensitive": false,
      "after_sensitive": false
    }
  },
  "configuration": {
    "provider_config": {
      "aws": {
        "name": "aws",
        "version_constraint": "3.74.1",
        "expressions": {
          "assume_role": [
            {
              "role_arn": {
                "constant_value": "arn:aws:iam::269954864908:role/FullAdmin"
              }
            }
          ],
          "region": {
            "constant_value": "us-west-2"
          }
        }
      }
    },
    "root_module": {
      "outputs": {
        "sg_id": {
          "expression": {
            "references": [
              "aws_security_group.this.id",
              "aws_security_group.this"
            ]
          }
        }
      },
      "resources": [
        {
          "address": "aws_security_group.this",
          "mode": "managed",
          "type": "aws_security_group",
          "name": "this",
          "provider_config_key": "aws",
          "expressions": {
            "name": {
              "references": [
                "var.env",
                "var.name"
              ]
            },
            "tags": {
              "references": [
                "var.tags"
              ]
            },
            "vpc_id": {
              "references": [
                "var.vpc_id"
              ]
            }
          },
          "schema_version": 1
        }
      ],
      "variables": {
        "env": {},
        "name": {},
        "tags": {},
        "vpc_id": {}
      }
    }
  }
}

```

**Comment by travisnburton** [comment]
After posting above json, i realized the plan output was for a destroy operation (`plan -destroy`).  I changed to a standard plan operation, and confirmed that the plan output was processed correctly.  The standard plan output is below, for reference:

```json
{
  "format_version": "1.0",
  "terraform_version": "1.1.7",
  "variables": {
    "env": {
      "value": "sandbox-py"
    },
    "name": {
      "value": "foo"
    },
    "tags": {
      "value": {
        "billing-cost-center": 1234,
        "billing-group": "basic",
        "billing-hfm": 4321,
        "env": "sandbox-py",
        "terraform": true,
        "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
      }
    },
    "vpc_id": {
      "value": "mocked"
    }
  },
  "planned_values": {
    "outputs": {
      "sg_id": {
        "sensitive": false
      }
    },
    "root_module": {
      "resources": [
        {
          "address": "aws_security_group.this",
          "mode": "managed",
          "type": "aws_security_group",
          "name": "this",
          "provider_name": "registry.terraform.io/hashicorp/aws",
          "schema_version": 1,
          "values": {
            "description": "Managed by Terraform",
            "name": "sandbox-py-foo",
            "revoke_rules_on_delete": false,
            "tags": {
              "billing-cost-center": "1234",
              "billing-group": "basic",
              "billing-hfm": "4321",
              "env": "sandbox-py",
              "terraform": "true",
              "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
            },
            "tags_all": {
              "billing-cost-center": "1234",
              "billing-group": "basic",
              "billing-hfm": "4321",
              "env": "sandbox-py",
              "terraform": "true",
              "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
            },
            "timeouts": null,
            "vpc_id": "mocked"
          },
          "sensitive_values": {
            "egress": [],
            "ingress": [],
            "tags": {},
            "tags_all": {}
          }
        }
      ]
    }
  },
  "resource_changes": [
    {
      "address": "aws_security_group.this",
      "mode": "managed",
      "type": "aws_security_group",
      "name": "this",
      "provider_name": "registry.terraform.io/hashicorp/aws",
      "change": {
        "actions": [
          "create"
        ],
        "before": null,
        "after": {
          "description": "Managed by Terraform",
          "name": "sandbox-py-foo",
          "revoke_rules_on_delete": false,
          "tags": {
            "billing-cost-center": "1234",
            "billing-group": "basic",
            "billing-hfm": "4321",
            "env": "sandbox-py",
            "terraform": "true",
            "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
          },
          "tags_all": {
            "billing-cost-center": "1234",
            "billing-group": "basic",
            "billing-hfm": "4321",
            "env": "sandbox-py",
            "terraform": "true",
            "terraform-path": "terragrunt/aws-269954864908/sandbox-py/us-west-2/common/sg-this"
          },
          "timeouts": null,
          "vpc_id": "mocked"

```

**Comment by gruebel** [comment]
great, thanks for checking again.
