### ISSUE TITLE
GCP: GoogleCloudSqlDatabasePublicallyAccessible raises AttributeError

### ISSUE THREAD

**Issue by acdha** [bridgecrewio/checkov#276]
# Description

A SQL database instance declared like this crashes the check for publically-accessible instances:

```hcl
resource "google_sql_database_instance" "sql_instance" {
  name   = "${var.gcp-project}-db-dev"
  region = "${var.region}"
  settings {
    tier = "${var.db_machine_type}"
    ip_configuration {
                ipv4_enabled = true
                authorized_networks {
                name = "${var.gcp-project}-sql-network"
                value = google_compute_address.ip_address-dev.address
                }
  }
 }
}
```

## Crash Log

```
ERROR:checkov.terraform.checks.resource.gcp.GoogleCloudSqlDatabasePublicallyAccessible:Failed to run check: Ensure that Cloud SQL database Instances are not open to the world for configuration: {'name': ['${var.gcp-project}-db-dev'], 'region': ['us-central1'], 'settings': [{'tier': ['${var.db_machine_type}'], 'ip_configuration': [{'ipv4_enabled': [True], 'authorized_networks': [{'name': ['${var.gcp-project}-sql-network'], 'value': ['${google_compute_address.ip_address-dev.address}']}]}]}]} at file: /bcs/modules/aws/prod/cloud-sql.tf
```

<details>

```
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 80, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=args.external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 23, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 48, in run
    self.check_tf_definition(report, root_folder,runner_filter)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 88, in check_tf_definition
    self.run_block(definition[block_type], definitions_context, full_file_path, report, scanned_file,
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 110, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks,runner_filter)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 64, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check_registry.py", line 70, in run_check
    result = check.run(scanned_file=scanned_file, entity_configuration=entity_configuration,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 44, in run
    raise e
  File "/usr/local/lib/python3.8/site-packages/checkov/common/checks/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/checks/resource/gcp/GoogleCloudSqlDatabasePublicallyAccessible.py", line 24, in scan_resource_conf
    if 'value' in authorized_network.keys():
AttributeError: 'str' object has no attribute 'keys'
```

</details>

## System Information

 - macOS 10.15.4
- Python 3.8.2
 - 1.0.308

**Comment by acdha** [comment]
Thanks @nimrodkor!
