### ISSUE TITLE
Python Custom Checks throwing traceback but still running

### ISSUE THREAD

**Issue by solaris187** [bridgecrewio/checkov#2851]
Attempting to write some custom checks for Checkov. When I try running the checks, python exceptions are thrown, however the checks do still run. Looking for feedback/advice on why the exceptions are happening so I can clean them up.

Checkov Version:  2.0.1075

TagExists.py
```
from checkov.common.models.enums import CheckCategories, CheckResult
from checkov.terraform.checks.resource.base_resource_check import BaseResourceCheck

class TagExists(BaseResourceCheck):
    def __init__(self, check_id, resource, tag_name, case_sensitive=True):
        an = 'an' if tag_name[0] in 'aeiouAEIOU' else 'a'
        name = f"Ensure every {resource} resource has {an} '{tag_name}' tag"
        supported_resources = [resource]
        categories = [CheckCategories.CONVENTION]
        super().__init__(name=name, id=check_id, categories=categories, supported_resources=supported_resources)
        self.tag_name = tag_name
        self.case_sensitive = case_sensitive

    def scan_resource_conf(self, conf):
        if 'tags' in conf:
            tags = conf['tags']
            if self.get_tag_value(tags):
                return CheckResult.PASSED

        return CheckResult.FAILED

    def get_tag_value(self, tags):
        for tag in tags:
            for (tag_name, tag_value) in tag.items():
                if (self.case_sensitive and self.tag_name == tag_name) or (not self.case_sensitive and self.tag_name.upper() == tag_name.upper()):
                    return tag_value

        return None
```
CostCenter.py
```
from TagExists import TagExists

class CostCenterTagExists(TagExists):
    def __init__(self):
        super().__init__(check_id='AWS_IVZ_Tags_CostCenter', resource='aws_kms_key', tag_name='CostCenter', case_sensitive=True)

check = CostCenterTagExists()
```

Traceback Error:

```
2022-04-21 12:21:33,796 [ThreadPoolEx] [ERROR]  Cannot load external check 'CostCenter' from ../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py
Traceback (most recent call last):
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks\base_check_registry.py", line 186, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py", line 1, in <module>
    from TagExists import TagExists
ImportError: cannot import name 'TagExists' from 'TagExists' (../../../../checkov/checkov-custom-rules/check_tags_python\TagExists.py)
2022-04-21 12:21:33,813 [ThreadPoolEx] [ERROR]  Cannot load external check 'CostCenter' from ../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py
Traceback (most recent call last):
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks\base_check_registry.py", line 186, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py", line 1, in <module>
    from TagExists import TagExists
ImportError: cannot import name 'TagExists' from 'TagExists' (../../../../checkov/checkov-custom-rules/check_tags_python\TagExists.py)
2022-04-21 12:21:33,826 [ThreadPoolEx] [ERROR]  Cannot load external check 'CostCenter' from ../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py
Traceback (most recent call last):
  File "C:\Users\pacea\AppData\Roaming\Python\Python39\site-packages\checkov\common\checks\base_check_registry.py", line 186, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "../../../../checkov/checkov-custom-rules/check_tags_python\CostCenter.py", line 1, in <module>
    from TagExists import TagExists
```

Checks still run:

```
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.0.1075

terraform_plan scan results:

Passed checks: 5, Failed checks: 0, Skipped checks: 0

Check: CKV_AWS_227: "Ensure KMS key is enabled"
        PASSED for resource: aws_kms_key.key
        File: /tfplan.json:118-148
Check: CKV_AWS_33: "Ensure KMS key policy does not contain wildcard (*) principal"
        PASSED for resource: aws_kms_key.key
        File: /tfplan.json:118-148
        Guide: https://docs.bridgecrew.io/docs/ensure-kms-key-policy-does-not-contain-wildcard-principal
Check: CKV_AWS_7: "Ensure rotation for customer created CMKs is enabled"
        PASSED for resource: aws_kms_key.key
        File: /tfplan.json:118-148
        Guide: https://docs.bridgecrew.io/docs/logging_8
Check: AWS_IVZ_Tags_CostCenter: "Ensure every aws_kms_key resource has a 'CostCenter' tag"
        PASSED for resource: aws_kms_key.key
        File: /tfplan.json:118-148
Check: AWS_IVZ_Tags_TagOverride: "Ensure every aws_kms_key resource has a 'TagOverride' tag"
        PASSED for resource: aws_kms_key.key
        File: /tfplan.json:118-148
```

**Comment by nimrodkor** [comment]
Hmmm interesting use caes. What happens if, in `CostCenter.py`, you replace this:
`from TagExists import TagExists`

With:
`from .TagExists import TagExists` (or the correct local path, for that matter)?
