### ISSUE TITLE
Bug in AWS/ElasticSearch check

### ISSUE THREAD

**Issue by prabhu** [bridgecrewio/checkov#295]
**Describe the bug**
AWS Elastic search node to node encryption is failing with the below error.

```bash
ERROR:checkov.terraform.checks.resource.aws.ElasticsearchNodeToNodeEncryption:Failed to run check: Ensure all Elasticsearch has node-to-node encryption enabled for configuration: {'count': ['False || False ? 1 : 0}'], 'domain_name': ['sadcloud'], 'elasticsearch_version': ['6.0'], 'cluster_config': [{'instance_type': ['t2.small.elasticsearch']}], 'ebs_options': [{'ebs_enabled': [True], 'volume_type': ['gp2'], 'volume_size': [10]}], 'log_publishing_options': [{'cloudwatch_log_group_arn': ['${aws_cloudwatch_log_group.main.arn}'], 'log_type': ['INDEX_SLOW_LOGS'], 'enabled': ['${!False']}, {'cloudwatch_log_group_arn': ['${aws_cloudwatch_log_group.main.arn}'], 'log_type': ['SEARCH_SLOW_LOGS'], 'enabled': ['${!False']}], 'depends_on': [['${aws_cloudwatch_log_group.main}']]} at file: /modules/aws/elasticsearch/main.tf
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.6/site-packages/checkov/main.py", line 84, in run
    files=file)
  File "/usr/local/lib/python3.6/site-packages/checkov/common/runners/runner_registry.py", line 25, in run
    runner_filter=self.runner_filter)
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/runner.py", line 48, in run
    self.check_tf_definition(report, root_folder,runner_filter)
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/runner.py", line 89, in check_tf_definition
    block_type,runner_filter)
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/runner.py", line 110, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks,runner_filter)
  File "/usr/local/lib/python3.6/site-packages/checkov/common/checks/base_check_registry.py", line 64, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/usr/local/lib/python3.6/site-packages/checkov/common/checks/base_check_registry.py", line 71, in run_check
    entity_name=entity_name, entity_type=entity_type, skip_info=skip_info)
  File "/usr/local/lib/python3.6/site-packages/checkov/common/checks/base_check.py", line 44, in run
    raise e
  File "/usr/local/lib/python3.6/site-packages/checkov/common/checks/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py", line 22, in scan_resource_conf
    instance_count = conf["cluster_config"][0]["instance_count"][0]
KeyError: 'instance_count'
```

Offending line
https://github.com/bridgecrewio/checkov/blob/master/checkov/terraform/checks/resource/aws/ElasticsearchNodeToNodeEncryption.py#L22

**To Reproduce**
Use sadcloud repo - https://github.com/nccgroup/sadcloud

**Expected behavior**
Code works without error

**Screenshots**

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**

In general use `.get("<key>", {})` notation when referring to a variable in a dict and always fail-safely by skipping a single test instead of crashing the whole tool.

**Comment by schosterbarak** [comment]
Thank you for reporting this! just pushed a fix

**Comment by prabhu** [comment]
Thank you for the prompt fix!

```instance_count = cluster_config["instance_count"][0]```

This line could fail if `instance_count` is None since the if above is just checking the type `if "instance_count" not in cluster_config` and not the type of the value and its length.

good
```
if "instance_count" not in cluster_config and isinstance(cluster_config["instance_count"], list):
```
or even better is
```
instance_count = cluster_config.get("instance_count", 0)
```
