### ISSUE TITLE
terraform splat interpolation syntax causes parsing issue

### ISSUE THREAD

**Issue by maratsh** [bridgecrewio/checkov#2977]
I'm checking file test.tf with command
```
LOG_LEVEL=DEBUG checkov --quiet -d .
```

```
#test.tf

locals {
  foo = kubernetes_namespace.bar.*.metadata.0.name
}
```
And in the logs I'm getting this error:

```
2022-05-17 16:37:04,262 [MainThread  ] [DEBUG]  failed while parsing file /Users/user/tmp/checkov/test.tf
Traceback (most recent call last):
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/lexer.py", line 528, in lex
    yield lexer.next_token(lexer_state, parser_state)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <unprintable UnexpectedCharacters object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/parser.py", line 726, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 12, in load
    return loads(file.read())
  File "/usr/local/lib/python3.9/site-packages/hcl2/api.py", line 87, in loads
    return hcl2.parse(text + "\n")
  File "/usr/local/lib/python3.9/site-packages/hcl2/parser.py", line 45, in parse
    tree = Hcl2.lark_parser.parse(text)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/lark.py", line 625, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/parsers/lalr_parser.py", line 178, in parse_from_state
    for token in state.lexer.lex(state):
  File "/Users/user/Library/Python/3.9/lib/python/site-packages/lark/lexer.py", line 537, in lex
    raise UnexpectedToken(token, e.allowed, state=parser_state, token_history=[last_token], terminals_by_name=self.root_lexer.terminals_by_name)
lark.exceptions.UnexpectedToken: <unprintable UnexpectedToken object>
```

If I replace "*" with number, a parsing issue is gone.

```
checkov --version
2.0.1143
```

**Comment by guidooliveira** [comment]
exactly the same issue with version 2.0.1144, can't parse any terraform file
