### ISSUE TITLE
CKV_GCP_73 Exception on missing argument

### ISSUE THREAD

**Issue by roymartinezblanco** [bridgecrewio/checkov#3044]
**Describe the issue**
While running Checkov on some GCP terraform resources I noticed that an exception was fired due to a missing field in the terraform plan. As shown on the example below, this field will not always be present and should be validated to avoid execptions

Looking at some resources like the one below you see that it is missing this field

https://github.com/bridgecrewio/checkov/blob/be7585c789b910244b7b9074a97f0da066d404f3/checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py#L27-L29

Error
```
Traceback (most recent call last):
    File "/usr/local/bin/checkov", line 9, in <module>
      sys.exit(run())
    File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 295, in run
      scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=config.file,
    File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 75, in run
      reports: Iterable[Report] = [self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
    File "/usr/local/lib/python3.10/site-packages/checkov/terraform/plan_runner.py", line 62, in run
      self.check_tf_definition(report, root_folder, runner_filter)
    File "/usr/local/lib/python3.10/site-packages/checkov/terraform/plan_runner.py", line 76, in check_tf_definition
      self.run_block(definition[block_type], None, full_file_path, root_folder, report, scanned_file,
    File "/usr/local/lib/python3.10/site-packages/checkov/terraform/plan_runner.py", line 96, in run_block
      results = registry.scan(scanned_file, entity, [], runner_filter)
    File "/usr/local/lib/python3.10/site-packages/checkov/common/checks/base_check_registry.py", line 124, in scan
      result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
    File "/usr/local/lib/python3.10/site-packages/checkov/common/checks/base_check_registry.py", line 138, in run_check
      result = check.run(
    File "/usr/local/lib/python3.10/site-packages/checkov/common/checks/base_check.py", line 75, in run
      check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
    File "/usr/local/lib/python3.10/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 72, in scan_entity_conf
      return self.scan_resource_conf(conf)
    File "/usr/local/lib/python3.10/site-packages/checkov/terraform/checks/resource/gcp/CloudArmorWAFACLCVE202144228.py", line 28, in scan_resource_conf
      if expr and expr[0].get("expression") == ["evaluatePreconfiguredExpr('cve-canary')"]:
    File "/usr/local/lib/python3.10/site-packages/checkov/common/parsers/node.py", line 1[89](xxxxx), in __getattr__
      raise TemplateAttributeError(f'***name*** is invalid')
  checkov.common.parsers.node.TemplateAttributeError: get is invalid
```

**Examples**
```
{
          "address": "google_compute_security_policy.some_policy_name",
          "mode": "managed",
          "type": "google_compute_security_policy",
          "name": "xxxxx",
          "provider_name": "registry.terraform.io/hashicorp/google",
          "schema_version": 0,
          "values": {
            "description": "Description Goes here",
            "fingerprint": "xxxxxx=",
            "id": "projects/xxxxx",
            "name": "xxxxx",
            "project": "xxxxx",
            "rule": [
              {
                "action": "allow",
                "description": "xxxxx",
                "match": [
                  {
                    "config": [{ "src_ip_ranges": ["*"] }],
                    "expr": [],
                    "versioned_expr": "SRC_IPS_V1"
                  }
                ],
                "preview": false,
                "priority": 2147483647
              }
            ],
            "self_link": "xxxxx",
            "timeouts": { "create": null, "delete": null, "update": null },
            "type": "CLOUD_ARMOR"
          },
```

**Version (please complete the following information):**
 - Checkov Version 2.0.1161

**Additional context**

**Comment by schosterbarak** [comment]
@[roymartinezblanco](https://github.com/roymartinezblanco) would you like to raise a pull request fixing the condition?
