### ISSUE TITLE
crashing on GCP EGRESS firewall rule which doesn't have allow field defined

### ISSUE THREAD

**Issue by jaksky** [bridgecrewio/checkov#319]
**Describe the bug**
Checkov crashing on GCP EGRESS firewall rule which doesn't have allow field defined. Tf version 0.12.26 Google provider version: 3.23

**To Reproduce**
1. Resource defined as 
```
resource "google_compute_firewall" "default_deny_egress" {
  name        = "deny-all-egress-all"
  description = "Prevent all egress traffic by default"
  disabled = true

  network        = google_compute_network.vpc_network.name
  enable_logging = true

  priority           = 65534
  direction          = "EGRESS"
  destination_ranges = ["0.0.0.0/0"]
  deny { protocol = "all" }
}
```
2. Run cli command : checkov -d folder
3. See error
```
ERROR:checkov.terraform.checks.resource.gcp.GoogleComputeFirewallUnrestrictedIngress3389:Failed to run check: Ensure Google compute firewall ingress does not allow unrestricted rdp access for configuration: {'name': ['${var.env}-deny-all-egress-all'], 'description': ['Prevent all egress traffic by default'], 'disabled': [True], 'network': ['${google_compute_network.vpc_network.name}'], 'enable_logging': [True], 'priority': [65534], 'direction': ['EGRESS'], 'destination_ranges': [['0.0.0.0/0']], 'deny': [{'protocol': {'all': {}}}]} at file: /../../modules/network/firewalls.tf
Traceback (most recent call last):
  File "/Users/jakub/Development/GIT_REPO/tfenv/bin/checkov", line 5, in <module>
    run()
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/main.py", line 76, in run
    files=file)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 26, in run
    runner_filter=self.runner_filter)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/terraform/runner.py", line 50, in run
    self.check_tf_definition(report, root_folder, runner_filter)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/terraform/runner.py", line 91, in check_tf_definition
    block_type, runner_filter)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/terraform/runner.py", line 113, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 64, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 71, in run_check
    entity_name=entity_name, entity_type=entity_type, skip_info=skip_info)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 44, in run
    raise e
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/Users/jakub/Development/GIT_REPO/tfenv/lib/python3.7/site-packages/checkov/terraform/checks/resource/gcp/**GoogleComputeFirewallUnrestrictedIngress3389.py**", line 22, in scan_resource_conf
    allow_blocks = conf['allow']
KeyError: 'allow'
```

**Expected behavior**
Not to crash when resource has valid specification

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Checkov Version: 1.0.346

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by arielkru** [comment]
Hi @jaksky !
We just released a new version which fixes your problem.
If it's not fixed let us know :)
