### ISSUE TITLE
Parsing does not work with terraform files being encoded with UTF-8/BOM

### ISSUE THREAD

**Issue by andreireinus** [bridgecrewio/checkov#3225]
**Example**
Create an empty file with Unix line endings and save it in UTF-8 encoding with a BOM. Running checkov will fail.
Removing BOM will resolve the issue

**Stacktrace**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/lark/lexer.py", line 536, in lex
    token = self.root_lexer.next_token(lexer_state, parser_state)
  File "/usr/local/lib/python3.8/dist-packages/lark/lexer.py", line 466, in next_token
    raise UnexpectedCharacters(lex_state.text, line_ctr.char_pos, line_ctr.line, line_ctr.column,
lark.exceptions.UnexpectedCharacters: <unprintable UnexpectedCharacters object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/checkov/terraform/parser.py", line 742, in _load_or_die_quietly
    raw_data = hcl2.load(f)
```

**Comment by gruebel** [comment]
@andreireinus thanks for reaching out. I think this should be no problem to fix on our side.
