### ISSUE TITLE
Simple TF file fails to parse

### ISSUE THREAD

**Issue by shearn89** [bridgecrewio/checkov#3243]
**Describe the issue**
I am getting parsing errors on all my terraform files. I have recreated it with a very simple example.

**Examples**
File `test.tf`:

```
data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}
```

Command and output:

```
$ checkov -f test.tf --framework terraform --skip-download
       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.1.66

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /Users/shearn89/repos/tf-bug-report/test.tfֿ
```

**Version (please complete the following information):**
 - Checkov Version 2.1.66

**Additional context**
Further test to check I'm sane:

```
~
╰─ take testdir

~/testdir
╰─ vim test.tf

~/testdir
╰─ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v4.22.0...
- Installed hashicorp/aws v4.22.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

~/testdir
╰─ terraform validate
Success! The configuration is valid.


~/testdir
╰─ cat test.tf
data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}

~/testdir
╰─ checkov -f test.tf --framework terraform --skip-download

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.1.66

terraform scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 1

Error parsing file /Users/shearn89/testdir/test.tfֿ

```

**Comment by shearn89** [comment]
Debug log:

```
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Checkov version: 2.1.66
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Python executable: /Users/shearn89/.pyenv/versions/3.10.1/bin/python3.10
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Python version: 3.10.1 (main, Jan 24 2022, 14:30:24) [Clang 13.0.0 (clang-1300.0.29.30)]
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Checkov executable (argv[0]): /Users/shearn89/.pyenv/versions/3.10.1/bin/checkov
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Command Line Args:   -f test.tf --framework terraform --skip-download
Defaults:
  --branch:          master
  --download-external-modules:False
  --external-modules-download-path:.external_modules
  --evaluate-variables:True
  --secrets-scan-file-type:[]

2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Resultant set of frameworks (removing skipped frameworks): terraform
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  terraform_runner declares no system dependency checks required.
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  No API key found. Scanning locally only.
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Skipping downloading configs from platform
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Skipping prisma policy API call
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Filtered list of policies: []
2022-07-21 10:51:40,026 [MainThread  ] [DEBUG]  Filtered runners based on file type(s). Result: ['terraform']
2022-07-21 10:51:40,026 [MainThread  ] [INFO ]  Scanning root folder and producing fresh tf_definitions and context
2022-07-21 10:51:40,028 [MainThread  ] [DEBUG]  Parsing /Users/shearn89/testdir/test.tf
2022-07-21 10:51:40,034 [MainThread  ] [DEBUG]  failed while parsing file /Users/shearn89/testdir/test.tf
Traceback (most recent call last):
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 91, in _call_userfunc
    return f.visit_wrapper(f, tree.data, children, tree.meta)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 447, in _vargs_meta
    return f(children, meta)   # TODO swap these for consistency? Backwards incompatible!
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 427, in f
    return _f(self, *args, **kwargs)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/hcl2/transformer.py", line 108, in block
    args = self.strip_new_line_tokens(args)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/hcl2/transformer.py", line 248, in strip_new_line_tokens
    return [arg for arg in args if arg != "\n"]
TypeError: 'Meta' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/checkov/terraform/parser.py", line 742, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/hcl2/api.py", line 15, in load
    return loads(file.read())
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/hcl2/api.py", line 89, in loads
    return hcl2.parse(text + "\n")
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/hcl2/parser.py", line 51, in parse
    return DictTransformer().transform(tree)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 130, in transform
    return self._transform_tree(tree)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 125, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 116, in _transform_children
    yield self._transform_tree(c)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 126, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages/lark/visitors.py", line 97, in _call_userfunc
    raise VisitError(tree.data, tree, e)
lark.exceptions.VisitError: Error trying to process rule "block":

'Meta' object is not iterable
```

**Comment by gruebel** [comment]
hey @shearn89 thanks for reaching out. I tested it locally and I don't get any parsing issue. Could you run following command in the virtual env, where you installed `checkov`
```shell
> pip show lark

Name: lark
Version: 1.1.2
Summary: a modern parsing library
Home-page: https://github.com/lark-parser/lark
Author: Erez Shinan
Author-email: erezshin@gmail.com
License: MIT
Location: .../site-packages
Requires: 
Required-by: bc-python-hcl2, pycep-parser
```

**Comment by gruebel** [comment]
you can also try it with the docker container, if it works, then something is up with your venv
```shell
> docker run --tty --rm --volume /Users/shearn89/testdir:/tf --workdir /tf bridgecrew/checkov -d /tf
```

**Comment by shearn89** [comment]
Hi, thanks for responding. See output below:

```
╰─ pip show lark
Name: lark
Version: 1.1.2
Summary: a modern parsing library
Home-page: https://github.com/lark-parser/lark
Author: Erez Shinan
Author-email: erezshin@gmail.com
License: MIT
Location: /Users/shearn89/.pyenv/versions/3.10.1/lib/python3.10/site-packages
Requires:
Required-by: bc-python-hcl2, pycep-parser
```

Docker:

```
docker run --tty --rm --volume $(pwd):/tf --workdir /tf bridgecrew/checkov -d /tf
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested


       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.1.66
Update available 2.1.66 -> 2.1.67
Run pip3 install -U checkov to update
```

I'll check my virtual environment.

**Comment by shearn89** [comment]
Yep - that's solved it. I had to do a `pip freeze` and uninstall everything from the system, then recreate, and it's working now. Thanks!

**Comment by shearn89** [comment]
For future Googlers - not sure what the problem was but something had gone awry in my system environment. Consider this a warning to use virtualenvs for everything!

**Comment by gruebel** [comment]
Nice, great to hear you could work it out. @shearn89 I can also recommend you to give `pipx` a try, it creates for each tool you install a separate venv and you can easily update it without interfering with other tools https://github.com/pypa/pipx
