### ISSUE TITLE
Checkov crashed for "--compact" input parameter with "-o json -o junitxml" for multiple output

### ISSUE THREAD

**Issue by pandey-mohit** [bridgecrewio/checkov#3258]
**Describe the issue**
Checkov is crashing when we use `--compact` input parameter with `-o json -o junitxml` for multiple output.

**Examples**
To create a sample `json` file, follow this documentation.
https://learn.hashicorp.com/tutorials/terraform/aws-build?in=terraform/aws-get-started
https://www.checkov.io/7.Scan%20Examples/Terraform%20Plan%20Scanning.html
```
mkdir checkov-results
checkov -f tfplan.json --framework terraform_plan --skip-download -o json -o junitxml --output-file-path checkov-results --compact
```

**Exception Trace**
```
    },
    "summary": {
        "passed": 2,
        "failed": 4,
        "skipped": 0,
        "parsing_errors": 0,
        "resource_count": 0,
        "checkov_version": "2.1.70"
    },
    "url": "Add an api key '--bc-api-key <api-key>' to see more detailed insights via https://bridgecrew.cloud"
}

--- OUTPUT DELIMITER ---

Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 337, in run
    exit_code = runner_registry.print_reports(scan_reports, config, url=url, created_baseline_path=created_baseline_path, baseline=baseline)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 211, in print_reports
    test_suites = [
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 212, in <listcomp>
    report.get_test_suite(properties=properties, use_bc_ids=config.output_bc_ids)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/output/report.py", line 449, in get_test_suite
    output=self._create_test_case_failure_output(record)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/output/report.py", line 541, in _create_test_case_failure_output
    if record.code_block:
AttributeError: 'Record' object has no attribute 'code_block'
```

**Desktop (please complete the following information):**
 - OS: linux/mac
 - Checkov Version: 2.0.1223 & 2.1.70 (latest)

**Comment by gruebel** [comment]
hey @pandey-mohit thanks for reaching out. Looks like a bug sneaked into the code 😄 it results from the combination of using json output + compact. I will come up with a fix for it.
