### ISSUE TITLE
Issues installing checkov in Azure Pipelines

### ISSUE THREAD

**Issue by thepaulmacca** [bridgecrewio/checkov#3312]
I'm looking to use checkov to scan my helm charts, but when I add an `install checkov` task, I'm getting an error. Can someone help?

I'm using the MS hosted agents `ubuntu-latest`

This is what my task looks like, which has been taken from the [docs](https://www.checkov.io/2.Basics/Installing%20Checkov.html#install-on-ubuntu-1804-lts):

```yaml
- bash: |
    sudo apt update
    sudo apt install software-properties-common
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt install python3.7
    sudo apt install python3-pip
    sudo python3.7 -m pip install -U checkov
  displayName: Install checkov
```

This is the raw log from the pipeline run:

```yaml
2022-08-05T22:58:40.6126231Z ##[section]Starting: Install checkov
2022-08-05T22:58:40.6130822Z ==============================================================================
2022-08-05T22:58:40.6131027Z Task         : Bash
2022-08-05T22:58:40.6131207Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-08-05T22:58:40.6131399Z Version      : 3.201.1
2022-08-05T22:58:40.6131547Z Author       : Microsoft Corporation
2022-08-05T22:58:40.6131775Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-08-05T22:58:40.6132054Z ==============================================================================
2022-08-05T22:58:40.7322079Z Generating script.
2022-08-05T22:58:40.7343005Z ========================== Starting Command Output ===========================
2022-08-05T22:58:40.7354018Z [command]/usr/bin/bash /home/vsts/work/_temp/37a2df4a-3677-4739-85b7-25a36807c82c.sh
2022-08-05T22:58:40.7606092Z 
2022-08-05T22:58:40.7606888Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2022-08-05T22:58:40.7607255Z 
2022-08-05T22:58:40.8512099Z Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
2022-08-05T22:58:40.8513142Z Get:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
2022-08-05T22:58:40.8528708Z Get:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
2022-08-05T22:58:40.8644365Z Get:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
2022-08-05T22:58:40.9006190Z Get:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10.5 kB]
2022-08-05T22:58:40.9182843Z Hit:6 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
2022-08-05T22:58:41.0713607Z Get:7 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [2002 kB]
2022-08-05T22:58:41.1102096Z Get:8 http://azure.archive.ubuntu.com/ubuntu focal-updates/main Translation-en [360 kB]
2022-08-05T22:58:41.1144969Z Get:9 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [15.6 kB]
2022-08-05T22:58:41.1192695Z Get:10 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [1187 kB]
2022-08-05T22:58:41.1422329Z Get:11 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [169 kB]
2022-08-05T22:58:41.1481534Z Get:12 http://azure.archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [584 B]
2022-08-05T22:58:41.1501073Z Get:13 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [934 kB]
2022-08-05T22:58:41.1647690Z Get:14 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [210 kB]
2022-08-05T22:58:41.1683135Z Get:15 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [21.0 kB]
2022-08-05T22:58:41.1704604Z Get:16 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [24.4 kB]
2022-08-05T22:58:41.2163115Z Get:17 http://azure.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [588 B]
2022-08-05T22:58:41.3831055Z Get:18 http://azure.archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [45.6 kB]
2022-08-05T22:58:41.3860823Z Get:19 http://azure.archive.ubuntu.com/ubuntu focal-backports/main Translation-en [16.3 kB]
2022-08-05T22:58:41.3872965Z Get:20 http://azure.archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [1420 B]
2022-08-05T22:58:41.3918311Z Get:21 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [24.0 kB]
2022-08-05T22:58:41.3932706Z Get:22 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe Translation-en [16.0 kB]
2022-08-05T22:58:41.3967972Z Get:23 http://azure.archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [860 B]
2022-08-05T22:58:41.4821643Z Get:24 http://azure.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [1638 kB]
2022-08-05T22:58:41.5141652Z Get:25 http://azure.archive.ubuntu.com/ubuntu focal-security/main Translation-en [278 kB]
2022-08-05T22:58:41.5176869Z Get:26 http://azure.archive.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [10.8 kB]
2022-08-05T22:58:41.5214624Z Get:27 http://azure.archive.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [1103 kB]
2022-08-05T22:58:41.5378198Z Get:28 http://azure.archive.ubuntu.com/ubuntu focal-security/restricted Translation-en [157 kB]
2022-08-05T22:58:41.5410294Z Get:29 http://azure.archive.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [588 B]
2022-08-05T22:58:41.5460921Z Get:30 http://azure.archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [712 kB]
2022-08-05T22:58:41.5850269Z Get:31 https://packages.microsoft.com/ubuntu/20.04/prod focal/main arm64 Packages [31.2 kB]
2022-08-05T22:58:41.5969591Z Get:32 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [180 kB]
2022-08-05T22:58:41.6019826Z Get:33 http://azure.archive.ubuntu.com/ubuntu focal-security/universe Translation-en [129 kB]
2022-08-05T22:58:41.6033973Z Get:34 http://azure.archive.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [14.7 kB]
2022-08-05T22:58:41.6050216Z Get:35 http://azure.archive.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [22.2 kB]
2022-08-05T22:58:41.6060062Z Get:36 http://azure.archive.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [508 B]
2022-08-05T22:58:41.6385834Z Get:37 https://packages.microsoft.com/ubuntu/20.04/prod focal/main armhf Packages [23.7 kB]
2022-08-05T22:58:46.5330011Z Fetched 9674 kB in 2s (4932 kB/s)
2022-08-05T22:58:47.3841091Z Reading package lists...
2022-08-05T22:58:47.5237938Z Building dependency tree...
2022-08-05T22:58:47.5249745Z Reading state information...
2022-08-05T22:58:47.6066659Z 24 packages can be upgraded. Run 'apt list --upgradable' to see them.
2022-08-05T22:58:47.6159150Z 
2022-08-05T22:58:47.6159998Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2022-08-05T22:58:47.6160395Z 
2022-08-05T22:58:47.6691092Z Reading package lists...
2022-08-05T22:58:47.7964812Z Building dependency tree...
2022-08-05T22:58:47.7978939Z Reading state information...
2022-08-05T22:58:47.9360289Z software-properties-common is already the newest version (0.99.9.8).
2022-08-05T22:58:48.0082520Z 0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
2022-08-05T22:58:48.6015733Z  This PPA contains more recent Python versions packaged for Ubuntu.
2022-08-05T22:58:48.6016345Z 
2022-08-05T22:58:48.6017633Z Disclaimer: there's no guarantee of timely updates in case of security problems or other issues. If you want to use them in a security-or-otherwise-critical environment (say, on a production server), you do so at your own risk.
2022-08-05T22:58:48.6018227Z 
2022-08-05T22:58:48.6019350Z Update Note
2022-08-05T22:58:48.6019603Z ===========
2022-08-05T22:58:48.6019882Z Please use this repository instead of ppa:fkrull/deadsnakes.
2022-08-05T22:58:48.6020058Z 
2022-08-05T22:58:48.6020275Z Reporting Issues
2022-08-05T22:58:48.6020466Z ================
2022-08-05T22:58:48.6020554Z 
2022-08-05T22:58:48.6020789Z Issues can be reported in the master issue tracker at:
2022-08-05T22:58:48.6021075Z https://github.com/deadsnakes/issues/issues
2022-08-05T22:58:48.6021202Z 
2022-08-05T22:58:48.6021414Z Supported Ubuntu and Python Versions
2022-08-05T22:58:48.6021661Z ====================================
2022-08-05T22:58:48.6021773Z 
2022-08-05T22:58:48.6022293Z - Ubuntu 18.04 (bionic) Python2.3 - Python 2.6, Python 3.1 - Python 3.5, Python3.7 - Python3.11
2022-08-05T22:58:48.6022836Z - Ubuntu 20.04 (focal) Python3.5 - Python3.7, Python3.9 - Python3.11
2022-08-05T22:58:48.6023309Z - Ubuntu 22.04 (jammy) Python3.7 - Python3.9, Python3.11
2022-08-05T22:58:48.6023978Z - Note: Python2.7 (all), Python 3.6 (bionic), Python 3.8 (focal), Python 3.10 (jammy) are not provided by deadsnakes as upstream ubuntu provides those packages.
2022-08-05T22:58:48.6024259Z 
2022-08-05T22:58:48.6024581Z Why some packages aren't built:
2022-08-05T22:58:48.6025286Z - Note: for focal, older python versions require libssl<1.1 so they are not currently built
2022-08-05T22:58:48.6025939Z - Note: for jammy, older python versions requre libssl<3 so they are not currently built
2022-08-05T22:58:48.6026448Z - If you need these, reach out to asottile to set up a private ppa
2022-08-05T22:58:48.6026603Z 
2022-08-05T22:58:48.6026888Z The packages may also work on other versions of Ubuntu or Debian, but that is not tested or supported.
2022-08-05T22:58:48.6027099Z 
2022-08-05T22:58:48.6027262Z Packages
2022-08-05T22:58:48.6027435Z ========
2022-08-05T22:58:48.6027511Z 
2022-08-05T22:58:48.6028500Z The packages provided here are loosely based on the debian upstream packages with some modifications to make them more usable as non-default pythons and on ubuntu.  As such, the packages follow debian's patterns and often do not include a full python distribution with just `apt install python#.#`.  Here is a list of packages that may be useful along with the default install:
2022-08-05T22:58:48.6029064Z 
2022-08-05T22:58:48.6029478Z - `python#.#-dev`: includes development headers for building C extensions
2022-08-05T22:58:48.6029956Z - `python#.#-venv`: provides the standard library `venv` module
2022-08-05T22:58:48.6030448Z - `python#.#-distutils`: provides the standard library `distutils` module
2022-08-05T22:58:48.6031001Z - `python#.#-lib2to3`: provides the `2to3-#.#` utility as well as the standard library `lib2to3` module
2022-08-05T22:58:48.6031531Z - `python#.#-gdbm`: provides the standard library `dbm.gnu` module
2022-08-05T22:58:48.6031995Z - `python#.#-tk`: provides the standard library `tkinter` module
2022-08-05T22:58:48.6032144Z 
2022-08-05T22:58:48.6032465Z Third-Party Python Modules
2022-08-05T22:58:48.6032688Z ==========================
2022-08-05T22:58:48.6032786Z 
2022-08-05T22:58:48.6033667Z Python modules in the official Ubuntu repositories are packaged to work with the Python interpreters from the official repositories. Accordingly, they generally won't work with the Python interpreters from this PPA. As an exception, pure-Python modules for Python 3 will work, but any compiled extension modules won't.
2022-08-05T22:58:48.6034173Z 
2022-08-05T22:58:48.6034833Z To install 3rd-party Python modules, you should use the common Python packaging tools.  For an introduction into the Python packaging ecosystem and its tools, refer to the Python Packaging User Guide:
2022-08-05T22:58:48.6035306Z https://packaging.python.org/installing/
2022-08-05T22:58:48.6035430Z 
2022-08-05T22:58:48.6035597Z Sources
2022-08-05T22:58:48.6035767Z =======
2022-08-05T22:58:48.6035977Z The package sources are available at:
2022-08-05T22:58:48.6036232Z https://github.com/deadsnakes/
2022-08-05T22:58:48.6036339Z 
2022-08-05T22:58:48.6036507Z Nightly Builds
2022-08-05T22:58:48.6036703Z ==============
2022-08-05T22:58:48.6036788Z 
2022-08-05T22:58:48.6037097Z For nightly builds, see ppa:deadsnakes/nightly https://launchpad.net/~deadsnakes/+archive/ubuntu/nightly
2022-08-05T22:58:48.6037509Z  More info: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa
2022-08-05T22:58:48.7465432Z Hit:1 http://azure.archive.ubuntu.com/ubuntu focal InRelease
2022-08-05T22:58:48.7466503Z Hit:2 http://azure.archive.ubuntu.com/ubuntu focal-updates InRelease
2022-08-05T22:58:48.7467075Z Hit:3 http://azure.archive.ubuntu.com/ubuntu focal-backports InRelease
2022-08-05T22:58:48.7467587Z Hit:4 http://azure.archive.ubuntu.com/ubuntu focal-security InRelease
2022-08-05T22:58:48.7920888Z Hit:5 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
2022-08-05T22:58:48.8211396Z Get:6 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease [18.1 kB]
2022-08-05T22:58:48.8263303Z Hit:7 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu focal InRelease
2022-08-05T22:58:49.3044552Z Get:8 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 Packages [22.5 kB]
2022-08-05T22:58:49.3174585Z Get:9 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main Translation-en [5204 B]
2022-08-05T22:58:51.6801494Z Fetched 45.7 kB in 1s (68.3 kB/s)
2022-08-05T22:58:52.5192828Z Reading package lists...
2022-08-05T22:58:52.5467835Z 
2022-08-05T22:58:52.5468943Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2022-08-05T22:58:52.5469182Z 
2022-08-05T22:58:52.6008300Z Reading package lists...
2022-08-05T22:58:52.7299486Z Building dependency tree...
2022-08-05T22:58:52.7314370Z Reading state information...
2022-08-05T22:58:52.8732749Z The following additional packages will be installed:
2022-08-05T22:58:52.8735010Z   libpython3.7-minimal libpython3.7-stdlib python3.7-minimal
2022-08-05T22:58:52.8739050Z Suggested packages:
2022-08-05T22:58:52.8739511Z   python3.7-venv
2022-08-05T22:58:52.9254519Z The following NEW packages will be installed:
2022-08-05T22:58:52.9256438Z   libpython3.7-minimal libpython3.7-stdlib python3.7 python3.7-minimal
2022-08-05T22:58:52.9575171Z 0 upgraded, 4 newly installed, 0 to remove and 24 not upgraded.
2022-08-05T22:58:53.0025449Z Need to get 4530 kB of archives.
2022-08-05T22:58:53.0025873Z After this operation, 23.3 MB of additional disk space will be used.
2022-08-05T22:58:53.0026884Z Get:1 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 libpython3.7-minimal amd64 3.7.13-1+focal3 [588 kB]
2022-08-05T22:58:53.0341540Z Get:2 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 python3.7-minimal amd64 3.7.13-1+focal3 [1810 kB]
2022-08-05T22:58:53.0992972Z Get:3 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 libpython3.7-stdlib amd64 3.7.13-1+focal3 [1773 kB]
2022-08-05T22:58:53.1428382Z Get:4 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 python3.7 amd64 3.7.13-1+focal3 [359 kB]
2022-08-05T22:58:53.5462334Z Fetched 4530 kB in 0s (26.7 MB/s)
2022-08-05T22:58:53.5847725Z Selecting previously unselected package libpython3.7-minimal:amd64.
2022-08-05T22:58:53.6673266Z (Reading database ... 
2022-08-05T22:58:53.6673600Z (Reading database ... 5%
2022-08-05T22:58:53.6674094Z (Reading database ... 10%
2022-08-05T22:58:53.6674346Z (Reading database ... 15%
2022-08-05T22:58:53.6674573Z (Reading database ... 20%
2022-08-05T22:58:53.6674813Z (Reading database ... 25%
2022-08-05T22:58:53.6675047Z (Reading database ... 30%
2022-08-05T22:58:53.6675585Z (Reading database ... 35%
2022-08-05T22:58:53.6676084Z (Reading database ... 40%
2022-08-05T22:58:53.6676302Z (Reading database ... 45%
2022-08-05T22:58:53.6676546Z (Reading database ... 50%
2022-08-05T22:58:53.7184365Z (Reading database ... 55%
2022-08-05T22:58:53.7618274Z (Reading database ... 60%
2022-08-05T22:58:53.7971757Z (Reading database ... 65%
2022-08-05T22:58:53.8738398Z (Reading database ... 70%
2022-08-05T22:58:53.9353312Z (Reading database ... 75%
2022-08-05T22:58:53.9930543Z (Reading database ... 80%
2022-08-05T22:58:54.0578054Z (Reading database ... 85%
2022-08-05T22:58:54.1459267Z (Reading database ... 90%
2022-08-05T22:58:54.2396262Z (Reading database ... 95%
2022-08-05T22:58:54.2397117Z (Reading database ... 100%
2022-08-05T22:58:54.2397535Z (Reading database ... 230284 files and directories currently installed.)
2022-08-05T22:58:54.2460206Z Preparing to unpack .../libpython3.7-minimal_3.7.13-1+focal3_amd64.deb ...
2022-08-05T22:58:54.2504519Z Unpacking libpython3.7-minimal:amd64 (3.7.13-1+focal3) ...
2022-08-05T22:58:54.4142140Z Selecting previously unselected package python3.7-minimal.
2022-08-05T22:58:54.4308008Z Preparing to unpack .../python3.7-minimal_3.7.13-1+focal3_amd64.deb ...
2022-08-05T22:58:54.4366971Z Unpacking python3.7-minimal (3.7.13-1+focal3) ...
2022-08-05T22:58:54.6501730Z Selecting previously unselected package libpython3.7-stdlib:amd64.
2022-08-05T22:58:54.6662404Z Preparing to unpack .../libpython3.7-stdlib_3.7.13-1+focal3_amd64.deb ...
2022-08-05T22:58:54.6704114Z Unpacking libpython3.7-stdlib:amd64 (3.7.13-1+focal3) ...
2022-08-05T22:58:54.8574712Z Selecting previously unselected package python3.7.
2022-08-05T22:58:54.8788425Z Preparing to unpack .../python3.7_3.7.13-1+focal3_amd64.deb ...
2022-08-05T22:58:54.8810474Z Unpacking python3.7 (3.7.13-1+focal3) ...
2022-08-05T22:58:54.9506129Z Setting up libpython3.7-minimal:amd64 (3.7.13-1+focal3) ...
2022-08-05T22:58:54.9573395Z Setting up python3.7-minimal (3.7.13-1+focal3) ...
2022-08-05T22:58:55.3666568Z Setting up libpython3.7-stdlib:amd64 (3.7.13-1+focal3) ...
2022-08-05T22:58:55.3695245Z Setting up python3.7 (3.7.13-1+focal3) ...
2022-08-05T22:58:55.9837795Z Processing triggers for man-db (2.9.1-1) ...
2022-08-05T22:58:56.9589258Z Processing triggers for mime-support (3.64ubuntu1) ...
2022-08-05T22:58:58.5744057Z 
2022-08-05T22:58:58.5744716Z WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
2022-08-05T22:58:58.5744897Z 
2022-08-05T22:58:58.6284369Z Reading package lists...
2022-08-05T22:58:58.7589661Z Building dependency tree...
2022-08-05T22:58:58.7603958Z Reading state information...
2022-08-05T22:58:58.8981735Z python3-pip is already the newest version (20.0.2-5ubuntu1.6).
2022-08-05T22:58:58.9726215Z 0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
2022-08-05T22:58:59.1501026Z Traceback (most recent call last):
2022-08-05T22:58:59.1502043Z   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
2022-08-05T22:58:59.1502475Z     "__main__", mod_spec)
2022-08-05T22:58:59.1502854Z   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
2022-08-05T22:58:59.1503247Z     exec(code, run_globals)
2022-08-05T22:58:59.1504189Z   File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
2022-08-05T22:58:59.1504662Z     from pip._internal.cli.main import main as _main  # isort:skip # noqa
2022-08-05T22:58:59.1505326Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
2022-08-05T22:58:59.1505775Z     from pip._internal.cli.autocompletion import autocomplete
2022-08-05T22:58:59.1506404Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
2022-08-05T22:58:59.1506855Z     from pip._internal.cli.main_parser import create_main_parser
2022-08-05T22:58:59.1507506Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
2022-08-05T22:58:59.1507932Z     from pip._internal.cli import cmdoptions
2022-08-05T22:58:59.1508508Z   File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
2022-08-05T22:58:59.1508900Z     from distutils.util import strtobool
2022-08-05T22:58:59.1509401Z ModuleNotFoundError: No module named 'distutils.util'
2022-08-05T22:58:59.1608282Z ##[error]Bash exited with code '1'.
2022-08-05T22:58:59.1622829Z ##[section]Finishing: Install checkov
```

I was looking at running the container instead to save all this, but I'm not sure if that would work with scanning this helm chart, as I need to run `helm template` first, and point it to a custom `values.yaml` file (I'm scanning a chart that's consuming library chart templates). If someone's managed to do it, an example would be great, would be much easier

Any help appreciated

Thanks

**Comment by thepaulmacca** [comment]
I managed to fix this myself by adding the below to my pipeline, if it helps anyone:

```yaml
- bash: |
    pip3 install checkov
  displayName: Install checkov

- bash: |
    checkov \
      --directory ${{ parameters.chartPath }}${{ parameters.chartName }} \
      --framework helm \
      --var-file ${{ parameters.chartPath }}${{ parameters.chartName }}/environments/dev/values.yaml \
      --skip-check CKV_K8S_21 \
      --output junitxml \
      --soft-fail \
      > $(System.DefaultWorkingDirectory)/checkov-report.xml
  displayName: Run checkov scan
```
