### ISSUE TITLE
bridgecrew/checkov Docker container hangs without exiting since version 2.1.147/latest

### ISSUE THREAD

**Issue by KrylixZA** [bridgecrewio/checkov#3400]
**Describe the issue**
We have a CI/CD pipeline using `bridgecrew/checkov:latest` to run scans against our Helm charts in Azure DevOps. Since today, we've been experiencing issues where the pipeline successfully pulls the Docker image and then just hangs indefinitely, until the 1hr timeout is reached. We have locked our pipelines in to using `bridgecrew/checkov:2.1.146` and that appears to be working, so it seems to be specific to 2.1.147/latest.

**Examples**
Unfortunately, due to the usual company policy reasons, I can't share the full details. But a simple example of a failing scan could be:
1. Download and extract the MongoDB 13.0.1 Helm chart from <https://bitnami.com/stack/mongodb/helm>.
2. Navigate your CLI of choice into the extracted Helm chart.
3. Run the following command: `docker run -v ${PWD}:/helm bridgecrew/checkov:latest --directory /helm --framework helm`

You will observe the stack trace below:

**Exception Trace**
2022-08-23 09:18:15,498 [MainThread  ] [WARNI]  Error processing helm chart common at dir: /helm/charts/common. Working dir: /tmp/tmpaxr3z0on. Error details: Error: library charts are not installable

Process ForkProcess-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/parallelizer/parallel_runner.py", line 37, in func_wrapper
    result = original_func(item)
  File "/usr/local/lib/python3.8/site-packages/checkov/helm/runner.py", line 254, in <lambda>
    list(parallel_runner.run_function(lambda cd: Runner._convert_chart_to_k8s(cd, self.root_folder,
  File "/usr/local/lib/python3.8/site-packages/checkov/helm/runner.py", line 221, in _convert_chart_to_k8s
    o, _ = Runner._get_binary_output(chart_item, target_folder_path, helm_command, runner_filter)
TypeError: cannot unpack non-iterable NoneType object

**Desktop (please complete the following information):**
 - OS: Windows 11 (our pipelines are using Ubuntu 22.04 and we've replicated on Ubuntu 20.04)
 - Checkov 2.1.147 / latest

**Additional context**
N/A

**Comment by nimrodkor** [comment]
Thanks for reporting @KrylixZA !
We've released 2.1.148 which includes a revert to the bug introduced in 2.1.147, as you correctly identified. 
Let us know if this is still happening from 148 and onwards!

**Comment by KrylixZA** [comment]
Hey @nimrodkor - all is well in our world once again!

Thanks for the timely resolution. Appreciate your efforts!
