### ISSUE TITLE
Fresh install on RH7.x fails to execute any commands.

### ISSUE THREAD

**Issue by davidjeddy** [bridgecrewio/checkov#3708]
**Describe the issue**

checkov Python dependency problems on RH7.x

**Examples**

```sh
[ec2-user@rh7_9 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[ec2-user@rh7_9 ~]$ python --version
Python 2.7.5
[ec2-user@rh7_9 ~]$ python3 --version
Python 3.6.8
[ec2-user@rh7_9 ~]$ pip --version
-bash: pip: command not found
[ec2-user@rh7_9 ~]$ pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
[ec2-user@rh7_9 ~]$ which checkov
/usr/local/bin/checkov
```

**Exception Trace**

```sh
[ec2-user@rh7_9 ~]$ checkov --version
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/usr/local/lib/python3.6/site-packages/checkov/main.py", line 22, in <module>
    from checkov.terraform.plan_runner import Runner as tf_plan_runner
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/plan_runner.py", line 11, in <module>
    from checkov.terraform.context_parsers.registry import parser_registry
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/context_parsers/__init__.py", line 1, in <module>
    from checkov.terraform.context_parsers.parsers import *
  File "/usr/local/lib/python3.6/site-packages/checkov/terraform/context_parsers/parsers/provider_context_parser.py", line 1, in <module>
    import hcl2
  File "/usr/local/lib/python3.6/site-packages/hcl2/__init__.py", line 5, in <module>
    from .api import load, loads
  File "/usr/local/lib/python3.6/site-packages/hcl2/api.py", line 5, in <module>
    from hcl2.parser import hcl2, strip_line_comment
  File "/usr/local/lib/python3.6/site-packages/hcl2/parser.py", line 78, in <module>
    hcl2 = Lark_StandAlone(transformer=DictTransformer())
  File "/usr/local/lib/python3.6/site-packages/hcl2/lark_parser.py", line 8, in Lark_StandAlone
    return Lark._load_from_dict(DATA, MEMO, **kwargs)
AttributeError: type object 'Lark' has no attribute '_load_from_dict'
```

**Desktop (please complete the following information):**
 - OS: RH 7.9
 - Checkov Version 2.x

**Comment by gruebel** [comment]
hey @davidjeddy thanks for reaching out. We don't support Python 3.6 and we won't change that, because it is officially EOL.
