### ISSUE TITLE
helm scans failure after image version 2.1.150

### ISSUE THREAD

**Issue by stevieg27** [bridgecrewio/checkov#3730]
**Describe the issue**
 I am currently using checkov via gitlab pipeline for helm scans. It was working fine before the version `2.1.151` but after that it is not scanning the helm charts resulting in empty results. Looks like the issue started after this change https://github.com/bridgecrewio/checkov/pull/3403 . 

**Logs of non working one all images after 2.150.0**

[DEBUG] Ran helm command to get dependency output. Chart: test1. dir: /tmp/tmph7gxe6_4. Output: WARNING: no dependencies at prototype/charts/test1/charts
 [INFO ]  Error parsing output test at dir: ./test/charts/test1. Working dir: /tmp/tmph7gxe6_4//test/charts/.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/checkov/helm/runner.py", line 268, in _convert_chart_to_k8s
    Runner._parse_output(target_dir, o)
  File "/usr/local/lib/python3.8/site-packages/checkov/helm/runner.py", line 131, in _parse_output
    output_str = str(output, 'utf-8')
TypeError: decoding to str: need a bytes-like object, NoneType found
2022-10-19 18:15:51,320 [MainThread  ] [INFO ]  creating Kubernetes graph
2022-10-19 18:15:51,320 [MainThread  ] [INFO ]  Successfully created Kubernetes graph
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Loading external checks from /usr/local/lib/python3.8/site-packages/checkov/helm/checks/graph_checks
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Getting exit code for report helm
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Soft fail severity threshold: None
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Soft fail checks: []
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Hard fail severity threshold: None
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Hard fail checks: []
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  Use enforcement rules is FALSE
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  In get_exit_code; exit code thresholds: {'soft_fail': False, 'soft_fail_checks': [], 'soft_fail_threshold': None, 'hard_fail_checks': [], 'hard_fail_threshold': None}, hard_fail_on_parsing_errors: False
2022-10-19 18:15:51,321 [MainThread  ] [DEBUG]  No failed checks, or soft_fail is True and soft_fail_on and hard_fail_on are empty - returning 0
2022-10-19 18:15:51,366 [MainThread  ] [INFO ]  
Wrote output in cli format to the file './results_cli.txt')
2022-10-19 18:15:51,366 [MainThread  ] [INFO ]  
Wrote output in junitxml format to the file './results_junitxml.xml')
2022-10-19 18:15:51,366 [MainThread  ] [INFO ]  
Wrote output in json format to the file './results_json.json')

**Logs of  working one of images before 2.150.0**

 [DEBUG]  Ran helm command to get dependency output. Chart: test1. dir: /tmp/tmpvv5i5qo6//prototype/charts/. Output: WARNING: no dependencies at prototype/charts/test1/charts

[DEBUG]  Ran helm command to template chart output. Chart: test1. dir: /tmp/tmpvv5i5qo6//prototype/charts/. Output: ---
Source: test1/templates/config-map.yaml

Please help me to debug this.

**Comment by 4111-619** [comment]
Same issue. Additionally, the same version is working fine with CLI, But not working while running in gitlabCI. Please help. Thanks
