### ISSUE TITLE
security_groups in aws_security_group rule not supported

### ISSUE THREAD

**Issue by jglapa** [bridgecrewio/checkov#38]
**Describe the bug**
referencing a `security_group` instead of `cidr_block` in a security group rule causes an exception

**To Reproduce**
1. try to run checkov on the following resource:
```tf
resource "aws_security_group" "bar-sg" {
  name        = "sg-bar"
  vpc_id      = aws_vpc.main.id

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    security_groups = [aws_security_group.foo-sg.id]
    description = "foo"
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }

}

```
result:
```
Traceback (most recent call last):
  File "/path/tf-checks/bin/checkov", line 34, in <module>
    report = Runner().run(root_folder, external_checks_dir=args.external_checks_dir)
  File "/path/tf-checks/lib/python3.7/site-packages/checkov/terraform/runner.py", line 38, in run
    results = resource_registry.scan(resource, scanned_file, skipped_checks)
  File "/pathtf-checks/lib/python3.7/site-packages/checkov/terraform/checks/resource/registry.py", line 38, in scan
    resource_name=resource_name, resource_type=resource, skip_info=skip_info)
  File "/path/tf-checks/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_check.py", line 31, in run
    check_result['result'] = self.scan_resource_conf(resource_configuration)
  File "/path/tf-checks/lib/python3.7/site-packages/checkov/terraform/checks/resource/aws/SecurityGroupUnrestrictedIngress22.py", line 25, in scan_resource_conf
    if rule['from_port'] == [PORT] and rule['to_port'] == [PORT] and rule['cidr_blocks'] == [[
KeyError: 'cidr_blocks'
```

**Expected behavior**
such resource definition is perfectly valid

**Desktop (please complete the following information):**
 - OS: Ubuntu `19.10`
 - Python: `3.7.5`
 - Checkov Version  `1.0.99`

**Comment by schosterbarak** [comment]
@jglapa  Thank you for reporting this bug. 
Just pushed a fix :)
