### ISSUE TITLE
Checkov does not do the checks and throws exception when the resource properties in the ARM template are assigned a value based on some logic

### ISSUE THREAD

**Issue by gyuvaraj10** [bridgecrewio/checkov#3844]
**Describe the issue**
Checkov does not do the checks and throws exception when the resource properties in the ARM template are assigned a value based on some logic

**Example Value**

ARM template:
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "applicationgateway_location_shortname": {
        "defaultValue": "",
        "type": "String",
        "maxLength": 3
      },
      "applicationgateway_platform": {
        "defaultValue": "",
        "type": "String",
        "maxLength": 6
      },
      "applicationgateway_project": {
        "defaultValue": "",
        "type": "String",
        "maxLength": 6
      },
      "applicationgateway_environment": {
        "defaultValue": "",
        "type": "String",
        "maxLength": 7
      },
      "applicationgateway_uniqueid": {
        "defaultValue": "1",
        "type": "String",
        "maxLength": 1
      },
      "location": {
        "type": "string",
        "defaultValue": "[resourceGroup().location]",
        "metadata": {
          "description": "Location for resources."
        }
      },
      "applicationGatewayTier": {
        "type": "string",
        "allowedValues": [
          "Standard_v2",
          "WAF_v2"
        ],
        "defaultValue": "WAF_v2",
        "metadata": {
          "description": "application gateway tier"
        }
      }
    },
    "variables": {
      "basename": "[concat(parameters('applicationgateway_platform'), '-', parameters('applicationgateway_project'), '-', parameters('applicationgateway_location_shortname'), '-', parameters('applicationgateway_environment'))]",
      "applicationGatewayName": "[concat(variables('basename'), '-ag-', parameters('applicationgateway_uniqueid'))]",
      "publicIPAddressName": "[concat(variables('basename'),'-agip-',parameters('applicationgateway_uniqueid'))]",
      "publicIPRef": "[resourceId('Microsoft.Network/publicIPAddresses',variables('publicIPAddressName'))]",
      "webApplicationFirewallConfigurationProperties": {
        "enabled": true,
        "firewallMode": "Detection",
        "ruleSetType": "OWASP",
        "ruleSetVersion": "3.0",
        "requestBodyCheck": true,
        "maxRequestBodySizeInKb": 128,
        "fileUploadLimitInMb": 100
      },
      "apiVersion": "2020-07-01"
    },
    "resources": [
      {
        "apiVersion": "[variables('apiVersion')]",
        "name": "[variables('applicationGatewayName')]",
        "type": "Microsoft.Network/applicationGateways",
        "location": "[parameters('location')]",
        "dependsOn": [
          "[variables('publicIPRef')]"
        ],
        "properties": {
          "sku": {
            "name": "[parameters('applicationGatewayTier')]",
            "tier": "[parameters('applicationGatewayTier')]"
          },
          "webApplicationFirewallConfiguration": "[if(equals(toUpper(parameters('applicationGatewayTier')), 'WAF_V2'), variables('webApplicationFirewallConfigurationProperties'), json('null'))]"
        }
      }
    ]
  }
```

Custom Check:
```python
from checkov.arm.base_resource_check import BaseResourceCheck
from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.common.util.type_forcers import force_int


class AGwebApplicationFirewallConfigurationEnabled(BaseResourceCheck):

    def __init__(self):
        name = "Web Application Firewall (WAF) should be enabled for Application Gateway"
        id = "CKV_AZURE_58"
        supported_resources = ['Microsoft.Network/applicationGateways']
        categories = [CheckCategories.NETWORKING]
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf):
        if "apiVersion" in conf:
            year = force_int(conf["apiVersion"][0:4])
            if year is None:
                return CheckResult.UNKNOWN
            elif year < 2017:
                return CheckResult.FAILED
        if "properties" in conf:
            if "webApplicationFirewallConfiguration" in conf["properties"]:
                if (str(conf["properties"]["webApplicationFirewallConfiguration"]["enabled"]).lower()=="true"):
                    return CheckResult.PASSED
        return CheckResult.FAILED
check = AGwebApplicationFirewallConfigurationEnabled()
```

Output:
```shell
vscode ➜ /workspaces/alright-chinchilla $ checkov -d . --framework arm --external-checks-dir checks
[ arm framework ]:   0%|                    |[0/4], Current File Scanned=../../ag.template.json2022-11-11 06:30:07,467 [MainThread  ] [ERROR]  Failed to run check: Web Application Firewall (WAF) should be enabled for Application Gateway for configuration: {'apiVersion': '2020-07-01', 'name': "[concat(variables('basename'), '-ag-', parameters('applicationgateway_uniqueid'))]", 'type': 'Microsoft.Network/applicationGateways', 'location': '[resourceGroup().location]', 'dependsOn': ["[variables('publicIPRef')]"], 'properties': {'sku': {'name': 'WAF_v2', 'tier': 'WAF_v2', '__startline__': 75, '__endline__': 78}, 'webApplicationFirewallConfiguration': "[if(equals(toUpper(parameters('applicationGatewayTier')), 'WAF_V2'), variables('webApplicationFirewallConfigurationProperties'), json('null'))]", '__startline__': 74, '__endline__': 80}, '__startline__': 66, '__endline__': 81} at file: /ag.template.json
Traceback (most recent call last):
  File "/home/vscode/.local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/main.py", line 330, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 79, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/arm/runner.py", line 116, in run
    results = arm_resource_registry.scan(arm_file, {resource_name: resource}, skipped_checks,
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/common/checks/base_check_registry.py", line 127, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/common/checks/base_check_registry.py", line 141, in run_check
    result = check.run(
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/common/checks/base_check.py", line 71, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/arm/base_resource_check.py", line 52, in scan_entity_conf
    return self.scan_resource_conf(conf, entity_type)
  File "/home/vscode/.local/lib/python3.10/site-packages/checkov/arm/base_resource_check.py", line 64, in wrapper
    return wrapped(self, conf)
  File "/workspaces/alright-chinchilla/checks/test_ag_check.py", line 24, in scan_resource_conf
    if (str(conf["properties"]["webApplicationFirewallConfiguration"]["enabled"]).lower()=="true"):
TypeError: string indices must be integers
[ arm framework ]:   0%|                    |[0/4], Current File Scanned=../../ag.template.json
```

**Comment by gyuvaraj10** [comment]
@gruebel , @mikeurbanski1  please confirm if this feature is available.

**Comment by gruebel** [comment]
hey @gyuvaraj10 thanks for reaching out. Currently we don't support such a use case in ARM templates. We call it variable rendering and to do it technically we first need to create a resource graph, which we don't have for ARM.

**Comment by gyuvaraj10** [comment]
Is there is way for me to do it? or any suggestions to validate the template in this case?

**Comment by gruebel** [comment]
nothing in particular. you can just check, if you can't find `enabled` then return either fail, pass or unknown
```python
        if "properties" in conf:
            if "webApplicationFirewallConfiguration" in conf["properties"]:
                if "enabled" not in conf["properties"]["webApplicationFirewallConfiguration"]:
                    return CheckResult.UNKNOWN
                if (str(conf["properties"]["webApplicationFirewallConfiguration"]["enabled"]).lower()=="true"):
                    return CheckResult.PASSED
```
even when we start to implement a graph for ARM your use case won't be supported for a while. You reference a parameter and variable, use two different functions and an if condition.
