### ISSUE TITLE
Failing version checkov-action@v12.1886.0 for framework github_actions

### ISSUE THREAD

**Issue by magnus-fors** [bridgecrewio/checkov#3942]
Framework github_actions started to fail in version v12.1886.0 (version v12.1885.0 works fine).
```
Run bridgecrewio/checkov-action@v12.1886.0
  with:
    directory: .github/workflows
    quiet: true
    framework: github_actions
    skip_check: CKV_GHA_7
    output_format: sarif
    log_level: WARNING
    container_user: 0
  env:
    CHECKOV_RESULTS: 
         _               _              
     ___| |__   ___  ___| | _______   __
    / __| '_ \ / _ \/ __| |/ / _ \ \ / /
   | (__| | | |  __/ (__|   < (_) \ V / 
    \___|_| |_|\___|\___|_|\_\___/ \_/  
                                        
  By bridgecrew.io | version: 2.2.95 
  dockerfile scan results:
  
  Passed checks: 47, Failed checks: 0, Skipped checks: 1
```
Fails with the falling call stack:
```
running checkov on directory: .github/workflows
checkov -d .github/workflows  --skip-check CKV_GHA_7  --quiet   --output sarif        --framework github_actions  
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 3[40](https://github.com/axteams-vms/cloud-storage/actions/runs/3549000828/jobs/5960853416#step:7:41), in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 80, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/github_actions/runner.py", line 109, in run
    report = super().run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/object_runner.py", line 1[45](https://github.com/axteams-vms/cloud-storage/actions/runs/3549000828/jobs/5960853416#step:7:46), in run
    self.add_python_check_results(
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/object_runner.py", line 190, in add_python_check_results
    resource=self.get_resource(file_path, key, check.supported_entities, start, end),  # type:ignore[arg-type]  # key is str not BaseCheck
  File "/usr/local/lib/python3.8/site-packages/checkov/github_actions/runner.py", line 96, in get_resource
    step_name = resolve_step_name(definition['jobs'][job_name], start_line, end_line)
KeyError: ''
```

**Comment by marynaKK** [comment]
@magnus-fors , Although I added a potential fix, I couldn't reproduce the error too. 
So this issue is still not solved...

**Comment by magnus-fors** [comment]
@gruebel Below you find the workflow file
```
name: IaC static code analysis

on:
  workflow_call:

jobs:
  validate-iac:
    runs-on: ubuntu-latest
    name: validate-iac
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Run Checkov on bicep files
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infrastructure/azure/
          soft_fail: true # since we have failed checks
          quiet: true
          framework: bicep
          skip_check: CKV_AZURE_14,CKV_AZURE_15,CKV_AZURE_16,CKV_AZURE_17,CKV_AZURE_18

      - name: Run Checkov on Dockerfiles
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./
          quiet: true
          framework: dockerfile
          skip_check: CKV_DOCKER_2

      - name: Run Checkov on Github Actions workflow files
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .github/workflows
          quiet: true
          framework: github_actions
          skip_check: CKV_GHA_7

      - name: Run Checkov on Terraform Github repository settings files
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: infrastructure/github
          quiet: true
          framework: terraform

```

**Comment by magnus-fors** [comment]
@gruebel @marynaKK I just tried the latest version 2.2.99 and it solved the issue. Thanks a lot for the help!

**Comment by gruebel** [comment]
great and thanks for testing it.
