### ISSUE TITLE
Checkov scan is failing : An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by pravindhawas** [bridgecrewio/checkov#3963]
When I am running running checkov scan locally. It is failing with below error. Can someone please help me with this?

C:\Users\abc\> checkov -f terraform.json --repo-root-for-plan-enrichment . --download-external-modules true
2022-11-30 18:56:29,789 [MainThread  ] [WARNI]  Failed to get the checkov mappings and guidelines from https://www.bridgecrew.cloud/api/v1/guidelines. Skips using BC_* IDs will not work.
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Program Files\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Program Files\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\checkov\common\bridgecrew\platform_integration.py", line 678, in get_public_run_config
    request = self.http.request("GET", self.guidelines_api_url, headers=headers)  # type:ignore[no-untyped-call]
  File "C:\Program Files\Python39\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\poolmanager.py", line 533, in urlopen
    return super(ProxyManager, self).urlopen(method, url, redirect=redirect, **kw)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bridgecrew.cloud', port=443): Max retries exceeded with url: /api/v1/guidelines (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))
[ kubernetes framework ]: 100%|████████████████████|[1/1], Current File Scanned=terraform.json
[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=terraform.json
[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=terraform.json
       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.2.106

**Version (please complete the following information):**
 - Checkov Version 2.2.106

**Comment by gruebel** [comment]
hey @pravindhawas thanks for reaching out. It looks like something is blocking the connection to our API endpoint. Can you open the UR https://www.bridgecrew.cloud/api/v1/guidelines on your computer? Are you using some kind of proxy?

**Comment by pravindhawas** [comment]
I can open the URL on my computer. Yes we have some proxy.
![image](https://user-images.githubusercontent.com/109735096/205016210-a26363c5-0f86-4e98-992f-013a7654b1b0.png)

**Comment by jaskaransinghdr6j** [comment]
Facing the same issue.

**Comment by pravindhawas** [comment]
We have whitelisted bridgecrew base URL in proxy and its working
