### ISSUE TITLE
Parsing Error on Custom Providers

### ISSUE THREAD

**Issue by jaskaransinghdr6j** [bridgecrewio/checkov#3999]
**Describe the issue**
With a terraform provider which has a DOT `.` in the name, checkov fails to parse the providers block.

**Examples**
`providers {
    aws.us-east-1 = "aws.us-east-1"
    ...
    }`
 
 2022-12-06 16:55:36,729 [MainThread  ] [DEBUG]  failed while parsing file /Users/jaskaransingh/Documents/Code/<REDACTED>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 126, in feed_token
    action, arg = states[state][token.type]
KeyError: 'DOT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/checkov/terraform/parser.py", line 741, in _load_or_die_quietly
    raw_data = hcl2.load(f)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hcl2/api.py", line 15, in load
    return loads(file.read())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hcl2/api.py", line 89, in loads
    return hcl2.parse(text + "\n")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/hcl2/parser.py", line 50, in parse
    tree = Hcl2.lark_parser.parse(text)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/lark.py", line 645, in parse
    return self.parser.parse(text, start=start, on_error=on_error)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parser_frontends.py", line 96, in parse
    return self.parser.parse(stream, chosen_start, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 41, in parse
    return self.parser.parse(lexer, start)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 171, in parse
    return self.parse_from_state(parser_state)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 188, in parse_from_state
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 179, in parse_from_state
    state.feed_token(token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lark/parsers/lalr_parser.py", line 129, in feed_token
    raise UnexpectedToken(token, expected, state=self, interactive_parser=None)
lark.exceptions.UnexpectedToken: Unexpected token Token('DOT', '.') at line 55, column 8.
Expected one of: 
	* EQUAL
	* LBRACE
	* __ANON_0
	* STRING_LIT
 
**Version (please complete the following information):**
 - Checkov Version 2.2.116

**Comment by jaskaransinghdr6j** [comment]
Apparently a valid provider name having a DOT (".") is not parsed correctly, eg. `aws.us-east-1`

**Comment by gruebel** [comment]
hey @jaskaransinghdr6j thanks for reaching out. Can you share the Terraform template snippet, where you leverage this syntax.

**Comment by jaskaransinghdr6j** [comment]
Here is the snippet from main.tf

`providers = {
    aws = "aws.us-east-1"
    aws.us-east-1 = "aws.us-east-1"
    aws.us-west-1 = "aws.us-west-1"
    aws.us-west-2 = "aws.us-west-2"
    dukakis       = "dukakis"
  }`

**Comment by gruebel** [comment]
I still can't reproduce it. I tried it with this example and all is good
```hcl
module "aws_vpc" {
  source = "./aws_vpc"
  providers = {
    aws = "aws.us-east-1"
    aws.us-east-1 = "aws.us-east-1"
    aws.us-west-1 = "aws.us-west-1"
    aws.us-west-2 = "aws.us-west-2"
    dukakis = "dukakis"
  }
}
```
