### ISSUE TITLE
LegacyVersion dropped from packaging in version 22 causing checkov to fail

### ISSUE THREAD

**Issue by gone-for-coding** [bridgecrewio/checkov#4022]
**Describe the issue**
LegacyVersion dropped from packaging in version 22 causing checkov to fail.

```console
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/main.py", line 20, in <module>
    from checkov.argo_workflows.runner import Runner as argo_workflows_runner
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/argo_workflows/runner.py", line 7, in <module>
    from checkov.common.images.image_referencer import ImageReferencer, Image
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/images/image_referencer.py", line 12, in <module>
    from checkov.common.bridgecrew.vulnerability_scanning.image_scanner import image_scanner
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/bridgecrew/vulnerability_scanning/image_scanner.py", line 15, in <module>
    from checkov.common.bridgecrew.vulnerability_scanning.integrations.docker_image_scanning import \
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/bridgecrew/vulnerability_scanning/integrations/docker_image_scanning.py", line 8, in <module>
    from checkov.common.bridgecrew.vulnerability_scanning.integrations.twistcli import TwistcliIntegration
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/bridgecrew/vulnerability_scanning/integrations/twistcli.py", line 11, in <module>
    from checkov.common.bridgecrew.platform_integration import bc_integration
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/bridgecrew/platform_integration.py", line 31, in <module>
    from checkov.common.bridgecrew.wrapper import reduce_scan_reports, persist_checks_results, \
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/bridgecrew/wrapper.py", line 13, in <module>
    from checkov.common.util.json_utils import CustomJSONEncoder
  File "/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/checkov/common/util/json_utils.py", line 6, in <module>
    from packaging.version import LegacyVersion, Version
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/root/.cache/pre-commit/repocfmpcwt0/py_env-python3/lib/python3.8/site-packages/packaging/version.py)
```

**Additional context**

https://github.com/bridgecrewio/checkov/blob/main/checkov/common/util/json_utils.py#L6

See here:
https://github.com/pypa/packaging/releases
and here:
https://github.com/pypa/packaging/pull/407
and here:

**Comment by gone-for-coding** [comment]
Ah I just saw somebody took care of it. So waiting for the next release.

https://github.com/bridgecrewio/checkov/commit/6ed144eda06523f303cd0602b8fa5e62bd65c136
