### ISSUE TITLE
Installation issue - Python module incompatibilities

### ISSUE THREAD

**Issue by davidfordaus** [bridgecrewio/checkov#4053]
**Environment:**
Pip 22.3.1
Python 3.8.2
Windows 10

**Repro steps:**

1. Create a VENV
2. Pip  install checkov
3. Receive the following error messages in the Pip log:

**Error**
ERROR: requests 2.28.1 has requirement charset-normalizer<3,>=2, but you'll have charset-normalizer 3.0.1 which is incompatible.
ERROR: aiohttp 3.8.3 has requirement charset-normalizer<3.0,>=2.0, but you'll have charset-normalizer 3.0.1 which is incompatible.

**Further error (running)**
Running Checkov after this as "checkov" has this error:
Traceback (most recent call last):
  File "C:\Git_Dentons_Pipeline_Dev\Environments_Shared\Common\Terraform\checkov\Scripts\checkov.cmd", line 37, in <module>
    from checkov.main import run
ImportError: No module named checkov.main

C:\Git_Dentons_Pipeline_Dev\Environments_Shared\Common\Terraform>checkov\Scripts\activate

**pip install checkov**
```
Collecting checkov
  Using cached https://files.pythonhosted.org/packages/87/c0/e9dc3e0078f563b78915ee25431dd17490a24ee4628653483b7442877db6/checkov-2.2.139-py3-none-any.whl
Collecting importlib-metadata>=0.12 (from checkov)
  Using cached https://files.pythonhosted.org/packages/e1/16/1f59f5d87d256012e9cdf0e8af8810965fa253e835cfecce64f4b11d4f2d/importlib_metadata-5.1.0-py3-none-any.whl
Collecting packageurl-python (from checkov)
  Using cached https://files.pythonhosted.org/packages/c8/1a/bbe90b213ed5f22bf09a59a633bd4a58b0034df819f1eedd432618f947bf/packageurl_python-0.10.4-py3-none-any.whl
Collecting charset-normalizer (from checkov)
  Downloading https://files.pythonhosted.org/packages/87/5d/0ebaee2249a04fd20bb4baeb9ea2c29dee17317175d9d67b4f5f34cf048d/charset_normalizer-3.0.1-cp38-cp38-win_amd64.whl (95kB)
     |████████████████████████████████| 102kB 3.2MB/s
Collecting jsonpath-ng (from checkov)
  Using cached https://files.pythonhosted.org/packages/4c/b7/3627068d9aa6b2d49af117eb3897770a5dbc6bb3f4c09ed56a9eb749438e/jsonpath_ng-1.5.3-py3-none-any.whl
Collecting cloudsplaining>=0.4.3 (from checkov)
  Using cached https://files.pythonhosted.org/packages/46/c3/8ae4da8073d9fd019c08de078cad6a528e3420e87d3720aa6ef17fe895a4/cloudsplaining-0.5.0-py3-none-any.whl
Collecting gitpython (from checkov)
  Using cached https://files.pythonhosted.org/packages/1f/d3/020efb312a7d25fa00e144497a33378d415552e5581be080a99017af6d39/GitPython-3.1.29-py3-none-any.whl
Collecting dpath<2,>=1.5.0 (from checkov)
  Using cached https://files.pythonhosted.org/packages/88/b2/abc5803f37a2ea1045d68765acfcb4ec166bc9e08c3ba451c53af29a73f2/dpath-1.5.0.tar.gz
Collecting tabulate (from checkov)
  Using cached https://files.pythonhosted.org/packages/40/44/4a5f08c96eb108af5cb50b41f76142f0afa346dfa99d5296fe7202a11854/tabulate-0.9.0-py3-none-any.whl
Collecting networkx<2.7 (from checkov)
  Using cached https://files.pythonhosted.org/packages/e9/93/aa6613aa70d6eb4868e667068b5a11feca9645498fd31b954b6c4bb82fa5/networkx-2.6.3-py3-none-any.whl
Collecting typing-extensions>=4.1.0 (from checkov)
  Using cached https://files.pythonhosted.org/packages/0b/8e/f1a0a5a76cfef77e1eb6004cb49e5f8d72634da638420b9ea492ce8305e8/typing_extensions-4.4.0-py3-none-any.whl
Collecting deep-merge (from checkov)
  Using cached https://files.pythonhosted.org/packages/e0/07/94e20c6407d93bb7800cf316762d64a6c9fb7b76a1163f90a7af4c3ae1da/deep_merge-0.0.4-py3-none-any.whl
Collecting bc-python-hcl2==0.3.47 (from checkov)
  Using cached https://files.pythonhosted.org/packages/34/c1/0341c37365ba64724a18be6a7a7919daf04e91a5efe3639fa26e45b6b1b8/bc_python_hcl2-0.3.47-py3-none-any.whl
Collecting schema (from checkov)
  Using cached https://files.pythonhosted.org/packages/0d/93/ca8aa5a772efd69043d0a745172d92bee027caa7565c7f774a2f44b91207/schema-0.7.5-py2.py3-none-any.whl
Collecting dockerfile-parse (from checkov)
  Using cached https://files.pythonhosted.org/packages/53/83/e9579a25c26bc8e1a6033e46e756e18c25caa05bfc421673d99d1af2efab/dockerfile_parse-1.2.0-py2.py3-none-any.whl
Collecting termcolor (from checkov)
  Downloading https://files.pythonhosted.org/packages/c3/23/16f4cdb09368524cd7cf47c2950663dd197a6c180cd5b6db01dcb65c5135/termcolor-2.1.1-py3-none-any.whl
Collecting argcomplete (from checkov)
  Using cached https://files.pythonhosted.org/packages/d3/e5/c5509683462e51b070df9e83e7f72c1ccfe3f733f328b4a0f06804c27278/argcomplete-2.0.0-py2.py3-none-any.whl
Collecting cyclonedx-python-lib<4.0.0,>=2.4.0 (from checkov)
  Using cached https://files.pythonhosted.org/packages/a3/1b/11f644be65acd165ad1e86b0a114e42110bed95529955ca8671c1257321a/cyclonedx_python_lib-3.1.1-py3-none-any.whl
Collecting packaging==21.3 (from checkov)
  Using cached https://files.pythonhosted.org/packages/05/8e/8de486cbd03baba4deef4142bd643a3e7bbe954a784dc1bb17142572d127/packaging-21.3-py3-none-any.whl
Collecting policyuniverse (from checkov)
  Using cached https://files.pythonhosted.org/packages/10/ea/4213c880a0c37a929faab0d3628863532557d727b4974e40a427fbc40ac9/policyuniverse-1.5.0.20220613-py2.py3-none-any.whl
Collecting prettytable>=3.0.0 (from checkov)
  Using cached https://files.pythonhosted.org/packages/fa/4c/9b2bbb92a14a09ed929afa40282c088d8e50f79303eb3873fbeba1d96e89/prettytable-3.5.0-py3-none-any.whl
Collecting colorama (from checkov)
  Using cached https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl
Collecting aiomultiprocess (from checkov)
  Using cached https://files.pythonhosted.org/packages/e6/fa/bfbf06b737de39a0585c169b132a0cbd735b4db23b4bcfd5daa52b0c7562/aiomultiprocess-0.9.0-py3-none-any.whl
Collecting pycep-parser==0.3.9 (from checkov)
  Using cached https://files.pythonhosted.org/packages/6c/3f/9ffd924259661c0f6e3508856b969a03dc1f6ce118de2080e399aaf82656/pycep_parser-0.3.9-py3-none-any.whl
Collecting requests>=2.26.0 (from checkov)
  Downloading https://files.pythonhosted.org/packages/ca/91/6d9b8ccacd0412c08820f72cebaa4f0c0441b5cda699c90f618b6f8a1b42/requests-2.28.1-py3-none-any.whl (62kB)
     |████████████████████████████████| 71kB 4.8MB/s
Collecting configargparse (from checkov)
  Using cached https://files.pythonhosted.org/packages/af/cb/2a6620656f029b7b49c302853b433fac2c8eda9cbb5a3bc70b186b1b5b90/ConfigArgParse-1.5.3-py3-none-any.whl
Collecting cachetools (from checkov)
  Downloading https://files.pythonhosted.org/packages/68/aa/5fc646cae6e997c3adf3b0a7e257cda75cff21fcba15354dffd67789b7bb/cachetools-5.2.0-py3-none-any.whl
Collecting bc-detect-secrets==1.4.5 (from checkov)
  Using cached https://files.pythonhosted.org/packages/f9/b8/53a3e228c35080770968891c170b6efc20e063286286cbe96e2f5ec55b77/bc_detect_secrets-1.4.5-py3-none-any.whl
Collecting tqdm (from checkov)
  Downloading https://files.pythonhosted.org/packages/47/bb/849011636c4da2e44f1253cd927cfb20ada4374d8b3a4e425416e84900cc/tqdm-4.64.1-py2.py3-none-any.whl (78kB)
     |████████████████████████████████| 81kB ...
Collecting aiodns (from checkov)
  Using cached https://files.pythonhosted.org/packages/ab/72/991ee33a517df69c6cd6f3486cfe9b6329557cb55acaa8cefac33c2aa4d2/aiodns-3.0.0-py3-none-any.whl
Collecting update-checker (from checkov)
  Using cached https://files.pythonhosted.org/packages/0c/ba/8dd7fa5f0b1c6a8ac62f8f57f7e794160c1f86f31c6d0fb00f582372a3e4/update_checker-0.18.0-py3-none-any.whl
Collecting pyyaml>=5.4.1 (from checkov)
  Using cached https://files.pythonhosted.org/packages/a8/5b/c4d674846ea4b07ee239fbf6010bcc427c4e4552ba5655b446e36b9a40a7/PyYAML-6.0-cp38-cp38-win_amd64.whl
Collecting semantic-version (from checkov)
  Downloading https://files.pythonhosted.org/packages/6a/23/8146aad7d88f4fcb3a6218f41a60f6c2d4e3a72de72da1825dc7c8f7877c/semantic_version-2.10.0-py2.py3-none-any.whl
Collecting click>=8.0.0 (from checkov)
  Using cached https://files.pythonhosted.org/packages/c2/f1/df59e28c642d583f7dacffb1e0965d0e00b218e0186d7858ac5233dce840/click-8.1.3-py3-none-any.whl
Collecting junit-xml>=1.9 (from checkov)
  Using cached https://files.pythonhosted.org/packages/2a/93/2d896b5fd3d79b4cadd8882c06650e66d003f465c9d12c488d92853dff78/junit_xml-1.9-py2.py3-none-any.whl
Collecting jmespath (from checkov)
  Using cached https://files.pythonhosted.org/packages/31/b4/b9b800c45527aadd64d5b442f9b932b00648617eb5d63d2c7a6587b7cafc/jmespath-1.0.1-py3-none-any.whl
Collecting aiohttp (from checkov)
  Downloading https://files.pythonhosted.org/packages/b8/ba/769b1307c2f86f3d6f486f7683a94aa298e5ba4cff974a663b8cd0388985/aiohttp-3.8.3-cp38-cp38-win_amd64.whl (324kB)
     |████████████████████████████████| 327kB ...
Collecting boto3>=1.17 (from checkov)
  Using cached https://files.pythonhosted.org/packages/55/a9/57cc2a220b4d78f7d13a54cf978e2e615f8b844b50961360116d0749b096/boto3-1.26.27-py3-none-any.whl
Collecting jsonschema<4.0.0,>=3.0.2 (from checkov)
  Downloading https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl (56kB)
     |████████████████████████████████| 61kB ...
Collecting docker (from checkov)
  Using cached https://files.pythonhosted.org/packages/d5/b3/a5e41798a6d4b92880998e0d9e6980e57c5d039f7f7144f87627a6b19084/docker-6.0.1-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12->checkov)
  Using cached https://files.pythonhosted.org/packages/d8/20/256eb3f3f437c575fb1a2efdce5e801a5ce3162ea8117da96c43e6ee97d8/zipp-3.11.0-py3-none-any.whl
Collecting six (from jsonpath-ng->checkov)
  Downloading https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl
Collecting decorator (from jsonpath-ng->checkov)
  Using cached https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting ply (from jsonpath-ng->checkov)
  Using cached https://files.pythonhosted.org/packages/a3/58/35da89ee790598a0700ea49b2a66594140f44dec458c07e8e3d4979137fc/ply-3.11-py2.py3-none-any.whl
Collecting cached-property (from cloudsplaining>=0.4.3->checkov)
  Using cached https://files.pythonhosted.org/packages/48/19/f2090f7dad41e225c7f2326e4cfe6fff49e57dedb5b53636c9551f86b069/cached_property-1.5.2-py2.py3-none-any.whl
Collecting markdown (from cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/86/be/ad281f7a3686b38dd8a307fa33210cdf2130404dfef668a37a4166d737ca/Markdown-3.4.1-py3-none-any.whl (93kB)
     |████████████████████████████████| 102kB ...
Collecting botocore (from cloudsplaining>=0.4.3->checkov)
  Using cached https://files.pythonhosted.org/packages/89/6d/ddc7bb91162c8337de7d619b8eb07bd31863b57c2ea817549f6935e3d26f/botocore-1.29.27-py3-none-any.whl
Collecting click-option-group (from cloudsplaining>=0.4.3->checkov)
  Using cached https://files.pythonhosted.org/packages/cf/b2/808e028b944a1f7c21005205762ee88654c40b73b9de2a04e18384d1c9cd/click_option_group-0.5.5-py3-none-any.whl
Collecting policy-sentry>=0.11.3 (from cloudsplaining>=0.4.3->checkov)
  Using cached https://files.pythonhosted.org/packages/ff/ca/9566e29bf6f73b25f1a78bce07b80d3aa8e705ab2a7f5544e770e81062b1/policy_sentry-0.12.5-py3-none-any.whl
Collecting jinja2 (from cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (133kB)
     |████████████████████████████████| 133kB 6.4MB/s
Collecting gitdb<5,>=4.0.1 (from gitpython->checkov)
  Using cached https://files.pythonhosted.org/packages/21/a6/35f83efec687615c711fe0a09b67e58f6d1254db27b1013119de46f450bd/gitdb-4.0.10-py3-none-any.whl
Collecting importlib-resources>=2.0.0; python_version < "3.9" (from bc-python-hcl2==0.3.47->checkov)
  Using cached https://files.pythonhosted.org/packages/ab/72/b4374afdfacc45bfcdd71404d5ac1315cf90b5b591d6110e1a4a8d1c8cfe/importlib_resources-5.10.1-py3-none-any.whl
Collecting lark>=1.0.0 (from bc-python-hcl2==0.3.47->checkov)
  Using cached https://files.pythonhosted.org/packages/ac/c7/25e678cb94ac2b7be741272d5b2ae099e32e23f36d820e6feb8931b12382/lark-1.1.5-py3-none-any.whl
Collecting contextlib2>=0.5.5 (from schema->checkov)
  Using cached https://files.pythonhosted.org/packages/76/56/6d6872f79d14c0cb02f1646cbb4592eef935857c0951a105874b7b62a0c3/contextlib2-21.6.0-py2.py3-none-any.whl
Collecting setuptools>=47.0.0 (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov)
  Using cached https://files.pythonhosted.org/packages/ef/e3/29d6e1a07e8d90ace4a522d9689d03e833b67b50d1588e693eec15f26251/setuptools-65.6.3-py3-none-any.whl
Collecting toml<0.11.0,>=0.10.0 (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov)
  Downloading https://files.pythonhosted.org/packages/44/6f/7120676b6d73228c96e17f1f794d8ab046fc910d781c8d151120c3f1569e/toml-0.10.2-py2.py3-none-any.whl
Collecting sortedcontainers<3.0.0,>=2.4.0 (from cyclonedx-python-lib<4.0.0,>=2.4.0->checkov)
  Using cached https://files.pythonhosted.org/packages/32/46/9cb0e58b2deb7f82b84065f37f3bffeb12413f947f9388e4cac22c4621ce/sortedcontainers-2.4.0-py2.py3-none-any.whl
Collecting pyparsing!=3.0.5,>=2.0.2 (from packaging==21.3->checkov)
  Downloading https://files.pythonhosted.org/packages/6c/10/a7d0fa5baea8fe7b50f448ab742f26f52b80bfca85ac2be9d35cdd9a3246/pyparsing-3.0.9-py3-none-any.whl (98kB)
     |████████████████████████████████| 102kB 6.4MB/s
Collecting wcwidth (from prettytable>=3.0.0->checkov)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting regex>=2022.1.18 (from pycep-parser==0.3.9->checkov)
  Using cached https://files.pythonhosted.org/packages/1f/f3/895ba11bc0243becd38f8b7560d2e329c465ead247cfb815611c347d7fc1/regex-2022.10.31-cp38-cp38-win_amd64.whl
Collecting idna<4,>=2.5 (from requests>=2.26.0->checkov)
  Downloading https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl (61kB)
     |████████████████████████████████| 71kB 4.5MB/s
Collecting certifi>=2017.4.17 (from requests>=2.26.0->checkov)
  Downloading https://files.pythonhosted.org/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl (155kB)
     |████████████████████████████████| 163kB 6.8MB/s
Collecting urllib3<1.27,>=1.21.1 (from requests>=2.26.0->checkov)
  Downloading https://files.pythonhosted.org/packages/65/0c/cc6644eaa594585e5875f46f3c83ee8762b647b51fc5b0fb253a242df2dc/urllib3-1.26.13-py2.py3-none-any.whl (140kB)
     |████████████████████████████████| 143kB ...
Collecting pycares>=4.0.0 (from aiodns->checkov)
  Using cached https://files.pythonhosted.org/packages/f7/d9/2803d586a71a5958ac31701c9bcdc00ff9a20c43fad3a9029c511e6f0844/pycares-4.3.0-cp38-cp38-win_amd64.whl
Collecting multidict<7.0,>=4.5 (from aiohttp->checkov)
  Downloading https://files.pythonhosted.org/packages/c9/a0/814652f4dc0c0cb80de69273bd7545d1c5a8302ac67909cbcf32c26ae867/multidict-6.0.3-cp38-cp38-win_amd64.whl
Collecting aiosignal>=1.1.2 (from aiohttp->checkov)
  Downloading https://files.pythonhosted.org/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl
Collecting frozenlist>=1.1.1 (from aiohttp->checkov)
  Downloading https://files.pythonhosted.org/packages/03/00/febbfd2ec244a0f91707bd879afe6aa278e337dc41cd9d0d25260e6da38e/frozenlist-1.3.3-cp38-cp38-win_amd64.whl
Collecting attrs>=17.3.0 (from aiohttp->checkov)
  Downloading https://files.pythonhosted.org/packages/f2/bc/d817287d1aa01878af07c19505fafd1165cd6a119e9d0821ca1d1c20312d/attrs-22.1.0-py2.py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 3.8MB/s
Collecting yarl<2.0,>=1.0 (from aiohttp->checkov)
  Downloading https://files.pythonhosted.org/packages/f9/fa/9c746d29462714663d04cf9e34cc44a86efa17705a811c77556643b80f1b/yarl-1.8.2-cp38-cp38-win_amd64.whl (56kB)
     |████████████████████████████████| 61kB 4.1MB/s
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->checkov)
  Using cached https://files.pythonhosted.org/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl
Collecting s3transfer<0.7.0,>=0.6.0 (from boto3>=1.17->checkov)
  Using cached https://files.pythonhosted.org/packages/5e/c6/af903b5fab3f9b5b1e883f49a770066314c6dcceb589cf938d48c89556c1/s3transfer-0.6.0-py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema<4.0.0,>=3.0.2->checkov)
  Downloading https://files.pythonhosted.org/packages/a4/8d/7d7e504e14d1030e31e8ea656482e5fe5b556e11ce43ac899cf5ed1467f5/pyrsistent-0.19.2-cp38-cp38-win_amd64.whl (62kB)
     |████████████████████████████████| 71kB ...
Collecting websocket-client>=0.32.0 (from docker->checkov)
  Using cached https://files.pythonhosted.org/packages/78/d5/2b5719b738791cd798e8f097eba4bb093ff5efca5cef2f3d37a72daa111f/websocket_client-1.4.2-py3-none-any.whl
Collecting pywin32>=304; sys_platform == "win32" (from docker->checkov)
  Using cached https://files.pythonhosted.org/packages/6d/37/fb50f89e6f8a420f0f02adbb81cd85de6fd8a4d4c842b721b08bcd533987/pywin32-305-cp38-cp38-win_amd64.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore->cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/36/7a/87837f39d0296e723bb9b62bbb257d0355c7f6128853c78955f57342a56d/python_dateutil-2.8.2-py2.py3-none-any.whl (247kB)
     |████████████████████████████████| 256kB ...
Collecting beautifulsoup4 (from policy-sentry>=0.11.3->cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/9c/d8/909c4089dbe4ade9f9705f143c9f13f065049a9d5e7d34c828aefdd0a97c/beautifulsoup4-4.11.1-py3-none-any.whl (128kB)
     |████████████████████████████████| 133kB 6.4MB/s
Collecting MarkupSafe>=2.0 (from jinja2->cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/2c/81/91062a81ac8a18f557f12e2618475b53878755c016c9914c8aa207155c4e/MarkupSafe-2.1.1-cp38-cp38-win_amd64.whl
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->checkov)
  Using cached https://files.pythonhosted.org/packages/6d/01/7caa71608bc29952ae09b0be63a539e50d2484bc37747797a66a60679856/smmap-5.0.0-py3-none-any.whl
Collecting cffi>=1.5.0 (from pycares>=4.0.0->aiodns->checkov)
  Downloading https://files.pythonhosted.org/packages/c9/e3/0a52838832408cfbbf3a59cb19bcd17e64eb33795c9710ca7d29ae10b5b7/cffi-1.15.1-cp38-cp38-win_amd64.whl (178kB)
     |████████████████████████████████| 184kB ...
Collecting soupsieve>1.2 (from beautifulsoup4->policy-sentry>=0.11.3->cloudsplaining>=0.4.3->checkov)
  Downloading https://files.pythonhosted.org/packages/16/e3/4ad79882b92617e3a4a0df1960d6bce08edfb637737ac5c3f3ba29022e25/soupsieve-2.3.2.post1-py3-none-any.whl
Collecting pycparser (from cffi>=1.5.0->pycares>=4.0.0->aiodns->checkov)
  Using cached https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
ERROR: requests 2.28.1 has requirement charset-normalizer<3,>=2, but you'll have charset-normalizer 3.0.1 which is incompatible.
ERROR: aiohttp 3.8.3 has requirement charset-normalizer<3.0,>=2.0, but you'll have charset-normalizer 3.0.1 which is incompatible.
Installing collected packages: zipp, importlib-metadata, packageurl-python, charset-normalizer, six, decorator, ply, jsonpath-ng, pyyaml, cached-property, contextlib2, schema, markdown, jmespath, python-dateutil, urllib3, botocore, s3transfer, boto3, colorama, click, click-option-group, soupsieve, beautifulsoup4, idna, certifi, requests, policy-sentry, MarkupSafe, jinja2, cloudsplaining, smmap, gitdb, gitpython, dpath, tabulate, networkx, typing-extensions, deep-merge, importlib-resources, lark, bc-python-hcl2, dockerfile-parse, termcolor, argcomplete, setuptools, toml, sortedcontainers, cyclonedx-python-lib, pyparsing, packaging, policyuniverse, wcwidth, prettytable, aiomultiprocess, regex, pycep-parser, configargparse, cachetools, bc-detect-secrets, tqdm, pycparser, cffi, pycares, aiodns, update-checker, semantic-version, junit-xml, multidict, frozenlist, aiosignal, attrs, yarl, async-timeout, aiohttp, pyrsistent, jsonschema, websocket-client, pywin32, docker, checkov
  Running setup.py install for dpath ... done
  Found existing installation: setuptools 41.2.0
    Uninstalling setuptools-41.2.0:
      Successfully uninstalled setuptools-41.2.0
Successfully installed MarkupSafe-2.1.1 aiodns-3.0.0 aiohttp-3.8.3 aiomultiprocess-0.9.0 aiosignal-1.3.1 argcomplete-2.0.0 async-timeout-4.0.2 attrs-22.1.0 bc-detect-secrets-1.4.5 bc-python-hcl2-0.3.47 beautifulsoup4-4.11.1 boto3-1.26.27 botocore-1.29.27 cached-property-1.5.2 cachetools-5.2.0 certifi-2022.12.7 cffi-1.15.1 charset-normalizer-3.0.1 checkov-2.2.139 click-8.1.3 click-option-group-0.5.5 cloudsplaining-0.5.0 colorama-0.4.6 configargparse-1.5.3 contextlib2-21.6.0 cyclonedx-python-lib-3.1.1 decorator-5.1.1 deep-merge-0.0.4 docker-6.0.1 dockerfile-parse-1.2.0 dpath-1.5.0 frozenlist-1.3.3 gitdb-4.0.10 gitpython-3.1.29 idna-3.4 importlib-metadata-5.1.0 importlib-resources-5.10.1 jinja2-3.1.2 jmespath-1.0.1 jsonpath-ng-1.5.3 jsonschema-3.2.0 junit-xml-1.9 lark-1.1.5 markdown-3.4.1 multidict-6.0.3 networkx-2.6.3 packageurl-python-0.10.4 packaging-21.3 ply-3.11 policy-sentry-0.12.5 policyuniverse-1.5.0.20220613 prettytable-3.5.0 pycares-4.3.0 pycep-parser-0.3.9 pycparser-2.21 pyparsing-3.0.9 pyrsistent-0.19.2 python-dateutil-2.8.2 pywin32-305 pyyaml-6.0 regex-2022.10.31 requests-2.28.1 s3transfer-0.6.0 schema-0.7.5 semantic-version-2.10.0 setuptools-65.6.3 six-1.16.0 smmap-5.0.0 sortedcontainers-2.4.0 soupsieve-2.3.2.post1 tabulate-0.9.0 termcolor-2.1.1 toml-0.10.2 tqdm-4.64.1 typing-extensions-4.4.0 update-checker-0.18.0 urllib3-1.26.13 wcwidth-0.2.5 websocket-client-1.4.2 yarl-1.8.2 zipp-3.11.0
WARNING: You are using pip version 19.2.3, however version 22.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(checkov) C:\Git_COMPANY_Pipeline_Dev\Environments_Shared\Common\Terraform>checkov
Traceback (most recent call last):
  File "C:\Git_COMPANY_Pipeline_Dev\Environments_Shared\Common\Terraform\checkov\Scripts\checkov.cmd", line 37, in <module>
    from checkov.main import run
ImportError: No module named checkov.main
```

**Comment by gruebel** [comment]
hey @davidfordaus thanks for reaching out. You wrote you are using pip `22.3.1` but in the error log I see you are using `19.2.3` can you update it first, because you need to update it inside your `venv` and then it should work.

**Comment by tanadeau** [comment]
I also saw this issue with pip 19.x. Once I upgrade to latest with `python3 -m pip install --upgrade pip` and then installed checkov, everything seemed to work.

**Comment by gruebel** [comment]
for anyone finding this, please update `pip` to the latest version and then there shouldn't be any issue.
