### ISSUE TITLE
Failed to run check: Ensure that instances are not configured to use the default service account for configuration

### ISSUE THREAD

**Issue by bschaatsbergen** [bridgecrewio/checkov#4205]
**Describe the issue**
Running pre-commit against this repository: https://github.com/bschaatsbergen/terraform-gce-atlantis

What I run: `checkov -d . --framework terraform`

I seem to run in the below error, even when trying to skip the check..

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
$ pre-commit run -a 
Terraform fmt............................................................Passed
Terraform validate.......................................................Passed
Terraform docs...........................................................Passed
Checkov..................................................................Failed
- hook id: terraform_checkov
- exit code: 1

2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module terraform-google-modules/container-vm/google:2.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module bschaatsbergen/atlantis/gce:None (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module terraform-google-modules/cloud-nat/google:1.0.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module terraform-google-modules/vm/google//modules/instance_template:1.0.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module terraform-google-modules/vm/google//modules/mig:1.0.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module GoogleCloudPlatform/lb-http/google:2.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,223 [MainThread  ] [WARNI]  Failed to download module terraform-google-modules/project-factory/google:3.0 (for external modules, the --download-external-modules flag is required)
2023-01-06 20:01:02,343 [MainThread  ] [ERROR]  Failed to run check: Ensure that instances are not configured to use the default service account for configuration: {'can_ip_forward': [False], 'description': ['This template is used to create VMs that run Atlantis in a containerized environment using Docker'], 'disk': [{'auto_delete': [True], 'boot': [True], 'disk_size_gb': [10], 'disk_type': ['pd-ssd'], 'dynamic': [{'disk_encryption_key': {'content': [{'kms_key_self_link': ['${var.disk_kms_key_self_link}']}], 'for_each': ['${var.disk_kms_key_self_link != None ? [1] : []}']}}], 'source_image': ['${data.google_compute_image.cos.self_link}'], 'disk_encryption_key': [{'kms_key_self_link': ['${var.disk_kms_key_self_link}']}]}, {'auto_delete': [False], 'device_name': ['atlantis-disk-0'], 'disk_size_gb': ['${var.persistent_disk_size_gb}'], 'disk_type': ['pd-ssd'], 'dynamic': [{'disk_encryption_key': {'content': [{'kms_key_self_link': ['${var.disk_kms_key_self_link}']}], 'for_each': ['${var.disk_kms_key_self_link != None ? [1] : []}']}}], 'mode': ['READ_WRITE']}], 'instance_description': ['VM running Atlantis in a containerized environment using Docker'], 'labels': [{'container-vm': 'module.atlantis.vm_container_label'}], 'lifecycle': [{'create_before_destroy': [True]}], 'machine_type': ['n2-standard-2'], 'metadata': [{'block-project-ssh-keys': False, 'gce-container-declaration': 'module.atlantis.metadata_value', 'google-logging-enabled': True}], 'metadata_startup_script': ['templatefile("path.module/startup-script.sh",{\'disk_name\': \'atlantis-disk-0\'})'], 'name_prefix': ['var.name-'], 'network_interface': [{'subnetwork': ['var.subnetwork'], 'subnetwork_project': ['var.project']}], 'project': ['var.project'], 'region': ['var.region'], 'scheduling': [{'automatic_restart': [True], 'instance_termination_action': ['${var.spot_machine_enabled ? "STOP" : None}'], 'on_host_maintenance': ['MIGRATE'], 'preemptible': [False], 'provisioning_model': ['STANDARD']}], 'service_account': [{'email': [{'email': '', 'scopes': 'cloud-platform'}], 'scopes': ['cloud-platform']}], 'shielded_instance_config': [{'enable_integrity_monitoring': [True], 'enable_vtpm': [True]}], 'tags': [['atlantis']]} at file: /main.tf
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/main.py", line 219, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 59, in run
    reports = [self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/runner.py", line 119, in run
    self.check_tf_definition(report, root_folder, runner_filter, collect_skip_comments)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/runner.py", line 212, in check_tf_definition
    self.run_all_blocks(definition, self.context, full_file_path, root_folder, report,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/runner.py", line 222, in run_all_blocks
    self.run_block(definition[block_type], definitions_context,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/runner.py", line 294, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 121, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 135, in run_check
    result = check.run(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 81, in run
    raise e
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 68, in run
    check_result["result"] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 54, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/checkov/terraform/checks/resource/gcp/GoogleComputeDefaultServiceAccount.py", line 25, in scan_resource_conf
    not re.match(DEFAULT_SERVICE_ACCOUNT, conf['service_account'][0]['email'][0]):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

**Desktop (please complete the following information):**
- OS: Linux
- Checkov version: 2.0.751

**Comment by bschaatsbergen** [comment]
Works like a charm @gruebel, thanks. I should've updated to the latest version, I hadn't kept track of the releases in a while.

Closing this issue.
