### ISSUE TITLE
local variable 'fileContent' referenced before assignment

### ISSUE THREAD

**Issue by iorlas** [bridgecrewio/checkov#4229]
**Describe the issue**
When running the checkov in one of the projects we have, it feels like it fails to read the yaml file in Kustomize checker. The problem is quite a simple one - the python variable is not defined. I believe the logic I incorrect, it should skip any further checks if it failed to read the yaml file.

**Examples**
-

**Exception Trace**

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 39, in func_wrapper
    result = original_func(item)
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 96, in _parallel_run
    report = runner.run(
  File "/usr/local/lib/python3.10/site-packages/checkov/kustomize/runner.py", line 539, in run
    self.run_kustomize_to_k8s(root_folder, files, runner_filter)
  File "/usr/local/lib/python3.10/site-packages/checkov/kustomize/runner.py", line 480, in run_kustomize_to_k8s
    self.kustomizeProcessedFolderAndMeta[kustomize_dir] = self._parseKustomization(kustomize_dir)
  File "/usr/local/lib/python3.10/site-packages/checkov/kustomize/runner.py", line 246, in _parseKustomization
    if 'resources' in fileContent:
UnboundLocalError: local variable 'fileContent' referenced before assignment

```

**Desktop (please complete the following information):**
 - OS: macOS
 - Checkov Version: 2.2.207

**Additional context**
----

**Comment by gruebel** [comment]
hey @iorlas thanks for reaching out.
Yeah, you are correct. we should just skip any further processing of the file 😄 will create a PR for it. Would it be possible for you to share the the problematic file? If you run `checkov` with debug log enabled, then it will log the problematic file path
```shell
LOG_LEVEL=DEBUG checkov -d . 
```
