### ISSUE TITLE
Terraform: Checkov crashes when using `for_each` with variables and `dynamic` blocks

### ISSUE THREAD

**Issue by Erouan50** [bridgecrewio/checkov#4324]
Hello everyone!

I'm using Checkov to validate some Terraform code; it crashes oddly in a specific condition with `IndexError: list index out of range` as an error message. Here is the code that bothers Checkov:

```hcl
variable "traefik_https_port_name" {
  default = "traefik-https"
}

variable "traefik_http_port_name" {
  default = "traefik-http"
}

resource "google_compute_backend_service" "this" {
  for_each = {
    http  = var.traefik_http_port_name
    https = var.traefik_https_port_name
  }
  name                            = "${var.cluster_name}-lb-pub-${each.key}-svc"
  port_name                       = each.value
  protocol                        = "HTTP"
  timeout_sec                     = var.backend_service_timeout
  enable_cdn                      = false
  connection_draining_timeout_sec = 30
  health_checks                   = [google_compute_http_health_check.http_health_check.self_link]

  dynamic "backend" {
    for_each = toset(google_container_cluster.cluster.instance_group_urls)
    content {
      group           = backend.value
      balancing_mode  = "UTILIZATION"
      max_utilization = "1.0"
      capacity_scaler = "1.0"
      max_rate        = "100000"
    }
  }
}
```

Two interesting notes:
* If I comment the block `dynamic "backend"`, no issue
* If I replace the variable (`var.traefik_http_port_name`) with their value, no issue

**Exception Trace**

```sh
LOG_LEVEL=DEBUG /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/bin/python3 /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/bin/checkov
2023-01-24 16:08:53,654 [MainThread  ] [DEBUG]  Leveraging the bundled IAM Definition.
2023-01-24 16:08:53,654 [MainThread  ] [DEBUG]  Leveraging the IAM definition at /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/policy_sentry/shared/data/iam-definition.json
2023-01-24 16:08:53,958 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710> with order 1
2023-01-24 16:08:53,958 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,958 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>]
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950> with order 0
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>]
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x7f028887de10> with order 10
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x7f028887de10>]
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x7f028887ed50> with order 6
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,959 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>, <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x7f028887ed50>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x7f028887de10>]
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x7f028887fe50> with order 0
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x7f028887fe50>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>, <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x7f028887ed50>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x7f028887de10>]
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.suppressions_integration.SuppressionsIntegration object at 0x7f0288654c90> with order 2
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-24 16:08:53,960 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x7f028887e950>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x7f028887fe50>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x7f02887ea710>, <checkov.common.bridgecrew.integration_features.features.suppressions_integration.SuppressionsIntegration object at 0x7f0288654c90>, <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x7f028887ed50>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x7f028887de10>]
2023-01-24 16:08:53,976 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/bicep/checks/graph_checks
2023-01-24 16:08:53,976 [MainThread  ] [DEBUG]  Searching through ['__pycache__'] and ['SQLServerAuditingEnabled.yaml', '__init__.py']
2023-01-24 16:08:53,978 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-311.pyc']
2023-01-24 16:08:54,039 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/home/antoine.rouaze/src/test, universal_newlines=False, shell=None, istream=None)
2023-01-24 16:08:54,041 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/home/antoine.rouaze/src/test, universal_newlines=False, shell=None, istream=None)
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  No API key present; setting include_all_checkov_policies to True
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  Run metadata: {
  "checkov_version": "2.2.299",
  "python_executable": "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/bin/python3",
  "python_version": "3.11.1 (main, Jan  6 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]",
  "checkov_executable": "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/bin/checkov",
  "args": [
    "Config File (/home/antoine.rouaze/src/test/.checkov.yaml):",
    "  framework:         terraform",
    "  directory:         .",
    "  baseline:          .checkov.baseline",
    "  evaluate-variables:True",
    "  compact:           True",
    "  quiet:             True",
    "Defaults:",
    "  --branch:          master",
    "  --download-external-modules:False",
    "  --external-modules-download-path:.external_modules",
    "  --secrets-scan-file-type:[]",
    "  --block-list-secret-scan:[]",
    "  --summary-position:top",
    "  --mask:            []",
    ""
  ]
}
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  Resultant set of frameworks (removing skipped frameworks): terraform
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  BC_SOURCE = cli, version = 2.2.299
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  terraform_runner declares no system dependency checks required.
2023-01-24 16:08:54,198 [MainThread  ] [DEBUG]  No API key found. Scanning locally only.
2023-01-24 16:08:54,497 [MainThread  ] [DEBUG]  Got checkov mappings and guidelines from Bridgecrew platform
2023-01-24 16:08:54,498 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/checks/graph_checks
2023-01-24 16:08:54,498 [MainThread  ] [DEBUG]  Searching through ['aws', 'azure', 'gcp', '__pycache__'] and ['__init__.py']
2023-01-24 16:08:54,503 [MainThread  ] [DEBUG]  Searching through [] and ['ALBProtectedByWAF.yaml', 'ALBRedirectsHTTPToHTTPS.yaml', 'AMRClustersNotOpenToInternet.yaml', 'APIGWLoggingLevelsDefinedProperly.yaml', 'APIGatewayEndpointsUsesCertificateForAuthentication.yaml', 'APIGatewayRequestParameterValidationEnabled.yaml', 'APIProtectedByWAF.yaml', 'AWSConfigRecorderEnabled.yaml', 'AWSNATGatewaysshouldbeutilized.yaml', 'AWSSSMParameterShouldBeEncrypted.yaml', 'AppLoadBalancerTLS12.yaml', 'AppSyncProtectedByWAF.yaml', 'AutoScalingEnableOnDynamoDBTables.yaml', 'AutoScallingEnabledELB.yaml', 'CLoudFrontS3OriginConfigWithOAI.yaml', 'CloudFrontHasCustomSSLCertificate.yaml', 'CloudFrontHasResponseHeadersPolicy.yaml', 'CloudFrontUsesSecureProtocolsForHTTPS.yaml', 'CloudFrontWebACLConfiguredWIthLog4jVulnerability.yaml', 'CloudtrailHasCloudwatch.yaml', 'CodecommitApprovalRulesAttached.yaml', 'ConfigRecorderRecordsAllGlobalResources.yaml', 'DMSEndpointHaveSSLConfigured.yaml', 'EBSAddedBackup.yaml', 'EC2InstanceHasIAMRoleAttached.yaml', 'EFSAddedBackup.yaml', 'EIPAllocatedToVPCAttachedEC2.yaml', 'EMRClusterHasSecurityConfiguration.yaml', 'ElastiCacheRedisConfiguredAutomaticFailOver.yaml', 'EncryptedEBSVolumeOnlyConnectedToEC2s.yaml', 'GuardDutyIsEnabled.yaml', 'HTTPNotSendingPasswords.yaml', 'IAMGroupHasAtLeastOneUser.yaml', 'IAMManagedIAMFullAccessPolicy.yaml', 'IAMPolicyNotAllowFullIAMAccess.yaml', 'IAMUserHasNoConsoleAccess.yaml', 'IAMUsersAreMembersAtLeastOneGroup.yaml', 'NeptuneDeletionProtectionEnabled.yaml', 'OpenSearchDomainHasFineGrainedControl.yaml', 'PostgresDBHasQueryLoggingEnabled.yaml', 'PostgresRDSHasQueryLoggingEnabled.yaml', 'RDSClusterHasBackupPlan.yaml', 'Route53ARecordAttachedResource.yaml', 'Route53ZoneEnableDNSSECSigning.yaml', 'Route53ZoneHasMatchingQueryLog.yaml', 'S3BucketEncryption.yaml', 'S3BucketHasPublicAccessBlock.yaml', 'S3BucketLogging.yaml', 'S3BucketReplicationConfiguration.yaml', 'S3BucketVersioning.yaml', 'S3KMSEncryptedByDefault.yaml', 'S3NotAllowAccessToAllAuthenticatedUsers.yaml', 'S3PublicACLRead.yaml', 'S3PublicACLWrite.yaml', 'SGAttachedToResource.yaml', 'SubnetHasACL.yaml', 'VPCHasFlowLog.yaml', 'VPCHasRestrictedSG.yaml', 'VPCPeeringRouteTableOverlyPermissive.yaml', 'WAF2HasLogs.yaml']
2023-01-24 16:08:54,599 [MainThread  ] [DEBUG]  Searching through [] and ['AccessToPostgreSQLFromAzureServicesIsDisabled.yaml', 'ApplicationGatewayEnablesWAF.yaml', 'AzureActiveDirectoryAdminIsConfigured.yaml', 'AzureAntimalwareIsConfiguredWithAutoUpdatesForVMs.yaml', 'AzureDataFactoriesEncryptedWithCustomerManagedKey.yaml', 'AzureMSSQLServerHasSecurityAlertPolicy.yaml', 'AzureNetworkInterfacePublicIPAddressId.yaml', 'AzureStorageAccountsUseCustomerManagedKeyForEncryption.yaml', 'AzureSynapseWorkspacesHaveNoIPFirewallRulesAttached.yaml', 'AzureUnattachedDisksAreEncrypted.yaml', 'CognitiveServicesCustomerManagedKey.yaml', 'DataExplorerEncryptionUsesCustomKey.yaml', 'MSQLenablesCustomerManagedKey.yaml', 'PGSQLenablesCustomerManagedKey.yaml', 'SQLServerAuditingEnabled.yaml', 'SQLServerAuditingRetention90Days.yaml', 'StorageContainerActivityLogsNotPublic.yaml', 'StorageCriticalDataEncryptedCMK.yaml', 'StorageLoggingIsEnabledForBlobService.yaml', 'StorageLoggingIsEnabledForTableService.yaml', 'VAconfiguredToSendReports.yaml', 'VAconfiguredToSendReportsToAdmins.yaml', 'VAisEnabledInStorageAccount.yaml', 'VAsetPeriodicScansOnSQL.yaml', 'VMHasBackUpMachine.yaml', 'VirtualMachinesUtilizingManagedDisks.yaml']
2023-01-24 16:08:54,636 [MainThread  ] [DEBUG]  Searching through [] and ['CloudFunctionSecureHTTPTrigger.yaml', 'DisableAccessToSqlDBInstanceForRootUsersWithoutPassword.yaml', 'GCPAuditLogsConfiguredForAllServicesAndUsers.yaml', 'GCPComputeFirewallOverlyPermissiveToAllTraffic.yaml', 'GCPContainerRegistryReposAreNotPubliclyAccessible.yaml', 'GCPKMSCryptoKeysAreNotPubliclyAccessible.yaml', 'GCPKMSKeyRingsAreNotPubliclyAccessible.yaml', 'GCPLogBucketsConfiguredUsingLock.yaml', 'GCPNetworkDoesNotUseDefaultFirewall.yaml', 'GCPPostgreSQLDatabaseFlaglog_durationIsSetToON.yaml', 'GCPPostgreSQLDatabaseFlaglog_executor_statsIsSetToOFF.yaml', 'GCPPostgreSQLDatabaseFlaglog_parser_statsIsSetToOFF.yaml', 'GCPPostgreSQLDatabaseFlaglog_planner_statsIsSetToOFF.yaml', 'GCPPostgreSQLDatabaseFlaglog_statement_statsIsSetToOFF.yaml', 'GCPProjectHasNoLegacyNetworks.yaml', 'GCRContainerVulnerabilityScanningEnabled.yaml', 'GKEClustersAreNotUsingDefaultServiceAccount.yaml', 'ServiceAccountHasGCPmanagedKey.yaml']
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-311.pyc']
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/cloudformation/checks/graph_checks
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Searching through ['__pycache__'] and ['__init__.py']
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-311.pyc']
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/kubernetes/checks/graph_checks
2023-01-24 16:08:54,664 [MainThread  ] [DEBUG]  Searching through ['__pycache__'] and ['ImpersonatePermissions.yaml', 'ModifyServicesStatus.yaml', 'NoCreateNodesProxyOrPodsExec.yaml', 'ReadAllSecrets.yaml', 'RequireAllPodsToHaveNetworkPolicy.yaml', 'RoleBindingPE.yaml', '__init__.py']
2023-01-24 16:08:54,678 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-311.pyc']
2023-01-24 16:08:54,678 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/bicep/checks/graph_checks
2023-01-24 16:08:54,678 [MainThread  ] [DEBUG]  Searching through ['__pycache__'] and ['SQLServerAuditingEnabled.yaml', '__init__.py']
2023-01-24 16:08:54,680 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-311.pyc']
2023-01-24 16:08:54,680 [MainThread  ] [DEBUG]  Loading external checks from /home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform_plan/checks/graph_checks
2023-01-24 16:08:54,681 [MainThread  ] [DEBUG]  Running without API key, so only open source runners will be enabled
2023-01-24 16:08:54,681 [MainThread  ] [DEBUG]  Filtered list of policies: []
2023-01-24 16:08:54,681 [MainThread  ] [DEBUG]  Received the following policy-level suppressions, that will be skipped from running: []
2023-01-24 16:08:54,682 [MainThread  ] [DEBUG]  Checking if terraform is valid for license
2023-01-24 16:08:54,682 [MainThread  ] [DEBUG]  Open source mode - the runner is enabled
2023-01-24 16:08:54,682 [MainThread  ] [INFO ]  Scanning root folder and producing fresh tf_definitions and context
2023-01-24 16:08:54,682 [MainThread  ] [INFO ]  Parsing HCL files in source dir
2023-01-24 16:08:54,682 [MainThread  ] [DEBUG]  Parsing /home/antoine.rouaze/src/test/main.tf
2023-01-24 16:08:54,691 [MainThread  ] [DEBUG]  Module load loop 0
2023-01-24 16:08:54,692 [MainThread  ] [INFO ]  Building graph from parsed module
2023-01-24 16:08:54,692 [MainThread  ] [INFO ]  Creating vertices
2023-01-24 16:08:54,692 [MainThread  ] [INFO ]  [TerraformLocalGraph] created 6 vertices
2023-01-24 16:08:54,692 [MainThread  ] [INFO ]  Creating edges
2023-01-24 16:08:54,693 [MainThread  ] [INFO ]  [TerraformLocalGraph] created 2 edges
2023-01-24 16:08:54,693 [MainThread  ] [INFO ]  Rendering variables, graph has 6 vertices and 2 edges
2023-01-24 16:08:54,693 [MainThread  ] [INFO ]  evaluating 2 edges
Traceback (most recent call last):
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/main.py", line 810, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 94, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/runner.py", line 120, in run
    local_graph, self.definitions = self.graph_manager.build_graph_from_source_directory(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_manager.py", line 45, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/local_graph.py", line 66, in build_graph
    renderer.render_variables_from_local_graph()
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 31, in render_variables_from_local_graph
    self._render_variables_from_edges()
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 69, in _render_variables_from_edges
    self._edge_evaluation_task([edge_group])
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 101, in _edge_evaluation_task
    self.evaluate_vertex_attribute_from_edge(inner_edges)
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 137, in evaluate_vertex_attribute_from_edge
    self.update_evaluated_value(
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 259, in update_evaluated_value
    self.local_graph.update_vertex_attribute(
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/local_graph.py", line 434, in update_vertex_attribute
    self.vertices[vertex_index].update_attribute(
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/common/graph/graph_builder/graph_components/blocks.py", line 169, in update_attribute
    additional_changed_attributes = self.extract_additional_changed_attributes(key)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/graph_components/blocks.py", line 59, in extract_additional_changed_attributes
    return self._extract_dynamic_changed_attributes(attribute_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/.cache/pre-commit/repo8vrqwjjk/py_env-python3/lib/python3.11/site-packages/checkov/terraform/graph_builder/graph_components/blocks.py", line 71, in _extract_dynamic_changed_attributes
    dynamic_block_name = dynamic_content_key_parts[-1]
                         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

**Desktop:**
 - OS: Fedora 37 - Linux 6.1.6-200.fc37.x86_64
 - Checkov Version: 2.2.299

**Additional context**

It's easy to reproduce with a `null_resource`:

```hcl
variable "value_1" {
  default = "value_1"
}

resource "null_resource" "test" {
  for_each = {
    key_1 = var.value_1
  }

  dynamic "trigger" {
    for_each = toset([""])
    content {
      trigger = {
        my_trigger = "test"
      }
    }
  }
}
```

**Comment by gruebel** [comment]
hey @Erouan50 thanks for reaching out.
We are soon starting to implement support for `for_each` on the resource level, so we can't accurately validate your current setup, but it shouldn't result in a crash either 😄 and thanks for easy example, makes the debugging easier 🥇
