### ISSUE TITLE
BCAuthError even if local exec

### ISSUE THREAD

**Issue by Benoit-LAGUET** [bridgecrewio/checkov#4345]
**Describe the issue**
Hello,
when executing checkov command in a CLI it ends with the following error.
It look like an authentication error but it fail even for a local execution.
I don't know why checkov try to connect to Bridgecrew.

**Exception Trace**

**Command : checkov -d.**

```
2023-01-27 10:53:28,006 [MainThread  ] [DEBUG]  Leveraging the bundled IAM Definition.
2023-01-27 10:53:28,006 [MainThread  ] [DEBUG]  Leveraging the IAM definition at /Users/ben/Library/Python/3.10/lib/python/site-packages/policy_sentry/shared/data/iam-definition.json
2023-01-27 10:53:28,772 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430> with order 0
2023-01-27 10:53:28,772 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,772 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>]
2023-01-27 10:53:28,773 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10> with order 1
2023-01-27 10:53:28,773 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,773 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10>]
2023-01-27 10:53:28,774 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x10881b1c0> with order 0
2023-01-27 10:53:28,774 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,774 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x10881b1c0>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10>]
2023-01-27 10:53:28,774 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x10881add0> with order 10
2023-01-27 10:53:28,775 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,775 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x10881b1c0>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x10881add0>]
2023-01-27 10:53:28,776 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x10881b9d0> with order 6
2023-01-27 10:53:28,776 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,776 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x10881b1c0>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10>, <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x10881b9d0>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x10881add0>]
2023-01-27 10:53:28,776 [MainThread  ] [DEBUG]  Adding the IntegrationFeatureRegistry <checkov.common.bridgecrew.integration_features.features.suppressions_integration.SuppressionsIntegration object at 0x108850280> with order 2
2023-01-27 10:53:28,777 [MainThread  ] [DEBUG]  self.features after the sort:
2023-01-27 10:53:28,777 [MainThread  ] [DEBUG]  [<checkov.common.bridgecrew.integration_features.features.policy_metadata_integration.PolicyMetadataIntegration object at 0x107f98430>, <checkov.common.bridgecrew.integration_features.features.repo_config_integration.RepoConfigIntegration object at 0x10881b1c0>, <checkov.common.bridgecrew.integration_features.features.custom_policies_integration.CustomPoliciesIntegration object at 0x10881ad10>, <checkov.common.bridgecrew.integration_features.features.suppressions_integration.SuppressionsIntegration object at 0x108850280>, <checkov.common.bridgecrew.integration_features.features.licensing_integration.LicensingIntegration object at 0x10881b9d0>, <checkov.common.bridgecrew.integration_features.features.fixes_integration.FixesIntegration object at 0x10881add0>]
2023-01-27 10:53:28,848 [MainThread  ] [DEBUG]  Loading external checks from /usr/local/lib/python3.10/site-packages/checkov/bicep/checks/graph_checks
2023-01-27 10:53:28,848 [MainThread  ] [DEBUG]  Searching through ['__pycache__'] and ['SQLServerAuditingEnabled.yaml', '__init__.py']
2023-01-27 10:53:28,853 [MainThread  ] [DEBUG]  Searching through [] and ['__init__.cpython-310.pyc']
2023-01-27 10:53:29,107 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/Users/ben/Git/cma/ureport/terraform, universal_newlines=False, shell=None, istream=None)
2023-01-27 10:53:29,136 [MainThread  ] [DEBUG]  Popen(['git', 'version'], cwd=/Users/ben/Git/cma/ureport/terraform, universal_newlines=False, shell=None, istream=None)
2023-01-27 10:53:29,487 [MainThread  ] [DEBUG]  No API key present; setting include_all_checkov_policies to True
2023-01-27 10:53:29,487 [MainThread  ] [DEBUG]  Run metadata: {
  "checkov_version": "2.2.304",
  "python_executable": "/usr/local/opt/python@3.10/bin/python3.10",
  "python_version": "3.10.9 (main, Dec 15 2022, 18:18:30) [Clang 14.0.0 (clang-1400.0.29.202)]",
  "checkov_executable": "/usr/local/bin/checkov",
  "args": [
    "Command Line Args:   -d .",
    "Defaults:",
    "  --framework:       ['all']",
    "  --branch:          master",
    "  --download-external-modules:False",
    "  --external-modules-download-path:.external_modules",
    "  --evaluate-variables:True",
    "  --secrets-scan-file-type:[]",
    "  --block-list-secret-scan:[]",
    "  --summary-position:top",
    "  --mask:            []",
    ""
  ]
}
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  Resultant set of frameworks (removing skipped frameworks): all
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  BC_SOURCE = cli, version = 2.2.304
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  terraform_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  cloudformation_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  kubernetes_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  serverless_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  arm_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [DEBUG]  terraform_plan_runner declares no system dependency checks required.
2023-01-27 10:53:29,488 [MainThread  ] [INFO ]  Checking necessary system dependancies for helm checks.
2023-01-27 10:53:29,689 [MainThread  ] [INFO ]  Found working version of helm dependancies: v3.11.0
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  dockerfile_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  secrets_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  json_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  yaml_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  github_configuration_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  gitlab_configuration_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  gitlab_ci_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  bitbucket_configuration_runner declares no system dependency checks required.
2023-01-27 10:53:29,689 [MainThread  ] [DEBUG]  bitbucket_pipelines_runner declares no system dependency checks required.
2023-01-27 10:53:29,690 [MainThread  ] [INFO ]  Checking necessary system dependancies for kustomize checks.
2023-01-27 10:53:29,859 [MainThread  ] [INFO ]  Found working version of kustomize dependancy kubectl: 1.22
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  github_actions_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  bicep_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  openapi_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  sca_image_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  argo_workflows_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  circleci_pipelines_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  azure_pipelines_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  ansible_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  sca_package_runner declares no system dependency checks required.
2023-01-27 10:53:29,860 [MainThread  ] [DEBUG]  Using API key ending with ce4cc17f
2023-01-27 10:53:30,754 [MainThread  ] [ERROR]  Received an error response during authentication
2023-01-27 10:53:30,754 [MainThread  ] [DEBUG]  An error occurred setting up the Bridgecrew platform integration. Please check your API token and try again.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 708, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=self.config.repo_id,
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 249, in setup_bridgecrew_credentials
    repo_full_path, response = self.get_s3_role(repo_id)
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 298, in get_s3_role
    raise BridgecrewAuthError(error_message)
checkov.common.bridgecrew.platform_errors.BridgecrewAuthError: BCAuthError, Received unexpected response from platform (status code 403). Please verify that your API token is valid and has permissions to call the Bridgecrew APIs.The key must be associated with any role besides Auditor.
````

**Desktop (please complete the following information):**
 - OS: IOS Ventura (same problem with Monterey)
 - Checkov Version : 2.2.304

**Additional context**
- Checkov is installed using Brew
- In the past I used vscode checkov extension (maybe there is a conflict)

**Comment by fraz78** [comment]
@gruebel its been a painful few hours until i came across your comments above. Simple but effective haha. Thanks.
