### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by vemulkri** [bridgecrewio/checkov#4502]
**Describe the issue**
Error while using latest image: 2.3.14

**Examples**
```
Error: -14 17:19:00,804 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 824, in run
    self.scan_reports = runner_registry.run(
  File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 95, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/runner.py", line 123, in run
    local_graph, self.definitions = self.graph_manager.build_graph_from_source_directory(
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_manager.py", line 48, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/local_graph.py", line 78, in build_graph
    renderer.render_variables_from_local_graph()
  File "/usr/local/lib/python3.10/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 34, in render_variables_from_local_graph
    self._render_variables_from_edges()
  File "/usr/local/lib/python3.10/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 75, in _render_variables_from_edges
    self._edge_evaluation_task([edge_group])
  File "/usr/local/lib/python3.10/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 109, in _edge_evaluation_task
    self.evaluate_vertex_attribute_from_edge(inner_edges)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 143, in evaluate_vertex_attribute_from_edge
    self.update_evaluated_value(
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 263, in update_evaluated_value
    str_to_evaluate if self.attributes_no_eval(changed_attribute_key, vertex) else evaluator.evaluate_terraform(str_to_evaluate)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py", line 54, in evaluate_terraform
    evaluated_value = handle_for_loop(evaluated_value)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py", line 210, in handle_for_loop
    new_val = _handle_for_loop_in_dict(rendered_statement, input_str, end_bracket_idx + 1)
  File "/usr/local/lib/python3.10/site-packages/checkov/terraform/graph_builder/variable_rendering/evaluate_terraform.py", line 2[41](https://github.com/Flutter-Global/fi-networks-aws-global-network/actions/runs/4176351095/jobs/7232520803#step:5:42), in _handle_for_loop_in_dict
    k_expression, v_expression = expression.replace(' ', '').split(renderer.FOR_EXPRESSION_DICT)
ValueError: too many values to unpack (expected 2)
```

Action ref i use in workflow:
```yaml
   - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: /
          framework: terraform
          quiet: true
```

**Version (please complete the following information):**
 - Checkov Version - 2.3.14
 
**Additional context**
I see latest image is pushed few mins back, started getting above error.

**Comment by ChanochShayner** [comment]
Hey @vemulkri 
This [PR](https://github.com/bridgecrewio/checkov/pull/4507) should fix it.
Feel free to reach out if it keeps failing.

**Comment by ravenium** [comment]
Had this issue too - wasn't sure why my GHA was breaking, and honestly I'm not sure what changed in the past two weeks that caused it.  Thanks for reporting!

**Comment by gruebel** [comment]
If the issue still exist feel free to reach out and please add some examples 🙂
