### ISSUE TITLE
Checks suppressions are unsupported in the Ansible runner 

### ISSUE THREAD

**Issue by JamesWoolfenden** [bridgecrewio/checkov#4532]
if you attempt to suppress a check like:
```
---
- name: Verify tests
  hosts: all
  gather_facts: False
  tasks:
    - name: default
      amazon.aws.ec2_instance:
        name: "public-compute-instance"
        key_name: "prod-ssh-key"
        vpc_subnet_id: subnet-5ca1ab1e
        instance_type: c5.large
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-123456
    - name: disabled
      ec2_instance:
        name: "public-compute-instance"
        key_name: "prod-ssh-key"
        vpc_subnet_id: subnet-5ca1ab1e
        instance_type: c5.large
        security_group: default
        network:
          assign_public_ip: false
        image_id: ami-123456
        #checkov:skip=CKV_AWS_135
        ebs_optimized: false
```

Then checkov (2.3.28) crashes:
```
checkov -d .
[ kubernetes framework ]: 100%|████████████████████|[1/1], Current File Scanned=
[ ansible framework ]:   0%|                    |[0/1], Current File Scanned=tes2023-02-20 14:07:00,506 [MainThread  ] [ERROR]  Failed to invoke function /Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/common/runners/runner_registry._parallel_run with <checkov.ansible.runner.Runner object at 0x10be09780>
Traceback (most recent call last):
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/common/parallelizer/parallel_runner.py", line 39, in func_wrapper
    result = original_func(item)
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/common/runners/runner_registry.py", line 103, in _parallel_run
    report = runner.run(
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/common/runners/object_runner.py", line 150, in run
    self.add_python_check_results(report=report, registry=registry, runner_filter=runner_filter, root_folder=root_folder)
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/common/runners/object_runner.py", line 169, in add_python_check_results
    results = registry.scan(file_path, self.definitions[file_path], skipped_checks, runner_filter)  # type:ignore[arg-type] # this is overridden in the subclass
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/yaml_doc/base_registry.py", line 179, in scan
    self._scan_yaml(
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/yaml_doc/base_registry.py", line 127, in _scan_yaml
    skip_info = ([x for x in skipped_checks if (x["id"] == check.id and entity[STARTLINE_MARK] <= x['line_number'] <= entity[ENDLINE_MARK])] or [{}])[0]
  File "/Users/jwoolfenden/Library/Python/3.10/lib/python/site-packages/checkov/yaml_doc/base_registry.py", line 127, in <listcomp>
    skip_info = ([x for x in skipped_checks if (x["id"] == check.id and entity[STARTLINE_MARK] <= x['line_number'] <= entity[ENDLINE_MARK])] or [{}])[0]
TypeError: list indices must be integers or slices, not str
[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=./t

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

By bridgecrew.io | version: 2.3.28
```

**Comment by jimsmith** [comment]
This doesn't allow for supression:

`CKV2_ANSIBLE_1] Ensure that HTTPS url is used with uri`

Does anyone know how to get this working, unless I’m missing something obvious here ? a colleague is thinking something about `CKV2` as well ?

```
- name: do something
  # checkov:skip=CKV2_ANSIBLE_1: development ongoing
  uri:
```

**Comment by jimsmith** [comment]
> @jimsmith I think yours is a different issue, so feel free to open a separate ticket to support skipping `CKV2_*` checks

@gruebel can you let me know why I need to open a separate ticket it's just that I have reported it doesn't work and @JamesWoolfenden as me to put this into the ticket.

As I does not work at a minimum this should have been supported. (thanks)

**Comment by jimsmith** [comment]
@gruebel @JamesWoolfenden  new ticket created.
https://github.com/bridgecrewio/checkov/issues/4573

**Comment by gruebel** [comment]
Sorry for the misunderstanding. This ticket is to fix the actual crash and support the skipping of the normal checks `CKV_*`. The `CKV2_*` checks are so called graph checks and work differently compared to the Python based ones.

When we implement a new framework, then we try to add basic functionality first. This means users can scan the templates and write their own Python checks. Supporting inline skips is not a core feature and is usually added in a later stage. Also adding support for graph checks it something, which comes much later, but was added here right from the beginning.

By implementing things in smaller batches we can see the demand and adoption of new frameworks and decide where we extend the capabilities and where not. And since it is an open source tool, you are always welcome to add the missing functionality 🙂
