### ISSUE TITLE
Docker: ImportError: Bad git executable

### ISSUE THREAD

**Issue by syphernl** [bridgecrewio/checkov#460]
**Describe the bug**
After upgrading to the latest `bridgecrew/checkov:latest` container (`sha256:ab8cd3d5a6d1a0de2ea1762a723e3cec3e71c7340c1d740d564f78859df54bc5`) executing checkov now results in an error:

```bash
$ checkov -d . -o junitxml | tee checkov-report.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 83, in <module>
    refresh()
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 278, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()
All git commands will error until this is rectified.
This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception
Example:
    export GIT_PYTHON_REFRESH=quiet
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 12, in <module>
    from checkov.common.goget.github.get_git import GitGetter
  File "/usr/local/lib/python3.8/site-packages/checkov/common/goget/github/get_git.py", line 3, in <module>
    from git import Repo
  File "/usr/local/lib/python3.8/site-packages/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()
All git commands will error until this is rectified.
This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception
Example:
    export GIT_PYTHON_REFRESH=quiet
```

Earlier today (with container `sha256:a225bb322b8144bf66bce6509f236f528f1ebab1696fb7bc7413c83bab22d413`) we didn't have this problem.  We're have integrated it using [the instructions on your docs](https://www.checkov.io/4.Integrations/gitlab.html).

Changing the entrypoint to:
```
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
      - 'GIT_PYTHON_REFRESH=quiet'
```

It appears that the changes of #456 might have triggered this. Should this info be added to the [gitlab documentation](https://github.com/bridgecrewio/checkov/blob/master/docs/4.Integrations/gitlab.md) or is this considered a bug?

**Comment by schosterbarak** [comment]
@syphernl thank you for reporting this. I'm on it.

**Comment by schosterbarak** [comment]
@syphernl fixed and tested locally. fix should be applied to dockerhub in ~15 min.
