### ISSUE TITLE
ca-certificate param results in an error after the addition of the no-cert-verify param 

### ISSUE THREAD

**Issue by tkishel** [bridgecrewio/checkov#4767]
**Describe the issue**

Using the `ca-certificate` param now results in an error after the release of the `no-cert-verify` param.

**Examples**

```
checkov --prisma-api-url https://api3.prismacloud.io --bc-api-key REDACTED -f main.tf --ca-certificate ~/certs/certifi-globalprotect.cacerts.pem

2023-03-27 09:27:10,610 [MainThread  ] [ERROR]  An SSL error occurred connecting to the platform. If you are on a VPN, please try disabling it and re-running the command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
IsADirectoryError: [Errno 21] Is a directory
```

**Exception Trace**

```sh
2023-03-27 09:27:10,610 [MainThread  ] [ERROR]  An SSL error occurred connecting to the platform. If you are on a VPN, please try disabling it and re-running the command.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
IsADirectoryError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 264, in set_s3_integration
    repo_full_path, response = self.get_s3_role(self.repo_id)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 300, in get_s3_role
    token = self.get_auth_token()
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 642, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 182, in get_auth_token
    request = self.http.request("POST", f"{self.prisma_api_url}/login",  # type:ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api3.prismacloud.io', port=443): Max retries exceeded with url: /login (Caused by SSLError(IsADirectoryError(21, 'Is a directory')))
2023-03-27 09:27:10,618 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 402, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
IsADirectoryError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 404, in ssl_wrap_socket
    raise SSLError(e)
urllib3.exceptions.SSLError: [Errno 21] Is a directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 354, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=self.config.repo_id,
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 251, in setup_bridgecrew_credentials
    self.set_s3_integration()
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 264, in set_s3_integration
    repo_full_path, response = self.get_s3_role(self.repo_id)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 300, in get_s3_role
    token = self.get_auth_token()
  File "/usr/local/lib/python3.10/site-packages/cachetools/__init__.py", line 642, in wrapper
    v = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 182, in get_auth_token
    request = self.http.request("POST", f"{self.prisma_api_url}/login",  # type:ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 78, in request
    return self.request_encode_body(
  File "/usr/local/lib/python3.10/site-packages/urllib3/request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/poolmanager.py", line 376, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api3.prismacloud.io', port=443): Max retries exceeded with url: /login (Caused by SSLError(IsADirectoryError(21, 'Is a directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 371, in run
    self.exit_run()
  File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 578, in exit_run
    exit(0) if self.config.no_fail_on_crash else exit(2)
  File "/usr/local/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 2
```

**Desktop (please complete the following information):**
 - OS: MacOSX, Homebrew 4.0.5, Python 3.10.10
 - Checkov Version 2.3.124

**Additional context**

We should also disable the following warnings with this code:

```
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

as the user has already made this security choice.

```
checkov --prisma-api-url https://api3.prismacloud.io --bc-api-key REDACTED -f main.tf --no-cert-verify

2023-03-27 09:38:09,145 [MainThread  ] [WARNI]  /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api3.prismacloud.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-03-27 09:38:09,322 [MainThread  ] [WARNI]  /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api3.prismacloud.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

2023-03-27 09:38:10,048 [MainThread  ] [WARNI]  /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api3.prismacloud.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[ terraform framework ]: 100%|████████████████████|[1/1], Current File Scanned=main.tf
[ secrets framework ]: 100%|████████████████████|[1/1], Current File Scanned=main.tf
2023-03-27 09:38:14,909 [MainThread  ] [WARNI]  /usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api3.prismacloud.io'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


       _               _              
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V / 
  \___|_| |_|\___|\___|_|\_\___/ \_/  
                                      
By bridgecrew.io | version: 2.3.124 

terraform scan results:

Passed checks: 13, Failed checks: 17, Skipped checks: 0
```

**Comment by tkishel** [comment]
Gah, user error
