### ISSUE TITLE
failed to persist logs stream into S3 bucket due to AccessDenied

### ISSUE THREAD

**Issue by ITProKyle** [bridgecrewio/checkov#4867]
**Describe the issue**

Starting with checkov==2.3.156,  the following error is raised:

```
Passed checks: 5, Failed checks: 0, Skipped checks: 0


More details: https://app3.prismacloud.io/projects?redacted
2023-04-10 12:48:40,518 [MainThread  ] [ERROR]  failed to persist logs stream into S3 bucket bc-scanner-results-890234264427-prod
Traceback (most recent call last):
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/checkov/common/bridgecrew/wrapper.py", line 116, in persist_logs_stream
    s3_client.put_object(Bucket=bucket, Key=object_path, Body=file_io)
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/checkov/main.py", line 644, in <module>
    sys.exit(ckv.run())
             ^^^^^^^^^
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/checkov/main.py", line 578, in run
    bc_integration.persist_logs_stream(logs_stream)
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 508, in persist_logs_stream
    persist_logs_stream(logs_stream, self.s3_client, self.support_bucket, log_path)
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/checkov/common/bridgecrew/wrapper.py", line 116, in persist_logs_stream
    s3_client.put_object(Bucket=bucket, Key=object_path, Body=file_io)
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/e153067/repos/gitlab/ccplat/kyle_finley/example-lab/.venv/lib/python3.11/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

Checking prior versions (2.3.117 & 2.3.155), it is not raised.

If any additional information is needed, please let me know.
I removed the bulk of the output, isolating the exception, to be cautious not to include my employers information.

> **EDIT:** Looks like i can actually reproduce this with 2.3.155 as well but not on macOS. I am getting the same error with 2.3.155 on amazonlinux:2. I am reverting to 2.3.105 for the time being (the version tracked in my lockfile that was working prior to trying to update).

**Desktop (please complete the following information):**
 - OS: mac OS
 - Checkov Version 2.3.156

**Comment by gruebel** [comment]
hey @ITProKyle thanks for reaching out.

This specific code part is only used, when you use `checkov` with the `--support` flag. Was it intentionally?

@mikeurbanski1 didn't you do some adjustments in this area lately?

**Comment by ITProKyle** [comment]
Yes, it is intentional. Our security team (those who require the use of checkov) requested it be added to all checkov scans ran in CI/CD. I believe it was at the recommendation of a support engineer they were working with.
