### ISSUE TITLE
Checkov fail to parse Kubernetes annotations when Suppressing comments are in file

### ISSUE THREAD

**Issue by paulozava** [bridgecrewio/checkov#4977]
**Describe the issue**
Checkov fail to parse Kubernetes annotations when Suppressing comments in file

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Exception Trace**
Here is the output of the run

```python
root@7a94243e1c98:/# checkov -d /app/kubernetes --external-checks-dir /policies/kubernetes --framework kubernetes
2023-04-27 10:33:13,911 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 462, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 102, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/runner.py", line 102, in run
    self.context = build_definitions_context(self.definitions, self.definitions_raw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/kubernetes_utils.py", line 174, in build_definitions_context
    skipped_checks = get_skipped_checks(resource)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/kubernetes_utils.py", line 102, in get_skipped_checks
    logging.debug(f"Parse of Annotation Failed for {metadata['annotations'][key]}: {entity_conf}")
                                                    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 462, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 102, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/runner.py", line 102, in run
    self.context = build_definitions_context(self.definitions, self.definitions_raw)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/kubernetes_utils.py", line 174, in build_definitions_context
    skipped_checks = get_skipped_checks(resource)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/checkov/kubernetes/kubernetes_utils.py", line 102, in get_skipped_checks
    logging.debug(f"Parse of Annotation Failed for {metadata['annotations'][key]}: {entity_conf}")
                                                    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
TypeError: list indices must be integers or slices, not str
```

Here is the file I want to check:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    hasdadsah: haha
  annotations:
    checkov.io/skip1: DUMMY_K8S_001=I have not set CPU limits as I want BestEffort QoS
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

And here is the policy:
```yaml
metadata:
  name: "Dummy Check Kubernetes"
  id: "DUMMY_K8S_001"
  category: "GENERAL_SECURITY"
scope:
  provider: kubernetes
definition:
  cond_type: "attribute"
  resource_types: "all"
  attribute: "metadata.labels.hasdadsah"
  operator: "not_exists"
```

**Desktop (please complete the following information):**
 - Docker - Debian based on image python:3.11.1-buster
 - Checkov Version 2.3.199
 - 
**Additional context**
The policy works fine when no Suppression comment is added to the subject

**Comment by gruebel** [comment]
hey @paulozava thanks for reaching out.

Looks like we don't support custom policies to be suppressed 😄 Currently the policy/check ID has to contain either `CKV_K8S` or `CKV2_K8S` otherwise it comes to this error. I will fix it and it should be released on Sunday/Monday.
