### ISSUE TITLE
Checkov throws an exeception with the latest image

### ISSUE THREAD

**Issue by sm43** [bridgecrewio/checkov#5025]
**Describe the issue**
Explain what you expected to happen when checkov crashed.

with the latest docker image getting an following exception

```
2023-05-03 09:25:35,748 [MainThread  ] [ERROR]  Exception traceback:
09:25:35   Traceback (most recent call last):
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 487, in run
09:25:35       exit_codes.append(self.print_results(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 635, in print_results
09:25:35       return runner_registry.print_reports(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 373, in print_reports
09:25:35       cli_output += report.print_console(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/output/report.py", line 310, in print_console
09:25:35       output_data += record.to_string(compact=is_compact, use_bc_ids=use_bc_ids)
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/output/record.py", line 205, in to_string
09:25:35       "\tFile: {}:{}\n".format(self.file_path, "-".join([str(x) for x in self.file_line_range])), "magenta"
09:25:35   TypeError: 'NoneType' object is not iterable
09:25:35   Traceback (most recent call last):
09:25:35     File "/usr/local/bin/checkov", line 9, in <module>
09:25:35       sys.exit(Checkov().run())
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 487, in run
09:25:35       exit_codes.append(self.print_results(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/main.py", line 635, in print_results
09:25:35       return runner_registry.print_reports(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 373, in print_reports
09:25:35       cli_output += report.print_console(
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/output/report.py", line 310, in print_console
09:25:35       output_data += record.to_string(compact=is_compact, use_bc_ids=use_bc_ids)
09:25:35     File "/usr/local/lib/python3.10/site-packages/checkov/common/output/record.py", line 205, in to_string
09:25:35       "\tFile: {}:{}\n".format(self.file_path, "-".join([str(x) for x in self.file_line_range])), "magenta"
09:25:35   TypeError: 'NoneType' object is not iterable
```

doesn't crash with `bridgecrew/checkov:2.3.211` but noticed the exception with 2.3.219 and later

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
LOG_LEVEL=DEBUG checkov ...
```

**Desktop (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by sm43** [comment]
It seems to be breaking >=2.3.215

**Comment by achiar99** [comment]
@sm43 Can you please provide the tf file that cause the crash?

**Comment by vsviridov** [comment]
I tried with these two env vars and the report printed fine...

**Comment by ChanochShayner** [comment]
@vsviridov Good
So, could you please provide some TF files/resources that failing on this? (+ logs with LOG_LEVEL=DEBUG)
This will help us to understand the issue.

**Comment by ChanochShayner** [comment]
Hey @sm43 and @vsviridov 
I've just merged [this](https://github.com/bridgecrewio/checkov/pull/5036) PR that should solve this issue.
Please upgrade your checkov version to `2.3.222` and let us know if this fixes your issue.

**Comment by sm43** [comment]
`2.3.222` works for me. It doesn't breaks now. Thanks for the quick fix :)

**Comment by vsviridov** [comment]
works for me as well, thank you.

**Comment by ChanochShayner** [comment]
Great! Closing the issue.
