### ISSUE TITLE
Ability using --external-checks-git to define a specific tag for checks to be run from

### ISSUE THREAD

**Issue by PANW-aharrell** [bridgecrewio/checkov#5196]
Having the ability to run specific versions of policies stored in git based on the tag/release associated with that version, as an example running:

`checkov -d . --external-checks-git https://github.com/PANW-aharrell/CCS-External-Checks-Test -b testtag1 -c CKV_COMPLEX_3`

works as expected, but trying to run on this specific tag:

`checkov -d . --external-checks-git https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1 -c CKV_COMPLEX_3`

errors out. Here is the current error:
```
checkov -d . --external-checks-git https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1 -c CKV_COMPLEX_3
2023-06-09 15:31:55,859 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/main.py", line 448, in run
    external_checks_dir = self.get_external_checks_dir()
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/main.py", line 643, in get_external_checks_dir
    external_checks_dir = [git_getter.get()]
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/base_getter.py", line 19, in get
    return self.do_get()
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/github/get_git.py", line 41, in do_get
    self._clone(git_url, clone_dir)
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/github/get_git.py", line 59, in _clone
    Repo.clone_from(git_url, clone_dir, depth=1)
  File "/opt/homebrew/lib/python3.10/site-packages/git/repo/base.py", line 1275, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/git/repo/base.py", line 1194, in _clone
    finalize_process(proc, stderr=stderr)
  File "/opt/homebrew/lib/python3.10/site-packages/git/util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/git/cmd.py", line 559, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --depth=1 https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1 /Users/aharrell/Documents/Checkovdemo/custompolicies/pythonpolicies/88790abb_checks/clone/
  stderr: 'Cloning into '/Users/aharrell/Documents/Checkovdemo/custompolicies/pythonpolicies/88790abb_checks/clone'...
fatal: repository 'https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1/' not found
'
Traceback (most recent call last):
  File "/opt/homebrew/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/main.py", line 448, in run
    external_checks_dir = self.get_external_checks_dir()
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/main.py", line 643, in get_external_checks_dir
    external_checks_dir = [git_getter.get()]
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/base_getter.py", line 19, in get
    return self.do_get()
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/github/get_git.py", line 41, in do_get
    self._clone(git_url, clone_dir)
  File "/Users/aharrell/Library/Python/3.10/lib/python/site-packages/checkov/common/goget/github/get_git.py", line 59, in _clone
    Repo.clone_from(git_url, clone_dir, depth=1)
  File "/opt/homebrew/lib/python3.10/site-packages/git/repo/base.py", line 1275, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, multi_options, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/git/repo/base.py", line 1194, in _clone
    finalize_process(proc, stderr=stderr)
  File "/opt/homebrew/lib/python3.10/site-packages/git/util.py", line 419, in finalize_process
    proc.wait(**kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/git/cmd.py", line 559, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --depth=1 https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1 /Users/aharrell/Documents/Checkovdemo/custompolicies/pythonpolicies/88790abb_checks/clone/
  stderr: 'Cloning into '/Users/aharrell/Documents/Checkovdemo/custompolicies/pythonpolicies/88790abb_checks/clone'...
fatal: repository 'https://github.com/PANW-aharrell/CCS-External-Checks-Test/tree/testtag1/' not found
```

**Comment by gruebel** [comment]
Closing in favour of #4842
