### ISSUE TITLE
Not able  to run Custom Policies for CheckOV in Python

### ISSUE THREAD

**Issue by rusherr02** [bridgecrewio/checkov#5283]
**Describe the issue**
I have created a sample custom rule and wants to run it aganisht my **cft.yaml** file.
I am getting the below error and it seems like when I use the below command it's running everything.
I just want to run my custom aganist one single .yaml file.
please help me for the same.

**Examples**
`from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.cloudformation.checks.resource.base_resource_check import BaseResourceCheck

class DemoCheck(BaseResourceCheck):

    def __init__(self, file):
        name = "Ensure any resource should not have abc"
        id = "CLUMIO_CFT_01"
        supported_resources = ['*']
        categories = [CheckCategories.GENERAL_SECURITY]
        self.file = file
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf, file):
        if 'abc' not in conf.get[file]:
            return CheckResult.PASSED

        return CheckResult.FAILED

scanner = DemoCheck()`
**Command which I used:**
`checkov -d . --external-checks-dir checkov/DemoPolicy`

**My folder structure:**
![image](https://github.com/bridgecrewio/checkov/assets/46245426/5e8feb10-3d35-4a6c-b509-2914b429a7d9)

**Console Output:*
[Console_Output_CV_CustomR.txt](https://github.com/bridgecrewio/checkov/files/11944869/Console_Output_CV_CustomR.txt)
*

I don't know why it's running/testing against all these files, I just need help running checkov custom rules against my file.
thanks

**Comment by rusherr02** [comment]
Getting below error:
`➜  checkov git:(main) ✗ checkov -d . --external-checks-dir checkov/DemoPolicy > output.txt
2023-07-04 11:59:46,145 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,155 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,159 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,180 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,195 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,198 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.
2023-07-04 11:59:46,206 [MainThread  ] [ERROR]  Cannot load external check 'Demo' from checkov/DemoPolicy/Demo.py
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks/base_check_registry.py", line 207, in load_external_checks
    spec.loader.exec_module(module)  # type: ignore[union-attr] # loader can't be None here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/manavmalhotra/PycharmProjects/checkov/checkov/DemoPolicy/Demo.py", line 5, in <module>
    class DemoCheck(BaseResourceCheck):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/multi_signature.py", line 64, in __new__
    raise NotImplementedError(f"The signature {multi_signature_key} for {name} is not supported.")
`

**Comment by gruebel** [comment]
hey @rusherr02 thanks for reaching out.

as you can see in the output `NotImplementedError: The signature (('self', 'conf', 'file'), None, None) for scan_resource_conf is not supported.` your `scan_resource_conf` signature is not supported. Also in the `__init__` you define in a `file` parameter, which doesn't exist and will not work. An other error is inside your code logic `conf.get[file]` this will not work, it is not valid Python syntax. All in all these are Python related errors and have nothing to do with `checkov`.

You can find multiple examples inside `checkov` on how to write your own Python based check https://github.com/bridgecrewio/checkov/tree/main/checkov/cloudformation/checks/resource/aws

**Comment by rusherr02** [comment]
Now I have changed the signature still I am getting the error:
`from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.cloudformation.checks.resource.base_resource_check import BaseResourceCheck


class DemoCheck(BaseResourceCheck):

    def __init__(self):
        name = "Ensure any resource should not have abc"
        id = "C_CFT_01"
        supported_resources = ['*']
        categories = [CheckCategories.GENERAL_SECURITY]
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf):
        if conf.get('Resource') == 'abc':
            return CheckResult.PASSED
        return CheckResult.FAILED
scanner = DemoCheck()`

Error:
`2023-07-05 10:52:47,962 [MainThread  ] [ERROR]  Failed to invoke function /Users/manavmalhotra/env/versions/3.11.3/lib/python3.11/site-packages/checkov/common/runners/runner_registry._parallel_run with <checkov.terraform.runner.Runner object at 0x1295f0910>
Traceback (most recent call last):
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/parallelizer/parallel_runner.py", line 39, in func_wrapper
    result = original_func(item)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 125, in _parallel_run
    report = runner.run(
             ^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/terraform/runner.py", line 117, in run
    self.load_external_checks(external_checks_dir)
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/terraform/runner.py", line 191, in load_external_checks
    self.graph_registry.load_external_checks(directory)
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks_infra/registry.py", line 75, in load_external_checks
    self._load_checks_from_dir(dir, True)
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/checkov/common/checks_infra/registry.py", line 54, in _load_checks_from_dir
    check_yaml = yaml.safe_load(f)
                 ^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/manavmalhotra/.pyenv/versions/3.11.3/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
y`

what's wrong in this?

**Comment by rusherr02** [comment]
How to check/see all possible values for  **supported_resources** ?

**Comment by rusherr02** [comment]
@gruebel I am able to checkov but it's not scanning my custom rule

**Console output:**
`➜  checkov git:(main) ✗ checkov -d . --external-checks-dir ./checkov/checkov-custom-cheks --framework cloudformation --check CKV_CLU_01
[ cloudformation framework ]: 100%|████████████████████|[378/378], Current File Scanned=/checkov/cft.yaml                                                                                                                          
By bridgecrew.io | version: 2.3.311 

cloudformation scan results:

Passed checks: 0, Failed checks: 0, Skipped checks: 0, Parsing errors: 7

Error parsing file ./tests/cloudformation/runner/resources/invalid_properties.yamlֿ
Error parsing file ./tests/cloudformation/runner/resources/invalid_properties.jsonֿ
Error parsing file ./tests/cloudformation/runner/resources/invalid.jsonֿ
Error parsing file ./tests/cloudformation/runner/resources/invalid.yamlֿ
Error parsing file ./tests/cloudformation/parser/cfn_with_ref_bad.yamlֿ
Error parsing file ./tests/cloudformation/parser/success_triple_quotes_string.jsonֿ
Error parsing file ./tests/cloudformation/parser/cfn_bad_name.yamlֿ

`

**Custom rule:**
`from checkov.common.models.enums import CheckResult, CheckCategories
from checkov.cloudformation.checks.resource.base_resource_check import BaseResourceCheck


class TestRule(BaseResourceCheck):
    def __init__(self):
        name = "Clu CFT sample Custom rule"
        id = "CKV_CLU_01"
        supported_resources = ['a']
        categories = [CheckCategories.LOGGING]
        super().__init__(name=name, id=id, categories=categories, supported_resources=supported_resources)

    def scan_resource_conf(self, conf):
        if 'Resources' in conf:
            if 'ClumioDiscoverPolicy' in conf:
                if 'Resource' in conf['ClumioDiscoverPolicy']['Properties']['PolicyDocument']['Statement'] == 'abc':
                    return CheckResult.FAILED
        return CheckResult.PASSED


check = TestRule()
`

Can you please help?

**Comment by rusherr02** [comment]
@gruebel can you please look into this?

**Comment by gruebel** [comment]
you are trying to search for a resource of type `a` I don't think this exists in your CFN template. you either have to use a wildcard or have to write the correct types in the list.

ex.
```python
supported_resources = ["AWS::S3::Bucket", "AWS::Logs::LogGroup"]
```

**Comment by rusherr02** [comment]
Yes it worked with it thanks.
