### ISSUE TITLE
Unable to install checkov on alpine 3.18.2 since ~1 week due to 'Getting requirements to build wheel' error

### ISSUE THREAD

**Issue by RoFz** [bridgecrewio/checkov#5351]
Hi,

started receiving this error on Alpine 3.18.2 since aprox. 1 week.

```
$ pip3 install --upgrade pip && pip3 install --upgrade setuptools
Requirement already satisfied: pip in /usr/lib/python3.11/site-packages (23.1.2)
Collecting pip
  Downloading pip-23.2-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 15.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Requirement already satisfied: setuptools in /usr/lib/python3.11/site-packages (67.7.2)
Collecting setuptools
  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/c7/42/be1c7bbdd83e1bfb160c94b9cafd8e25efc7400346cf7ccdbdb452c467fa/setuptools-68.0.0-py3-none-any.whl.metadata
  Downloading setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
Downloading setuptools-68.0.0-py3-none-any.whl (804 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 804.0/804.0 kB 9.1 MB/s eta 0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
Successfully installed setuptools-68.0.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
$ pip3 install checkov
Collecting checkov
  Obtaining dependency information for checkov from https://files.pythonhosted.org/packages/58/f5/8dde441a40d3f012aa0f55ab80419106891f9fcbcc2fc4b94f8a9e7c4403/checkov-2.3.329-py3-none-any.whl.metadata
  Downloading checkov-2.3.329-py3-none-any.whl.metadata (25 kB)
Collecting bc-python-hcl2==0.3.51 (from checkov)
  Downloading bc_python_hcl2-0.3.51-py3-none-any.whl (14 kB)
Collecting bc-detect-secrets==1.4.29 (from checkov)
  Obtaining dependency information for bc-detect-secrets==1.4.29 from https://files.pythonhosted.org/packages/ba/0f/e2c0156fa3c7436da522d0a903b4e2142e7c45b64ffb159552333b882413/bc_detect_secrets-1.4.29-py3-none-any.whl.metadata
  Downloading bc_detect_secrets-1.4.29-py3-none-any.whl.metadata (23 kB)
Collecting bc-jsonpath-ng==1.5.9 (from checkov)
  Downloading bc_jsonpath_ng-1.5.9-py3-none-any.whl (29 kB)
Collecting deep-merge (from checkov)
  Downloading deep_merge-0.0.4-py3-none-any.whl (5.1 kB)
Collecting tabulate (from checkov)
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting colorama (from checkov)
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting termcolor (from checkov)
  Downloading termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting junit-xml>=1.9 (from checkov)
  Downloading junit_xml-1.9-py2.py3-none-any.whl (7.1 kB)
Collecting dpath==2.1.3 (from checkov)
  Downloading dpath-2.1.3-py3-none-any.whl (17 kB)
Collecting pyyaml>=5.4.1 (from checkov)
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 17.1 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-b067427r/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.
```

Any clues?

**Comment by aaleksandrov** [comment]
I have this too, for me builds ran fine 6 hours ago
I came across this one https://github.com/yaml/pyyaml/issues/601 , looks like `pyyaml` causes failure

**Comment by aaleksandrov** [comment]
This workaround worked for me https://github.com/pypa/pip/issues/12158#issuecomment-1638668908

**Comment by gruebel** [comment]
hey @RoFz thanks for reaching out.

We don't support officially Alpine and don't test against it. I added an info in the docs, but realized I forgot to add it to the main readme. I highly recommend not to use Alpine for large Python projects it is only a matter of time till you won't be able to install it anymore.

**Comment by RoFz** [comment]
Hi @gruebel , could you add here a link to the documentation that contains up-to-date information about the supported OSs, please? It would be most helpful. README.md even mentions Ubuntu 18.04, right after Alpine.
