### ISSUE TITLE
Cannot Skip (or Enforce) Multiple Frameworks

### ISSUE THREAD

**Issue by billyjbryant** [bridgecrewio/checkov#5486]
**Describe the issue**
When running `checkov` from the command line, the flag `--skip-framework` only accepts a single value. Therefore, if you wished to skip multiple frameworks in a scan, one would deduce that you should be able to do so by specifying `--skip-framework <framework>` multiple times for each framework you wish to skip. 

Example:
```bash
checkov --skip-framework secrets --skip-framework sca_image [...remaining cli options]
```

However, this actually results in only the last specified framework to be skipped. Thus in the example above, the `secrets` framework would still be included in the scan and only the `sca_image` framework would be skipped.

This is also the same for `--framework`, wherein it only scans the last provided framework rather than all frameworks supplied. 

**Version (please complete the following information):**
 - Checkov Version 
```
checkov -v
2.4.0
```

**Additional context**
I encountered this issue after attempting to add the `skip-framework` and `framework` functionality into the Checkov VSCode Extension. I require this as my PrismaCloud license does not include the SECRETS or SCA modules and thus I need to be able to ensure that these are skipped, otherwise, I get the following error when trying to use the Checkov VSCode Extension: 

```bash
[debug]: Checkov scan process exited with code 2 
[debug]: Checkov task output: {"stdout":""}
[error]: Error occurred while running a checkov scan {"error":"Checkov exited with code 2"}
[info]: Cancellation token invoked, aborting checkov run. 
[debug]: Getting cached results for hash ecebd6f7eca5ac8bc76d79b6f5960338 
[debug]: Today: 1692860400000 
[debug]: Cache date: 1692860400000 
[debug]: Cache date (1692860400000) is not stale 
[debug]: useCache is true, but did not find cached results for file: /Users/billybryant/break-glass-amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts, hash: ecebd6f7eca5ac8bc76d79b6f5960338 
[info]: Starting to scan. 
[debug]: git remote -v command failed; returning null Command failed: git remote -v
fatal: not a git repository (or any of the parent directories): .git
 {"code":128,"killed":false,"signal":null,"cmd":"git remote -v","stack":"Error: Command failed: git remote -v\nfatal: not a git repository (or any of the parent directories): .git\n\n    at ChildProcess.exithandler (node:child_process:409:12)\n    at ChildProcess.emit (node:events:513:28)\n    at ChildProcess.emit (node:domain:489:12)\n    at maybeClose (node:internal/child_process:1121:16)\n    at Socket.<anonymous> (node:internal/child_process:479:11)\n    at Socket.emit (node:events:513:28)\n    at Socket.emit (node:domain:489:12)\n    at Pipe.<anonymous> (node:net:757:14)\n    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17)"}
[info]: Running checkov: 
[info]: checkov --output-bc-ids -s --bc-api-key **** -f "/Users/billybryant/break-glass-amplify/amplify/backend/types/amplify-dependent-resources-ref.d.ts" --skip-check BC_LIC* -o json --skip-framework secrets --skip-framework sca_package --skip-framework sca_image 
[warn]: Checkov stderr: 2023-08-24 11:19:17,890 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/checkov/2.4.0/libexec/lib/python3.11/site-packages/checkov/main.py", line 572, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/2.4.0/libexec/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 123, in run
    raise ModuleNotEnabledError(f'The framework "{runner_check_type}" is part of the "{self.licensing_integration.get_subscription_for_runner(runner_check_type).name}" module, which is not enabled in the platform')
checkov.common.bridgecrew.platform_errors.ModuleNotEnabledError: ModuleNotEnabledError, The framework "secrets" is part of the "SECRETS" module, which is not enabled in the platform 
 
[warn]: Checkov stderr: Traceback (most recent call last):
  File "/opt/homebrew/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/2.4.0/libexec/lib/python3.11/site-packages/checkov/main.py", line 572, in run
    self.scan_reports = runner_registry.run(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/2.4.0/libexec/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 123, in run
 
[warn]: Checkov stderr:     raise ModuleNotEnabledError(f'The framework "{runner_check_type}" is part of the "{self.licensing_integration.get_subscription_for_runner(runner_check_type).name}" module, which is not enabled in the platform')
checkov.common.bridgecrew.platform_errors.ModuleNotEnabledError: ModuleNotEnabledError, The framework "secrets" is part of the "SECRETS" module, which is not enabled in the platform 
 
[debug]: Checkov scan process exited with code 1 
[debug]: Checkov task output: {"stdout":""}
[error]: Error occurred while running a checkov scan {"error":"Checkov exited with code 1"}
[info]: Cancellation token invoked, aborting checkov run. 
```

**Comment by billyjbryant** [comment]
PR to add the ability to Skip or Include Frameworks via the VSCode Extension: https://github.com/bridgecrewio/checkov-vscode/pull/134

**Comment by billyjbryant** [comment]
I determined that I was sending the parameters incorrectly and that the params accepts a space delimited list. This is resolved.
