### ISSUE TITLE
Index List Out of range error

### ISSUE THREAD

**Issue by aca8089** [bridgecrewio/checkov#5579]
We are getting the following error when scanning the entire directory of the terraform code but if we are scanning a small subsets of directory like modules etc the scan is getting completed but with whole directory it is failing. We are using the checkov latest version as well.

> checkov --directory ./ --soft-fail --output junitxml > /home/vsts/work/1/s/Checkov-Report.xml
========================== Starting Command Output ===========================
[command]/usr/bin/bash /home/vsts/work/_temp/7e30a6ee-476c-4ff7-9d10-063b23135d3f.sh
2023-09-19 05:59:55,641 [MainThread  ] [ERROR]  Failed to invoke function /usr/local/lib/python3.7/dist-packages/checkov/common/runners/runner_registry._parallel_run with <checkov.terraform.runner.Runner object at 0x7fdab29b4a10>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/checkov/common/parallelizer/parallel_runner.py", line 39, in func_wrapper
    result = original_func(item)
  File "/usr/local/lib/python3.7/dist-packages/checkov/common/runners/runner_registry.py", line 133, in _parallel_run
    collect_skip_comments=collect_skip_comments,
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/runner.py", line 93, in run
    create_graph=CHECKOV_CREATE_GRAPH,
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_manager.py", line 86, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 84, in build_graph
    renderer.render_variables_from_local_graph()
  File "/usr/local/lib/python3.7/dist-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 36, in render_variables_from_local_graph
    self._render_variables_from_edges()
  File "/usr/local/lib/python3.7/dist-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 102, in _render_variables_from_edges
    self.evaluate_non_rendered_values()
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 515, in evaluate_non_rendered_values
    self.local_graph.update_vertex_config(vertex, changed_attributes)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 479, in update_vertex_config
    updated_config = update_dictionary_attribute(updated_config, changed_attribute, new_value, dynamic_blocks)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 629, in update_dictionary_attribute
    config[key] = update_dictionary_attribute(inner_config, ".".join(key_parts[1:]), new_value, dynamic_blocks=dynamic_blocks)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 639, in update_dictionary_attribute
    dynamic_blocks=dynamic_blocks
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 667, in update_list_attribute
    config[i] = update_dictionary_attribute(config=config_value, key_to_update=key_to_update, new_value=new_value, dynamic_blocks=dynamic_blocks)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 629, in update_dictionary_attribute
    config[key] = update_dictionary_attribute(inner_config, ".".join(key_parts[1:]), new_value, dynamic_blocks=dynamic_blocks)
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 639, in update_dictionary_attribute
    dynamic_blocks=dynamic_blocks
  File "/usr/local/lib/python3.7/dist-packages/checkov/terraform/graph_builder/local_graph.py", line 662, in update_list_attribute
    inner_config[idx] = new_value
IndexError: list assignment index out of range
##[section]Finishing: Bash

**Comment by gruebel** [comment]
hey @aca8089 thanks for reaching out.

Can't really help without testing it against the actual templates. Looking at the code hints it to trying to evaluate entries in a list.

**Comment by gruebel** [comment]
Feel free to reach out with the needed templates.
