### ISSUE TITLE
CSV output is not compatible with others

### ISSUE THREAD

**Issue by gquintana** [bridgecrewio/checkov#5678]
**Describe the issue**
As soon as csv output is mixed with another one, it fails and raises an error:
```
Traceback (most recent call last):
  File "C:\Work\myapp\.venv\Scripts\checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\main.py", line 519, in run
    exit_codes.append(self.print_results(
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\main.py", line 715, in print_results
    return runner_registry.print_reports(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\common\runners\runner_registry.py", line 574, in print_reports
    csv_sbom_report.persist_report(is_api_key=is_api_key, output_path=config.output_file_path)
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\common\output\csv.py", line 149, in persist_report
    self.persist_report_iac(file_name=FILE_NAME_IAC, output_path=output_path)
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\common\output\csv.py", line 162, in persist_report_iac
    CSVSBOM.write_section(
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\common\output\csv.py", line 201, in write_section
    with open(file, "w", newline="") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'console,reports/csv\\20231023-140630_iac.csv'
```
The command line was:
```
checkov --config-file rules/checkov.yml --skip-download --directory . --output cli --output csv --output-file-path console,reports/csv --soft-fail
```
I tried several combinations:
* cli + junitxml -> OK
* cli +csv -> Fail
* junitxml + csv -> Fail
* csv alone -> OK

**Additional context**

Checkov 2.5.18

**Comment by gquintana** [comment]
Changing the line https://github.com/bridgecrewio/checkov/blob/main/checkov/common/runners/runner_registry.py#L574 with 
```python
            csv_sbom_report.persist_report(is_api_key=is_api_key, output_path=output_formats["csv"])
```
I can got as step further:
```
An error occurred while writing csv results to file: reports\csv
Traceback (most recent call last):
  File "C:\Work\myapp\.venv\Lib\site-packages\checkov\common\runners\runner_registry.py", line 259, in save_output_to_file
    file_path.write_text(data)
  File "C:\Scoop\apps\python\current\Lib\pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Scoop\apps\python\current\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'reports\\csv'
```
Now the fact that `reports/csv` is a directory (and not file) seems to be a problem

**Comment by gruebel** [comment]
hey @gquintana thanks for reaching out.

I think the problem is the usage of the flag `--output-file-path console,reports/csv` because the comma was meant to be used with file paths not folders and CSV creates multiple files, that's why it doesn't work.
