### ISSUE TITLE
SCA Scan with Cyclonedx Output Causes Crash

### ISSUE THREAD

**Issue by hi-artem** [bridgecrewio/checkov#5698]
**Describe the issue**

Running the following command is causing crash:

```sh
checkov --framework sca_package -d .  --bc-api-key $PRISMA_ACCESS_KEY::$PRISMA_SECRET_KEY --repo-id hagopj13/node-express-boilerplate -o cyclonedx
```

**Examples**

Using this repo as an example https://github.com/hagopj13/node-express-boilerplate

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
 LOG_LEVEL=DEBUG checkov --framework sca_package -d .  --bc-api-key $PRISMA_ACCESS_KEY::$PRISMA_SECRET_KEY --repo-id hagopj13/node-express-boilerplate -o cyclonedx

TRUNCATED OUTPUT IS TOO LONG

2023-10-27 09:03:01,435 [MainThread  ] [INFO ]  Finalize repository hagopj13/node-express-boilerplate in bridgecrew's platform
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Getting exit code for report sca_package
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Soft fail severity threshold: None
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Soft fail checks: []
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Hard fail severity threshold: None
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Hard fail checks: []
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  Use enforcement rules is FALSE
2023-10-27 09:03:01,436 [MainThread  ] [DEBUG]  In get_exit_code; exit code thresholds: {'soft_fail': False, 'soft_fail_checks': [], 'soft_fail_threshold': None, 'hard_fail_checks': [], 'hard_fail_threshold': None}, hard_fail_on_parsing_errors: False
2023-10-27 09:03:01,437 [MainThread  ] [DEBUG]  There are failed checks and all soft/hard fail args are empty - returning 1
2023-10-27 09:03:01,450 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/main.py", line 554, in run
    exit_codes.append(self.print_results(
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/main.py", line 773, in print_results
    return runner_registry.print_reports(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 526, in print_reports
    cyclonedx = CycloneDX(repo_id=metadata_integration.bc_integration.repo_id, reports=cyclonedx_reports)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 64, in __init__
    self.bom = self.create_bom()
               ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 112, in create_bom
    vulnerability = self.create_vulnerability(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 287, in create_vulnerability
    vulnerability = self.create_cve_vulnerability(resource=resource, component=component)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 408, in create_cve_vulnerability
    affects=[BomTarget(ref=component.bom_ref.value)],
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bom_ref'
Traceback (most recent call last):
  File "/opt/homebrew/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/main.py", line 554, in run
    exit_codes.append(self.print_results(
                      ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/main.py", line 773, in print_results
    return runner_registry.print_reports(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 526, in print_reports
    cyclonedx = CycloneDX(repo_id=metadata_integration.bc_integration.repo_id, reports=cyclonedx_reports)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 64, in __init__
    self.bom = self.create_bom()
               ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 112, in create_bom
    vulnerability = self.create_vulnerability(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 287, in create_vulnerability
    vulnerability = self.create_cve_vulnerability(resource=resource, component=component)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/checkov/common/output/cyclonedx.py", line 408, in create_cve_vulnerability
    affects=[BomTarget(ref=component.bom_ref.value)],
                           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bom_ref'
```

**Desktop (please complete the following information):**
 - OS: OSX
 - Checkov Version 3.0.7

**Additional context**
Scan works with CSV output

**Comment by gruebel** [comment]
hey @hi-artem thanks for reaching out.

I can confirm this is a bug, resulting from a transitive dependency, which exists multiple times.
