### ISSUE TITLE
Checkov 3.0.10 crashes

### ISSUE THREAD

**Issue by SebastianBalle** [bridgecrewio/checkov#5719]
**Describe the issue**
Explain what you expected to happen when checkov crashed.

**Examples**
Please share an example code sample (in the IaC of your choice) + the expected outcomes.

Binary crashes listing version.

**Exception Trace**
Please share the trace for the exception and all relevant output by checkov.
To maximize the understanding, please run checkov with LOG_LEVEL set to debug
as follows:
```sh
$ LOG_LEVEL=DEBUG checkov --version                                                                                                                                            

2023-11-03 10:08:18,039 [MainThread  ] [DEBUG]  Leveraging the bundled IAM Definition.
2023-11-03 10:08:18,039 [MainThread  ] [DEBUG]  Leveraging the IAM definition at /opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/policy_sentry/shared/data/iam-definition.json
Traceback (most recent call last):
  File "/opt/homebrew/bin/checkov", line 2, in <module>
    from checkov.main import Checkov
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/main.py", line 22, in <module>
    from checkov.ansible.runner import Runner as ansible_runner
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/ansible/runner.py", line 7, in <module>
    from checkov.ansible.graph_builder.local_graph import AnsibleLocalGraph
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/ansible/graph_builder/local_graph.py", line 14, in <module>
    from checkov.ansible.utils import get_scannable_file_paths, TASK_RESERVED_KEYWORDS, parse_file
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/ansible/utils.py", line 13, in <module>
    from checkov.common.util.suppression import collect_suppressions_for_context
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/util/suppression.py", line 6, in <module>
    from checkov.common.bridgecrew.integration_features.features.policy_metadata_integration import (
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/integration_features/__init__.py", line 1, in <module>
    from checkov.common.bridgecrew.integration_features.features import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/integration_features/features/policy_metadata_integration.py", line 9, in <module>
    from checkov.common.bridgecrew.platform_integration import bc_integration
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/platform_integration.py", line 37, in <module>
    from checkov.common.runners.base_runner import filter_ignored_paths
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/runners/base_runner.py", line 16, in <module>
    from checkov.common.output.report import Report
  File "/opt/homebrew/Cellar/checkov/3.0.10/libexec/lib/python3.12/site-packages/checkov/common/output/report.py", line 12, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'
```

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0 (23A344)
 - Checkov Version: 3.0.10 (latest stable homebrew)
 - Python version: 3.12.0

**Additional context**
Add any other context about the problem here (e.g. code snippets).

**Comment by SebastianBalle** [comment]
Modified local version of Python from 3.11.2 to 3.12.0 and the error remains.

**Comment by SebastianBalle** [comment]
@gruebel 

The error also occurs when installing the latest 3.0.19 using pip.

**Comment by jouve** [comment]
same issue with homebrew, I reinstalled python-tabulate & python-markupsafe and it fixed the issue

**Comment by SebastianBalle** [comment]
> same issue with homebrew, I reinstalled python-tabulate & python-markupsafe and it fixed the issue

Thank you that worked. I ran the following commands:
```sh
brew uninstall --ignore-dependencies python-tabulate
brew uninstall --ignore-dependencies python-markupsafe
brew install python-tabulate
brew link --overwrite python-tabulate
brew install python-markupsafe
brew link --overwrite python-markupsafe

checkov --version
```
