### ISSUE TITLE
Question: Intended use case for binaries included with releases

### ISSUE THREAD

**Issue by Nathan-Yorio** [bridgecrewio/checkov#5728]
I see that there are binaries included in each release automatically built in the actions workflow.

What is the intended use case for these binaries? If there is one, what is the recommended way to implement them? They would help greatly if I could download them as standalone binaries instead of installing all python dependencies in some container images I'm building but they're not mentioned anywhere in the install documentation.

 When I try to run the x86 linux binary on my local machine I get the following output (which says to me these aren't actually dependency resolved standalone binaries)

```
Traceback (most recent call last):
  File "checkov/main.py", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "checkov/common/runners/runner_registry.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "checkov/common/output/spdx.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/spdx/writer/tagvalue/tagvalue_writer.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/spdx/writer/write_utils.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/spdx/validation/document_validator.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/spdx/validation/file_validator.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/spdx/validation/license_expression_validator.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 391, in exec_module
  File "spdx_tools/common/spdx_licensing.py", line 7, in <module>
  File "license_expression/__init__.py", line 820, in get_spdx_licensing
  File "license_expression/__init__.py", line 833, in get_license_index
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIl2iov4/license_expression/data/scancode-licensedb-index.json'
[68232] Failed to execute script 'main' due to unhandled exception!
```

So, my question is mainly what are these supposed to be for and should I stop even considering them as a potential way to install checkov?

My personal ideal use case for a binary would be to just `curl` the archive and place it in /usr/bin so that I can call it from my container without actually needing to do something along these lines

```
ARG PYTHON_VERSION=3.9.2-3
ARG PIP_VERSION=20.3.4-4+deb11u1
RUN <<EOT bash
  apt-get update
  apt-get install --no-install-suggests --no-install-recommends --yes python3=${PYTHON_VERSION} python3-pip=${PIP_VERSION}
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

ARG CHECKOV_VERSION=2.4.58
RUN pip3 install --no-cache-dir checkov==${CHECKOV_VERSION}
```

**Comment by gruebel** [comment]
hey @Nathan-Yorio thanks for reaching out.

The binaries are an alternative way of installing `checkov`, which includes all dependencies + the runtime as I remember. From the error I can see a dependency is missing its internal "database", which is a JSON file, this needs to be fixed 🙂
