### ISSUE TITLE
dataclasses backport required for Python 3.6

### ISSUE THREAD

**Issue by timhourigan** [bridgecrewio/checkov#575]
**Describe the bug**
Since #567, `dataclasses` is being used. This module is not in Python 3.6, so the [backport](https://pypi.org/project/dataclasses/) needs to be installed.

**To Reproduce**

```shell
$ python --version
> python 3.6.11
$ python -m venv .env
> ...
$ source .venv/bin/activate
$ pip install checkov
> ...
$ checkov --version

Traceback (most recent call last):
  File "/tmp/test/.env/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/main.py", line 15, in <module>
    from checkov.common.util.docs_generator import print_checks
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/common/util/docs_generator.py", line 11, in <module>
    from checkov.serverless.registry import sls_registry
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/__init__.py", line 1, in <module>
    from checkov.serverless.checks.function import *
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/checks/__init__.py", line 3, in <module>
    from checkov.serverless.checks.function import *
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/checks/function/__init__.py", line 1, in <module>
    from checkov.serverless.checks.function.aws import *
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/checks/function/aws/StarActionPolicyDocument.py", line 1, in <module>
    from checkov.serverless.checks.function.base_function_check import BaseFunctionCheck
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/checks/function/base_function_check.py", line 5, in <module>
    from checkov.serverless.checks.function.registry import function_registry
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/checks/function/registry.py", line 1, in <module>
    from checkov.serverless.base_registry import ServerlessRegistry
  File "/tmp/test/.env/lib/python3.6/site-packages/checkov/serverless/base_registry.py", line 2, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses
#
# To resolve
#
$ pip install dataclasses
$ checkov --version
1.0.544
```

**Expected behavior**
`setup.py` should have a dependency for `dataclasses`, if the Python version is `3.6`.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Checkov Version 1.0.544

**Comment by schosterbarak** [comment]
We would accept a contribution to solving that. 
As a workaround: We are currently running checkov with python 3.7 and it works :)

**Comment by robeden** [comment]
The `pipfile` says python 3.7 is required. If 3.6 is supported that should be updated.

**Comment by timhourigan** [comment]
Reading `setup.py` I'd assumed `3.6` was also supported, but maybe that is out of date?

https://github.com/bridgecrewio/checkov/blob/a737202c62b71ed48c1ee56e1405925567b084b0/setup.py#L104

I'm happy to do a PR to add `dataclasses` to `install_requires` in the case of `3.6`, but you might prefer to say `>=3.7` only?

Note, I can solve the issue locally by either adding `dataclasses` to my dependencies or using Python 3.7/3.8, so it isn't a blocker.

**Comment by schosterbarak** [comment]
let's update setup.py to support only python 3.7 and above.

**Comment by schosterbarak** [comment]
@timhourigan do you want to open a PR on that or should I?

**Comment by timhourigan** [comment]
@schosterbarak It may be cleaner if you raise the PR, as I'm assuming the `README.md` may need to mention `>=3.7` now?

**Comment by schosterbarak** [comment]
np. on it.

**Comment by schosterbarak** [comment]
Done. @timhourigan thank you for reporting this.

**Comment by nhairs** [comment]
If `dataclasses` is the only 3.7 feature being used, it is possible to modify the `setup.py` `packages` to conditionally install it on 3.6 (we'd then need to update the `python_requires` as well).

If anyone know's if this is the case I'd be happy to create a PR that does this (or provide details).
(I'd add the snippet but I'm at work).
