### ISSUE TITLE
ValueError: Credentials for client are not set

### ISSUE THREAD

**Issue by ramsharan-choudhary-bzy** [bridgecrewio/checkov#5772]
**Describe the issue**
Using checkov in github actions, using below command to installing checkov
-> pip3 install checkov

**Examples**
This is the command I am executing.
-> checkov -f us-dev.plan.json -o sarif -o github_failed_only --output-file-path checkov_result -s --skip-check CKV2_AZURE_33,CKV2_AZURE_32

**Version (please complete the following information):**
 - Checkov Version [e.g. 22]

**Additional context**
Error: -20 13:37:45,538 [MainThread  ] [ERROR]  Exception traceback:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line [12](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:13)5, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run
    report = runner.run(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/secrets/runner.py", line [13](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:14)1, in run
    bc_integration.set_s3_client()
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client
    raise ValueError("Credentials for client are not set")
ValueError: Credentials for client are not set
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/main.py", line 634, in run
    self.scan_reports = runner_registry.run(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line [15](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:16)8, in run
    parallel_runner_results = parallel_runner.run_function(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 52, in run_function
    return self._run_function_multiprocess_spawn(func, items, group_size)
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 1[22](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:23), in _run_function_multiprocess_spawn
    return p.starmap(func, items, chunksize=group_size)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: Credentials for client are not set
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 1[25](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:26), in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run
    report = runner.run(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/secrets/runner.py", line 1[31](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:32), in run
    bc_integration.set_s3_client()
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client
    raise ValueError("Credentials for client are not set")
ValueError: Credentials for client are not set
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/.local/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/main.py", line 6[34](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:35), in run
    self.scan_reports = runner_registry.run(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/runners/runner_registry.py", line 158, in run
    parallel_runner_results = parallel_runner.run_function(
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 52, in run_function
    return self._run_function_multiprocess_spawn(func, items, group_size)
  File "/home/runner/.local/lib/python3.10/site-packages/checkov/common/parallelizer/parallel_runner.py", line 122, in _run_function_multiprocess_spawn
    return p.starmap(func, items, chunksize=group_size)
  File "/usr/lib/python3.10/multiprocessing/pool.py", line [37](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:38)5, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line [77](https://github.com/beazley/devops-azure-terraform-uw-lz/actions/runs/6867076719/job/18851391367#step:15:78)4, in get
    raise self._value
ValueError: Credentials for client are not set

**Comment by gruebel** [comment]
will be fixed with version 3.1.2

**Comment by kozmic** [comment]
When is version 3.1.2 scheduled for release? This change here has basically broken `checkov` for non-bridgecrew customers.

**Comment by kozmic** [comment]
FYI @gruebel ☝️  (sorry I forgot to tag you in my original comment)

**Comment by gruebel** [comment]
It should be already released on `pypi`, the image is created a few minutes later. And it didn't break for all non-bridgecrew users, only if you used the `secrets` framework.

**Comment by ramsharan-choudhary-bzy** [comment]
@gruebel  is this some faulty patch release this issue occurs, looks like this was working till last week.

**Comment by jmk47912204** [comment]
@gruebel - Yes, we are also facing the same issue with the latest tag. As a temporary workaround, we are using 3.0.40 tag to bypass this issue

Would be nice to have this fix on the **latest** tag since we have already included checkov stage in our pipeline via libraries to all of our projects

**Comment by gruebel** [comment]
This was a minor release and we typically include possible breaking changes with a minor release. If you have sensitive workflows, then you always should upper bound to the next minor release or pin it and test newer versions on less sensitive workflows or on a periodical basis.

**Comment by tknisch** [comment]
@gruebel we are also using GitHub actions. How do we should use the upper bound as the versioning of the GitHub Actions is completely different?

**Comment by gruebel** [comment]
easy, pin it to a commit hash, like you should do, if you want to have a secure GHA workflow https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies

> For GitHub workflows used in building and releasing your project, pin dependencies by hash. See [main.yaml](https://github.com/ossf/scorecard/blob/f55b86d6627cc3717e3a0395e03305e81b9a09be/.github/workflows/main.yml#L27) for example. To determine the permissions needed for your workflows, you may use [StepSecurity's online tool](https://app.stepsecurity.io/secureworkflow/) by ticking the "Pin actions to a full length commit SHA". You may also tick the "Restrict permissions for GITHUB_TOKEN" to fix issues found by the Token-Permissions check.
