### ISSUE TITLE
Currently tagged docker latest c08499f01d2c68c5f045cf7bacdb3a21dc95c3335cbb423d1976b8de66611050 appears broken

### ISSUE THREAD

**Issue by jamiegosling** [bridgecrewio/checkov#5774]
**Describe the issue**
Pulling the docker sha c08499f01d2c68c5f045cf7bacdb3a21dc95c3335cbb423d1976b8de66611050 which is currently tagged as latest results in an error when trying to run checkov

**Examples**
running checkov -d against the root of a set of terraform

**Exception Trace**
```sh
2023-11-20 14:20:06,429 [MainThread  ] [ERROR]  Exception traceback:

multiprocessing.pool.RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker

    result = (True, func(*args, **kwds))

                    ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar

    return list(itertools.starmap(args[0], args[1]))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run

    report = runner.run(

             ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/sast/runner.py", line 53, in run

    bc_integration.set_s3_client()

  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client

    raise ValueError("Credentials for client are not set")

ValueError: Credentials for client are not set

"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 523, in run

    self.scan_reports = runner_registry.run(

                        ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 158, in run

    parallel_runner_results = parallel_runner.run_function(

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/parallelizer/parallel_runner.py", line 52, in run_function

    return self._run_function_multiprocess_spawn(func, items, group_size)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/parallelizer/parallel_runner.py", line 122, in _run_function_multiprocess_spawn

    return p.starmap(func, items, chunksize=group_size)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 375, in starmap

    return self._map_async(func, iterable, starmapstar, chunksize).get()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get

    raise self._value

ValueError: Credentials for client are not set

multiprocessing.pool.RemoteTraceback: 

"""

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 125, in worker

    result = (True, func(*args, **kwds))

                    ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar

    return list(itertools.starmap(args[0], args[1]))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run

    report = runner.run(

             ^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/sast/runner.py", line 53, in run

    bc_integration.set_s3_client()

  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client

    raise ValueError("Credentials for client are not set")

ValueError: Credentials for client are not set

"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "/usr/local/bin/checkov", line 9, in <module>

    sys.exit(Checkov().run())

             ^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/main.py", line 523, in run

    self.scan_reports = runner_registry.run(

                        ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/runners/runner_registry.py", line 158, in run

    parallel_runner_results = parallel_runner.run_function(

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/parallelizer/parallel_runner.py", line 52, in run_function

    return self._run_function_multiprocess_spawn(func, items, group_size)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/checkov/common/parallelizer/parallel_runner.py", line 122, in _run_function_multiprocess_spawn

    return p.starmap(func, items, chunksize=group_size)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 375, in starmap

    return self._map_async(func, iterable, starmapstar, chunksize).get()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/multiprocessing/pool.py", line 774, in get

    raise self._value

ValueError: Credentials for client are not set

```

**Desktop (please complete the following information):**
 - OS: linux/amd64
 - Checkov Version 3

**Comment by gareth-e** [comment]
I also see this error.
Tests that were running OK last week on version 3.0.38 are now failing with this error (on version 3.1.1).
