### ISSUE TITLE
regression run failure with 3.1.0

### ISSUE THREAD

**Issue by chenrui333** [bridgecrewio/checkov#5784]
👋 trying to build the 3.1.0 release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
==> /opt/homebrew/Cellar/checkov/3.1.0/bin/checkov -f /private/tmp/checkov-test-20231120-22742-1k8j752/test.tf 2>&1
  Error: -20 20:53:26,071 [MainThread  ] [ERROR]  Exception traceback:
  Error: test failed
  multiprocessing.pool.RemoteTraceback: 
  """
  Traceback (most recent call last):
    File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line 125, in worker
      result = (True, func(*args, **kwds))
                      ^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/pool.py", line [51](https://github.com/Homebrew/homebrew-core/actions/runs/6938043234/job/18873191365#step:3:52), in starmapstar
      return list(itertools.starmap(args[0], args[1]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/common/runners/runner_registry.py", line 788, in _parallel_run
      report = runner.run(
               ^^^^^^^^^^^
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/secrets/runner.py", line 131, in run
      bc_integration.set_s3_client()
    File "/opt/homebrew/Cellar/checkov/3.1.0/libexec/lib/python3.12/site-packages/checkov/common/bridgecrew/platform_integration.py", line 397, in set_s3_client
      raise ValueError("Credentials for client are not set")
  ValueError: Credentials for client are not set
  """
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6938043234/job/18873191365
relates to Homebrew/homebrew-core#154982

---

I suspect root cause is with this PR, https://github.com/bridgecrewio/checkov/pull/5763

cc @Saarett

**Comment by gruebel** [comment]
I recommend to use version 3.1.3+ the versions 3.1.0-3.1.2 can only be run, if `secrets` and `sast` frameworks are excluded or when an API key is used.

**Comment by chenrui333** [comment]
Looks like 3.1.9 works for me, thanks!
