### ISSUE TITLE
Checkov missing default bc_api_url

### ISSUE THREAD

**Issue by MichalP574** [bridgecrewio/checkov#6053]
Hi, I'm not sure if this (https://github.com/bridgecrewio/checkov/pull/5961/files ) is related to my issue with Checkov GitHub Action, but I'm getting the following error:
checkov -d . --output sarif --output-file-path /github/workspace/results.sarif --download-external-modules true --framework terraform

2024-02-15 07:18:56,235 [MainThread ] [WARNI] Failed to get the checkov mappings and guidelines from None/bridgecrew/api/v2/guidelines. Skips using BC_* IDs will not work. Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn sock = connection.create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 60, in create_connection for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ socket.gaierror: [Errno -2] Name or service not known.
File: checkov/common/bridgecrew/platform_integration.py 
 -       self.bc_api_url = normalize_bc_url(os.getenv('BC_API_URL', "https://www.bridgecrew.cloud"))
 -       self.prisma_api_url = normalize_prisma_url(os.getenv("PRISMA_API_URL"))
 +      self.bc_api_url = normalize_bc_url(os.getenv('BC_API_URL'))
The workflow runs as expected but there are no help URLs. For the time being, I use env: BC_API_URL:  Thank you in advance for your response!

**Comment by naveednawazkhan** [comment]
bridgecrew.cloud has been deprecated. If you're using Prisma Cloud follow this [doc](https://docs.prismacloud.io/en/classic/appsec-admin-guide/get-started/connect-your-repositories/ci-cd-runs/add-github-actions)

For open-source checkov, you can use the below docs.
https://www.checkov.io/4.Integrations/GitHub%20Actions.html#use-a-checkov-action-from-the-marketplace

**Comment by MichalP574** [comment]
Hi, I encountered an issue when trying to use the open-source tool Checkov; I received the error mentioned previously. As a result, I had to configure the environment variable as follows to make the GitHub Action workflow work correctly:
```
env:
  BC_API_URL: https://www.bridgecrew.cloud
```

The error does not occur in Bitbucket pipelines.
