### ISSUE TITLE
No flag for non-interactive mode

### ISSUE THREAD

**Issue by michal-adamkiewicz** [bridgecrewio/checkov#609]
**Describe the bug**
During weekend something has changed, although I didn't touch my code inside CI/CD (gitlab).
Suddenly I started to see at the end of checks dialog like this:

```bash Visualize and collaborate on these issues with Bridgecrew! 
Bridgecrew's dashboard allows automation of future checks, Pull Request scanning and auto-comments, automatic remidiation PR's and more! Plus it's free for 100 Terraform objects and a great way to visualize and collaborate on these results. To instantly see this scan in the platform, Press y! 
 
Visualize results? (y/n): Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 71, in run
    runner_registry.print_reports(scan_reports, args)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 58, in print_reports
    self.bc_platform.onboarding(args,scan_reports)
  File "/usr/local/lib/python3.8/site-packages/checkov/common/bridgecrew/platform_integration.py", line 210, in onboarding
    reply = self._input_visualize_results()
  File "/usr/local/lib/python3.8/site-packages/checkov/common/bridgecrew/platform_integration.py", line 320, in _input_visualize_results
    result = str(input('Visualize results? (y/n): ')).lower().strip()  # nosec
EOFError: EOF when reading a line`

**Comment by schosterbarak** [comment]
thanks @michal-adamkiewicz  i'll revert this change noow

**Comment by michal-adamkiewicz** [comment]
Np 👍 
I'm super fan of this solution anyway! 💯 :)

**Comment by schosterbarak** [comment]
Hi @michal-adamkiewicz can you install latest and try again?

**Comment by michal-adamkiewicz** [comment]
Yeah it's working again. Thanks a lot @schosterbarak
