### ISSUE TITLE
Checkov crash

### ISSUE THREAD

**Issue by msl0** [bridgecrewio/checkov#6260]
**Describe the issue**
Checkov does not start

**Examples**
I try to run `checkov` command in empty directory.

**Exception Trace**
```
$ LOG_LEVEL=DEBUG checkov
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import Checkov
  File "/usr/local/lib/python3.8/dist-packages/checkov/main.py", line 22, in <module>
    from checkov.ansible.runner import Runner as ansible_runner
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/runner.py", line 7, in <module>
    from checkov.ansible.graph_builder.local_graph import AnsibleLocalGraph
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/graph_builder/local_graph.py", line 14, in <module>
    from checkov.ansible.utils import get_scannable_file_paths, TASK_RESERVED_KEYWORDS, parse_file
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/utils.py", line 13, in <module>
    from checkov.common.util.suppression import collect_suppressions_for_context
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/util/suppression.py", line 6, in <module>
    from checkov.common.bridgecrew.integration_features.features.policy_metadata_integration import (
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/integration_features/__init__.py", line 1, in <module>
    from checkov.common.bridgecrew.integration_features.features import *  # noqa
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/integration_features/features/repo_config_integration.py", line 9, in <module>
    from checkov.common.bridgecrew.platform_integration import bc_integration
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 1414, in <module>
    bc_integration = BcPlatformIntegration()
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 111, in __init__
    self.clean()
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 147, in clean
    self.http_retry = urllib3.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

**Desktop (please complete the following information):**
 - OS: Ununtu 20.04
 - Checkov Version: 3.2.65

**Additional context**
```
$ python3 --version
Python 3.8.10
```

**Comment by deeps-sf** [comment]
@msl0 Thank you for reaching out. Is it still crashing?
If yes, could you please try to upgrade checkov and test?

to upgrade with pip3:
pip3 install -U checkov

with Homebrew:
brew upgrade checkov

**Comment by msl0** [comment]
It works after updating to version 3.2.88

**Comment by deeps-sf** [comment]
@msl0 Glad it is working as expected now.
thank you.

**Comment by robertbrandso** [comment]
For others finding this issue. I had almost the same error message:

```
File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import Checkov
  File "/usr/local/lib/python3.8/dist-packages/checkov/main.py", line 22, in <module>
    from checkov.ansible.runner import Runner as ansible_runner
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/runner.py", line 9, in <module>
    from checkov.ansible.graph_builder.local_graph import AnsibleLocalGraph
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/graph_builder/local_graph.py", line 14, in <module>
    from checkov.ansible.utils import get_scannable_file_paths, TASK_RESERVED_KEYWORDS, parse_file
  File "/usr/local/lib/python3.8/dist-packages/checkov/ansible/utils.py", line 16, in <module>
    from checkov.common.util.suppression import collect_suppressions_for_context
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/util/suppression.py", line 6, in <module>
    from checkov.common.bridgecrew.integration_features.features.policy_metadata_integration import (
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/integration_features/__init__.py", line 1, in <module>
    from checkov.common.bridgecrew.integration_features.features import *  # noqa
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/integration_features/features/custom_policies_integration.py", line 11, in <module>
    from checkov.common.bridgecrew.platform_integration import bc_integration
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 1453, in <module>
    bc_integration = BcPlatformIntegration()
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 112, in __init__
    self.clean()
  File "/usr/local/lib/python3.8/dist-packages/checkov/common/bridgecrew/platform_integration.py", line 148, in clean
    self.http_retry = urllib3.Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```

The solution in my case was to upgrade *urllib3*:
`pip3 install --upgrade urllib3`
