### ISSUE TITLE
Add an option to either stop checkov connecting to prizmacloud API endpoint or to suppress warning when connection is no available.

### ISSUE THREAD

**Issue by DiemanXT** [bridgecrewio/checkov#6755]
**Describe the feature**

Suppress warning when prizmacloud API can't be reached.

I am running Chekov in air-gapped environment that has no connection to the internet. While Checkov runs fine I am getting below warning. There is no option to either instruct checkov not to connect to api endpoint or to suppress that warning. I do not want to suppress all warnings - just this one.

$ checkov --directory . --output-file-path /tmp/checkov_report/checkov_report.json
2024-10-07 10:19:54,565 [MainThread  ] [WARNI]  Failed to get the checkov mappings and guidelines from https://api0.prismacloud.io/bridgecrew/api/v2/guidelines. Skips using BC_* IDs will not work.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line [61](https://natwest.gitlab-dedicated.com/natwestgroup/DigitalX/DataAndAnalytics/DataTechnology/DEDevOps/aws-recp-dedevops/-/jobs/12395676#L61)1, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f10ced48b90>, 'Connection to api0.prismacloud.io timed out. (connect timeout=3.1)')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 12[73](https://natwest.gitlab-dedicated.com/natwestgroup/DigitalX/DataAndAnalytics/DataTechnology/DEDevOps/aws-recp-dedevops/-/jobs/12395676#L73), in get_public_run_config
    request = self.http.request("GET", self.guidelines_api_url, headers=headers)  # type:ignore[no-untyped-call]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 110, in request
    return self.request_encode_url(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 8[75](https://natwest.gitlab-dedicated.com/natwestgroup/DigitalX/DataAndAnalytics/DataTechnology/DEDevOps/aws-recp-dedevops/-/jobs/12395676#L75), in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 875, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api0.prismacloud.io', port=443): Max retries exceeded with url: /bridgecrew/api/v2/guidelines (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f10ced48b[90](https://natwest.gitlab-dedicated.com/natwestgroup/DigitalX/DataAndAnalytics/DataTechnology/DEDevOps/aws-recp-dedevops/-/jobs/12395676#L90)>, 'Connection to api0.prismacloud.io timed out. (connect timeout=3.1)'))

**Additional context**

As I understand the only drawback from not having that integration would be lack of links to guides for errors identified and ability to visualise output via prizmacloud UI. I do not need either.

**Comment by gruebel** [comment]
hey @DiemanXT this is probably what you are looking for https://github.com/bridgecrewio/checkov/blob/51c5054daba4e5de158525c6182ebe6a51856633/docs/2.Basics/CLI%20Command%20Reference.md?plain=1#L42

**Comment by DiemanXT** [comment]
that made it, thank you @gruebel. 
I wonder if you might be able to help me with something that might be related.
While warning is not there anymore I now noticed that all findings that checkov is reported have severity "unknown". Do you know what is going on?

**Comment by DiemanXT** [comment]
Hi @gruebel ,

I've got access to API working now though severity is still showing as unknown. I can see guidance links in the output (previously they were not there).

**Comment by DiemanXT** [comment]
Looks like severity info is paid information that requires APi key... shame
