### ISSUE TITLE
Missing `protocol` key for `aws_lb_listener`

### ISSUE THREAD

**Issue by StayPirate** [bridgecrewio/checkov#680]
**Describe the bug**
protocol is not a valid key for `aws_lb_listener`

**To Reproduce**
snippet
```hcl
resource "aws_lb_listener" "http_redirector" {
  load_balancer_arn = aws_lb.redirector.arn
  port              = "80"
  protocol          = "HTTP" #tfsec:ignore:AWS004
  default_action {
    type = "redirect"
    redirect {
      host        = "example.com"
      status_code = "HTTP_302"
    }
  }
}
```
Traceback
```
Traceback (most recent call last):
  File "/home/user/.config/pyenv/versions/checkov/bin/checkov", line 5, in <module>
    run()
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/main.py", line 65, in run
    files=file, guidelines=guidelines)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 31, in run
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/runner.py", line 61, in run
    self.check_tf_definition(report, root_folder, runner_filter, collect_skip_comments)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/runner.py", line 90, in check_tf_definition
    scanned_file, runner_filter)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/runner.py", line 98, in run_all_blocks
    scanned_file, block_type, runner_filter)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/runner.py", line 136, in run_block
    results = registry.scan(scanned_file, entity, skipped_checks, runner_filter)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 103, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/common/checks/base_check_registry.py", line 110, in run_check
    entity_name=entity_name, entity_type=entity_type, skip_info=skip_info)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 58, in run
    raise e
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/common/checks/base_check.py", line 39, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 16, in scan_entity_conf
    return self.scan_resource_conf(conf, entity_type)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 28, in wrapper
    return wrapped(self, conf)
  File "/home/user/.config/pyenv/versions/3.7.9/envs/checkov/lib/python3.7/site-packages/checkov/terraform/checks/resource/aws/ALBListenerHTTPS.py", line 29, in scan_resource_conf
    if default_action['redirect'][0]['protocol'] == ['HTTPS']:
KeyError: 'protocol'
```

**Expected behavior**
Test should pass

**Desktop (please complete the following information):**
 - Python: 3.7.9
 - Checkov Version 1.0.636

**Comment by nimrodkor** [comment]
Thanks for reporting @StayPirate !

We'll include a fix for this in the next version of checkov. See the linked PR
