### ISSUE TITLE
No module named 'packaging'

### ISSUE THREAD

**Issue by benjiprod** [bridgecrewio/checkov#685]
**Describe the bug**
Since latest docker image v1.0.640. We got an issue when running checkov on our CI.

**To Reproduce**
```
$ checkov --quiet -d directory
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 2, in <module>
    from checkov.main import run
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 23, in <module>
    from checkov.terraform.runner import Runner as tf_runner
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 20, in <module>
    from checkov.terraform.parser import Parser
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/parser.py", line 16, in <module>
    from checkov.terraform.module_loading.registry import ModuleLoaderRegistry
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/module_loading/__init__.py", line 1, in <module>
    from checkov.terraform.module_loading.loaders import *
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/module_loading/loaders/versions_parser.py", line 2, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

**Additional context**
Using Docker Image v1.0.640

**Comment by schosterbarak** [comment]
thank you for reporting this @benjiprod . was fixed by @rotemavni
