### ISSUE TITLE
GoogleComputeFirewallUnrestrictedIngress - KeyError on parsing

### ISSUE THREAD

**Issue by Temikus** [bridgecrewio/checkov#75]
**Describe the bug**
Checkov traces back on checking some of my GCP manifests.

**To Reproduce**
Managed to get a reproducible scenario:

```
temikus λ checkov
...
version: 1.0.131
...

λ mkdir test && cd test                                                                                                                                       
λ wget https://gist.githubusercontent.com/Temikus/6be1f3e408d84f609a739718a42e3cf5/raw/971c5834234d32b3ddf4614defd6a641249d935c/checkov_fail.tf

λ checkov -d .
ERROR:checkov.terraform.checks.resource.gcp.GoogleComputeFirewallUnrestrictedIngress3389:Failed to run check Ensure Google compute firewall ingress does not allow unrestricted rdp access for configuration {'description': ['allow Google health checks and network load balancers access'], 'name': ['my-firewall'], 'network': ['default'], 'allow': [{'protocol': ['icmp']}, {'protocol': ['tcp'], 'ports': [['8080', '443']]}], 'source_ranges': [['130.211.0.0/22', '35.191.0.0/16']], 'target_tags': [['my-tag']]}
Traceback (most recent call last):
  File "/Users/temikus/.homebrew/bin/checkov", line 5, in <module>
    run()
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/main.py", line 37, in run
    report = Runner().run(root_folder, external_checks_dir=args.external_checks_dir, files=file)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/runner.py", line 29, in run
    self.check_tf_definition(report, root_folder, tf_definitions)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/runner.py", line 52, in check_tf_definition
    block_type)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/runner.py", line 66, in run_block
    results = registry.scan(entity, scanned_file, skipped_checks)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/checks/utilities/base_registry.py", line 39, in scan
    entity_name=entity_name, entity_type=entity, skip_info=skip_info)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/checks/utilities/base_check.py", line 44, in run
    raise e
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/checks/utilities/base_check.py", line 33, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/checks/resource/base_check.py", line 20, in scan_entity_conf
    return self.scan_resource_conf(conf)
  File "/Users/temikus/.homebrew/lib/python3.7/site-packages/checkov/terraform/checks/resource/gcp/GoogleComputeFirewallUnrestrictedIngress3389.py", line 22, in scan_resource_conf
    if PORT in conf['allow'][0]['ports'][0]:
KeyError: 'ports'
```

**Expected behavior**
Not errorring out.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: OSX Mojave 10.14.6
 - Checkov Version: 1.0.131

**Comment by schosterbarak** [comment]
hey @Temikus , Thank you for reporting this!
Just pushing a fix at: https://github.com/bridgecrewio/checkov/pull/76
Can you let me know if that works for you in latest checkov version?

**Comment by Temikus** [comment]
@schosterbarak thanks for the quick response! This looks fixed 👍 

```
λ checkov -d .

       _               _
   ___| |__   ___  ___| | _______   __
  / __| '_ \ / _ \/ __| |/ / _ \ \ / /
 | (__| | | |  __/ (__|   < (_) \ V /
  \___|_| |_|\___|\___|_|\_\___/ \_/

version: 1.0.132

Passed checks: 4, Failed checks: 0, Skipped checks: 0

Check: CKV_GCP_3: "Ensure Google compute firewall ingress does not allow unrestricted rdp access"
	PASSED for resource: google_compute_firewall.ci
	File: /:150-167


Check: CKV_GCP_2: "Ensure Google compute firewall ingress does not allow unrestricted ssh access"
	PASSED for resource: google_compute_firewall.ci
	File: /:150-167


Check: CKV_GCP_3: "Ensure Google compute firewall ingress does not allow unrestricted rdp access"
	PASSED for resource: google_compute_firewall.ci
	File: /:152-169


Check: CKV_GCP_2: "Ensure Google compute firewall ingress does not allow unrestricted ssh access"
	PASSED for resource: google_compute_firewall.ci
	File: /:152-169
```

**Comment by schosterbarak** [comment]
@Temikus Thank you for getting back on this.
Can you share what other resources might be of value? it will help me prfioritize checkov GCP checks by community feedback

**Comment by Temikus** [comment]
@schosterbarak I think CloudSQL may be a low-hanging fruit, e.g.:
- Non-ha instances
- No maintenance windows configured
- No backups configured
- Auto storage increase is disabled
- Unsecured connections are allowed to connect to the instance
- Public connections are allowed from any IP address
- Micro-instances used for production workloads

I'm happy to collab on more ideas! I like this project.

**Comment by schosterbarak** [comment]
- Unsecured connections are allowed to connect to the instance - is covered in CKV_GCP_6
- Public connections are allowed from any IP address - is covered in CKV_GCP_11
- No backups configured - is covered in CKV_GCP_14 (added today to thanks to your comment :) [here](https://github.com/bridgecrewio/checkov/pull/86))

Micro-instances used for production workloads - every developer chooses to mark "production" a bit differently. Checkov has the ability to load external checks (documented [here](https://www.checkov.io/2.Concepts/Custom%20Scans.html)) would love to hear your thoughts on that one.

Full list of checkov checks:
https://github.com/bridgecrewio/checkov//blob/master/docs/3.Scans/resource-scans.md
Contributions are welcome!
