### ISSUE TITLE
ERROR:checkov.terraform.checks.resource.aws.IAMPolicyAttachedToGroupOrRoles:Failed to run check for terraform plan

### ISSUE THREAD

**Issue by ismailyenigul** [bridgecrewio/checkov#802]
**Describe the bug**

Testing cloudtrail audit with the code at https://github.com/trussworks/terraform-aws-cloudtrail/blob/v4.2.0/examples/simple/main.tf (terraform 0.13)
scanning tf files works fine as expected.
but fails to parse terraform plan of the same code.

**To Reproduce**
1. download code https://github.com/trussworks/terraform-aws-cloudtrail/releases/tag/v4.2.0
2. extract and go to the terraform-aws-cloudtrail-4.2.0/examples/simple
3. add region by creating provider.tf
 cat provider.tf 
```
provider "aws" {
  region = "us-east-1"
}
```
4. run terraform init and plan (terraform 0.13 min)
5. run checkov -d . (it all passes)
```terraform scan results:

Passed checks: 17, Failed checks: 0, Skipped checks: 0
Check: CKV_AWS_40: "Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.)"
	PASSED for resource: aws_iam_policy_attachment.main
	File: /../../main.tf:68-72
	Guide: https://docs.bridgecrew.io/docs/iam_16-iam-policy-privileges-1
```	
6. create tf json file by
```
terraform13 plan --out tf.binary
terraform13 show  -json tf.binary > tf.json
jq < tf.json  >tf-formatted.json
checkov -f tf-formatted.json

ERROR:checkov.terraform.checks.resource.aws.IAMPolicyAttachedToGroupOrRoles:Failed to run check: Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.) for configuration: {'groups': [None], 'name': ['cloudtrail-cloudwatch-logs-policy-attachment'], 'roles': [['cloudtrail-cloudwatch-logs-role']], 'users': [None], 'start_line': [91], 'end_line': [98]} at file: /tf-formatted.json
2021-01-21 08:34:36,917 [MainThread  ] [ERROR]  Failed to run check: Ensure IAM policies are attached only to groups or roles (Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.) for configuration: {'groups': [None], 'name': ['cloudtrail-cloudwatch-logs-policy-attachment'], 'roles': [['cloudtrail-cloudwatch-logs-role']], 'users': [None], 'start_line': [91], 'end_line': [98]} at file: /tf-formatted.json
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 5, in <module>
    run()
  File "/usr/local/lib/python3.9/site-packages/checkov/main.py", line 79, in run
    scan_reports = runner_registry.run(external_checks_dir=external_checks_dir, files=args.file,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/runners/runner_registry.py", line 32, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 65, in run
    self.check_tf_definition(report, runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 79, in check_tf_definition
    self.run_block(definition[block_type], full_file_path, report, scanned_file,
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/plan_runner.py", line 95, in run_block
    results = registry.scan(scanned_file, entity, [], runner_filter)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 103, in scan
    result = self.run_check(check, entity_configuration, entity_name, entity_type, scanned_file, skip_info)
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check_registry.py", line 109, in run_check
    result = check.run(scanned_file=scanned_file, entity_configuration=entity_configuration,
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 62, in run
    raise e
  File "/usr/local/lib/python3.9/site-packages/checkov/common/checks/base_check.py", line 42, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 16, in scan_entity_conf
    return self.scan_resource_conf(conf, entity_type)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/base_resource_check.py", line 32, in wrapper
    return wrapped(self, conf)
  File "/usr/local/lib/python3.9/site-packages/checkov/terraform/checks/resource/aws/IAMPolicyAttachedToGroupOrRoles.py", line 18, in scan_resource_conf
    if 'users' in conf.keys() and len(conf['users'][0]) > 0:
TypeError: object of type 'NoneType' has no len()

```

I commented the following lines to skip this test in main.tf of the module
```
# resource "aws_iam_policy_attachment" "main" {
#   name       = "cloudtrail-cloudwatch-logs-policy-attachment"
#   policy_arn = aws_iam_policy.cloudtrail_cloudwatch_logs.arn
#   roles      = [aws_iam_role.cloudtrail_cloudwatch_role.name]
# }
```
But got the following failed checks which should not.

```
Check: CKV_AWS_21: "Ensure all data stored in the S3 bucket have versioning enabled"
	FAILED for resource: aws_s3_bucket.aws_logs
	File: /tf-formatted.json:452-501
	Guide: https://docs.bridgecrew.io/docs/s3_16-enable-versioning

		453 |               "values": {
		454 |                 "acl": "log-delivery-write",
		455 |                 "bucket": "log-124455555",
	
```
but versioning is enabled.

```
1716           "website": []
1717         },
1718         "after_unknown": {
1719           "acceleration_status": true,
1720           "arn": true,
1721           "bucket_domain_name": true,
1722           "bucket_regional_domain_name": true,
1723           "cors_rule": [],
1724           "grant": [],
 ...
           ],
1753           "tags": {},
1754           "versioning": true,
1755           "website": [],
1756           "website_domain": true,
1757           "website_endpoint": true
1758         }

```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Checkov Version 1.0.711

**Comment by schosterbarak** [comment]
Thank you for fixing this one @ismailyenigul
