### ISSUE TITLE
Malformed resource causes crash

### ISSUE THREAD

**Issue by robeden** [bridgecrewio/checkov#857]
**Describe the bug**
A malformed resource like this causes an exception that kills off all subsequent checks:
```terraform
resource "aws_instance" {
  ami = "amiid"
  instance_type = "t3.micro"
}
```

Example error:
```
Traceback (most recent call last):
  File "/Users/robeden/git/third-party/checkov/checkov/common/checks/base_check.py", line 62, in run
    raise e
  File "/Users/robeden/git/third-party/checkov/checkov/common/checks/base_check.py", line 42, in run
    check_result['result'] = self.scan_entity_conf(entity_configuration, entity_type)
  File "/Users/robeden/git/third-party/checkov/checkov/terraform/checks/resource/base_resource_check.py", line 16, in scan_entity_conf
    self.handle_dynamic_values(conf)
  File "/Users/robeden/git/third-party/checkov/checkov/terraform/checks/resource/base_resource_check.py", line 38, in handle_dynamic_values
    for dynamic_element in conf.get("dynamic", []):
AttributeError: 'list' object has no attribute 'get'
```

**Expected behavior**
The bad data should be skipped before being passed to checks.

Long term: it would be good to catch exceptions thrown by checks and report that something didn't work properly with the check.

**Comment by nimrodkor** [comment]
+1
