### ISSUE TITLE
auto.tfvars file parsing error

### ISSUE THREAD

**Issue by MrLuje** [bridgecrewio/checkov#865]
**Describe the bug**
Parsing error on a auto.tfvars file

**To Reproduce**
1. Create a variables.tf file with the following content
```hcl2
variable "environment" {
  type = string
}
```
2. Create a default.auto.tfvars file with the following content 
```hcl2
environment = "dev"
```
3. Run cli command  checkov -d {path to folder}
```log
DEBUG:checkov.terraform.parser:failed while parsing file <DirEntry 'default.auto.tfvars'>
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/checkov/1.0.765/libexec/lib/python3.9/site-packages/checkov/terraform/parser.py", line 723, in _load_or_die_quietly
    return _clean_bad_definitions(hcl2.load(f))
  File "/home/linuxbrew/.linuxbrew/Cellar/checkov/1.0.765/libexec/lib/python3.9/site-packages/checkov/terraform/parser.py", line 731, in _clean_bad_definitions
    return {
  File "/home/linuxbrew/.linuxbrew/Cellar/checkov/1.0.765/libexec/lib/python3.9/site-packages/checkov/terraform/parser.py", line 732, in <dictcomp>
    block_type: list(filter(lambda definition_list: block_type == 'locals' or
  File "/home/linuxbrew/.linuxbrew/Cellar/checkov/1.0.765/libexec/lib/python3.9/site-packages/checkov/terraform/parser.py", line 733, in <lambda>
    len(definition_list.keys()) == 1, tf_definition_list[block_type]))
AttributeError: 'str' object has no attribute 'keys'
```

**Expected behavior**
File should be properly parsed

**Desktop (please complete the following information):**
 - OS: Windows 10 + WSL2
 - Checkov Version : 1.0.765

**Comment by robeden** [comment]
I'm actually working on this right now. Looks like something broke at some point with all .tfvar files.

**Comment by MrLuje** [comment]
Oh ok, that was the first time I was using checkov... I was wondering if I was using it in a wrong way, since I also had some old syntax lying around to fix :)

**Comment by robeden** [comment]
> Oh ok, that was the first time I was using checkov... 

Ack, sorry for the poor first impression. Fix coming soon. 😄

**Comment by MrLuje** [comment]
> > Oh ok, that was the first time I was using checkov...
> 
> Ack, sorry for the poor first impression. Fix coming soon. 😄

No problem, thanks for the quick fix 😃
