### ISSUE TITLE
Checkov throws an exception with serverless when it has only an Output resource block

### ISSUE THREAD

**Issue by DevelopmentTeamMojo** [bridgecrewio/checkov#934]
Checkov throws an exception with serverless when it has only an Output resource block defined 

```
Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Roaming\Python\Python39\Scripts\checkov.cmd", line 53, in <module>
    run()
  File "C:\Users\xyz\AppData\Roaming\Python\Python39\site-packages\checkov\main.py", line 97, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "C:\Users\xyz\AppData\Roaming\Python\Python39\site-packages\checkov\common\runners\runner_registry.py", line 34, in run
    scan_report = runner.run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "C:\Users\xyz\AppData\Roaming\Python\Python39\site-packages\checkov\serverless\runner.py", line 106, in run
    for resource_name, resource in cf_sub_template['Resources'].items():
KeyError: 'Resources'
```

**To Reproduce**
Here's a sample serverless.yml config 

```
service: my-function
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  my-function:
    name: my-function-${opt:stage}
    handler: index.handler

resources:
  Outputs:
    MyFunctionArn:
      Value: 
        Fn::GetAtt: [ MyDashFunctionLambdaFunction, Arn ]
      Export:
        Name: MyFunctionArn
```

**Screenshots**

**Comment by tomaszdudek7** [comment]
Was this fixed by any chance?

**Comment by gruebel** [comment]
it doesn't throw an error, but it also doesn't scan anything in the file 😄 which is better than before, but still a bug
