### ISSUE TITLE
UnboundLocalError: local variable 'root' referenced before assignment, in terraform/plan_runner.py

### ISSUE THREAD

**Issue by KevinHock** [bridgecrewio/checkov#951]
Version: `1.0.831` (latest as of today)

**Describe the bug**
When passing a file that is failed to load, there is a crash, from line 67 of `plan_runner.py`

**To Reproduce**
1. `checkov --check CKV_AWS_2 --file does_not_exist.tf --file totes_valid_file.tf`
2. 
```python
ERROR:checkov.cloudformation.parser:Template file not found: does_not_exist.tf
2021-03-08 23:04:01,749 [MainThread  ] [ERROR]  Template file not found: does_not_exist.tf
ERROR:checkov.arm.parser:Template file not found: does_not_exist.tf
2021-03-08 23:04:01,750 [MainThread  ] [ERROR]  Template file not found: does_not_exist.tf
Traceback (most recent call last):
  File "/home/KevinHock/py37venv/bin/checkov", line 5, in <module>
    run()
  File "/home/KevinHock/py37venv/lib/python3.7/site-packages/checkov/main.py", line 108, in run
    guidelines=guidelines, bc_integration=bc_integration)
  File "/home/KevinHock/py37venv/lib/python3.7/site-packages/checkov/common/runners/runner_registry.py", line 35, in run
    runner_filter=self.runner_filter, collect_skip_comments=collect_skip_comments)
  File "/home/KevinHock/py37venv/lib/python3.7/site-packages/checkov/terraform/plan_runner.py", line 67, in run
    logging.debug(f'Failed to load {root}/{file} as is not a .json file, skipping')
UnboundLocalError: local variable 'root' referenced before assignment
```

**Expected behavior**
No crash, just yelling/debug stuff.

**Comment by KevinHock** [comment]
I don't care about this issue that much, i.e. it is not impacting my work, but figured I would make it 👍🏼

**Comment by KevinHock** [comment]
Fixed 2 hours ago, just not bumped yet maybe https://github.com/bridgecrewio/checkov/commit/dd0fefb6162c877f346a50e3e12696e2de73dfda
